import { useSettings } from "../providers/SettingsProvider";

const copy = {
  en: {
    operations: "Operations",
    operationsSubtitle: "Keep learning journeys healthy and safe.",
    overview: "Overview",
    users: "People",
    jobs: "Processing",
    lessons: "Lessons",
    audit: "Audit log",
    system: "System",
    returnToApp: "Return to ClipQuest",
    accessDenied: "Operations access required",
    accessDeniedBody: "This area is limited to authorized ClipQuest operators.",
    loading: "Loading operations data…",
    loadFailed: "Could not load this operations view.",
    retry: "Try again",
    search: "Search",
    searchPlaceholder: "Search by name, email, title, or ID",
    clear: "Clear",
    previous: "Previous",
    next: "Next",
    results: "results",
    noResults: "No matching records",
    noResultsBody: "Adjust the search or filter and try again.",
    all: "All",
    active: "Active",
    failed: "Failed",
    complete: "Complete",
    queued: "Queued",
    running: "Running",
    banned: "Suspended",
    role: "Role",
    joined: "Joined",
    lastSeen: "Last seen",
    never: "Never",
    attempts: "Attempts",
    owner: "Owner",
    admin: "Operator",
    user: "Learner",
    verified: "Verified",
    unverified: "Unverified",
    suspend: "Suspend",
    restore: "Restore",
    revokeSessions: "Revoke sessions",
    changeRole: "Change role",
    reason: "Reason",
    reasonPlaceholder: "Add a clear operational reason",
    cancel: "Cancel",
    confirm: "Confirm action",
    actionSucceeded: "Action completed and added to the audit log.",
    actionFailed: "The action could not be completed.",
    retryJob: "Retry job",
    cancelJob: "Cancel job",
    progress: "Progress",
    updated: "Updated",
    questions: "Questions",
    watched: "Watched",
    notWatched: "Not watched",
    language: "Language",
    actor: "Actor",
    action: "Action",
    target: "Target",
    outcome: "Outcome",
    success: "Success",
    configuration: "Configuration",
    configured: "Configured",
    unavailable: "Unavailable",
    model: "Question model",
    database: "Database migration",
    queueHealth: "Generation jobs",
    totalUsers: "Total learners",
    totalLessons: "Generated lessons",
    activeJobs: "Active jobs",
    failedJobs: "Failed jobs",
    activity7d: "Last 7 days",
    newUsers: "New learners",
    completedAttempts: "Completed attempts",
    recentFailures: "Recent processing failures",
    recentFailuresBody:
      "Only operational error summaries are shown. Transcript text stays private.",
    noFailures: "No recent failures",
    protectedData: "Protected data boundary",
    protectedDataBody:
      "Secrets, auth tokens, raw transcripts, correct-answer payloads, and password controls are never exposed here.",
    openOperations: "Open operations console",
  },
  "zh-CN": {
    operations: "运营管理",
    operationsSubtitle: "维护学习任务的稳定与安全。",
    overview: "概览",
    users: "用户",
    jobs: "处理任务",
    lessons: "课程",
    audit: "审计记录",
    system: "系统",
    returnToApp: "返回 ClipQuest",
    accessDenied: "需要运营权限",
    accessDeniedBody: "此区域仅限获得授权的 ClipQuest 运营人员。",
    loading: "正在加载运营数据…",
    loadFailed: "无法加载此运营页面。",
    retry: "重试",
    search: "搜索",
    searchPlaceholder: "按姓名、邮箱、标题或 ID 搜索",
    clear: "清除",
    previous: "上一页",
    next: "下一页",
    results: "条结果",
    noResults: "没有匹配记录",
    noResultsBody: "请调整搜索或筛选条件后重试。",
    all: "全部",
    active: "正常",
    failed: "失败",
    complete: "完成",
    queued: "排队中",
    running: "处理中",
    banned: "已停用",
    role: "角色",
    joined: "加入时间",
    lastSeen: "最近活跃",
    never: "从未",
    attempts: "答题次数",
    owner: "所有者",
    admin: "运营人员",
    user: "学习者",
    verified: "已验证",
    unverified: "未验证",
    suspend: "停用",
    restore: "恢复",
    revokeSessions: "撤销会话",
    changeRole: "更改角色",
    reason: "原因",
    reasonPlaceholder: "填写明确的运营原因",
    cancel: "取消",
    confirm: "确认操作",
    actionSucceeded: "操作已完成并写入审计记录。",
    actionFailed: "无法完成此操作。",
    retryJob: "重试任务",
    cancelJob: "取消任务",
    progress: "进度",
    updated: "更新时间",
    questions: "题目",
    watched: "已观看",
    notWatched: "未观看",
    language: "语言",
    actor: "操作人员",
    action: "操作",
    target: "目标",
    outcome: "结果",
    success: "成功",
    configuration: "配置",
    configured: "已配置",
    unavailable: "不可用",
    model: "题目模型",
    database: "数据库迁移",
    queueHealth: "生成任务",
    totalUsers: "用户总数",
    totalLessons: "已生成课程",
    activeJobs: "活跃任务",
    failedJobs: "失败任务",
    activity7d: "最近 7 天",
    newUsers: "新用户",
    completedAttempts: "已完成答题",
    recentFailures: "近期处理失败",
    recentFailuresBody: "这里只显示运营错误摘要，转写文本始终保持私密。",
    noFailures: "近期没有失败任务",
    protectedData: "受保护数据边界",
    protectedDataBody:
      "密钥、认证令牌、原始转写、正确答案和密码控制永远不会在此显示。",
    openOperations: "打开运营管理台",
  },
} as const;

export function useAdminCopy() {
  const { locale } = useSettings();
  return copy[locale];
}
