import { useSettings } from "../providers/SettingsProvider";

const copy = {
  en: {
    operations: "Operations",
    operationsSubtitle: "Keep learning journeys healthy and safe.",
    overview: "Overview",
    users: "People",
    jobs: "Generation streams",
    lessons: "Lessons",
    audit: "Audit log",
    system: "System",
    returnToApp: "Return to ClipQuest",
    accessDenied: "Operations access required",
    accessDeniedBody: "This area is limited to authorized ClipQuest operators.",
    loading: "Loading operations data…",
    loadFailed: "Could not load this operations view.",
    retry: "Try again",
    search: "Search",
    searchPlaceholder: "Search by name, email, title, or ID",
    clear: "Clear",
    previous: "Previous",
    next: "Next",
    results: "results",
    noResults: "No matching records",
    noResultsBody: "Adjust the search or filter and try again.",
    all: "All",
    active: "Active",
    failed: "Failed",
    complete: "Complete",
    queued: "Queued",
    running: "Running",
    banned: "Suspended",
    role: "Role",
    joined: "Joined",
    lastSeen: "Last seen",
    never: "Never",
    attempts: "Attempts",
    owner: "Owner",
    admin: "Operator",
    user: "Learner",
    verified: "Verified",
    unverified: "Unverified",
    suspend: "Suspend",
    restore: "Restore",
    revokeSessions: "Revoke sessions",
    changeRole: "Change role",
    reason: "Reason",
    reasonPlaceholder: "Add a clear operational reason",
    cancel: "Cancel",
    confirm: "Confirm action",
    actionSucceeded: "Action completed and added to the audit log.",
    actionFailed: "The action could not be completed.",
    retryJob: "Retry job",
    cancelJob: "Cancel job",
    progress: "Progress",
    updated: "Updated",
    questions: "Questions",
    watched: "Watched",
    notWatched: "Not watched",
    language: "Language",
    actor: "Actor",
    action: "Action",
    target: "Target",
    outcome: "Outcome",
    success: "Success",
    configuration: "Configuration",
    configured: "Configured",
    unavailable: "Unavailable",
    disabled: "Disabled",
    available: "Available",
    disabledByDesign: "Disabled by design",
    required: "Required",
    model: "Question model",
    generationArchitecture: "Generation architecture",
    localAiGeneration: "ClipQuest Local AI generation",
    workerGeneration: "Worker generation",
    extensionRequirement: "Local AI extension",
    pipeline: "Quiz pipeline",
    promptVersion: "Prompt version",
    validatorVersion: "Validator version",
    generationRollout: "v5.8 concept-first rollout",
    supportedGenerationProfile: "Supported generation profile",
    effectiveDefaultProfile: "Effective default profile",
    groundedExtensionRequirement: "Grounded extension contract",
    workerVersion: "Worker version",
    database: "Database migration",
    queueHealth: "Generation states",
    totalUsers: "Total learners",
    totalLessons: "Generated lessons",
    activeJobs: "Active generations",
    failedJobs: "Needs attention",
    activity7d: "Last 7 days",
    newUsers: "New learners",
    completedAttempts: "Completed attempts",
    recentFailures: "Generations needing attention",
    recentFailuresBody:
      "Only bounded local-stream status is shown. Captions and model responses stay private.",
    noFailures: "No recent failures",
    generationStreamsSubtitle:
      "Read-only progress from learner-owned ClipQuest Local AI streams.",
    generationState: "Generation state",
    generating: "Generating",
    retrying: "Retrying",
    recovering: "Recovering automatically",
    cooldown: "Cooling down automatically",
    retryRequired: "Legacy recovery required",
    actionRequired: "Configuration required",
    generationFailed: "Automatic recovery failed",
    ready: "Ready",
    questionsReady: "Questions ready",
    questionTypes: "Question types",
    aiCalls: "AI calls",
    retries: "Retries",
    primaryCalls: "Primary calls",
    automaticRetries: "Automatic retries",
    automaticRecoveries: "Automatic recovery sessions",
    legacyManualContinuations: "Legacy continuation-classified calls",
    legacyManualContinuationsNote:
      "Historical protocol rows use this label for compatibility; they do not prove that a learner clicked a continuation control.",
    partialCalls: "Partial calls",
    firstQuestionLatency: "Question 1 latency",
    tokenUsage: "Token usage",
    telemetrySource: "Telemetry",
    authoritativeTelemetry: "Authoritative call events",
    legacyTelemetry: "Legacy summary",
    outcomes: "Outcomes",
    lastQuestion: "Last accepted question",
    lastCall: "Last call attempt",
    configurationActionRequired:
      "The learner must repair their private DeepSeek configuration; ClipQuest resumes automatically afterward.",
    automaticRecoveryFailed:
      "Automatic recovery ended safely. The incomplete bank cannot be scored; the learner can start a new quiz.",
    protectedData: "Protected data boundary",
    protectedDataBody:
      "Secrets, auth tokens, raw transcripts, correct-answer payloads, and password controls are never exposed here.",
    openOperations: "Open operations console",
  },
  "zh-CN": {
    operations: "运营管理",
    operationsSubtitle: "维护学习任务的稳定与安全。",
    overview: "概览",
    users: "用户",
    jobs: "生成流",
    lessons: "课程",
    audit: "审计记录",
    system: "系统",
    returnToApp: "返回 ClipQuest",
    accessDenied: "需要运营权限",
    accessDeniedBody: "此区域仅限获得授权的 ClipQuest 运营人员。",
    loading: "正在加载运营数据…",
    loadFailed: "无法加载此运营页面。",
    retry: "重试",
    search: "搜索",
    searchPlaceholder: "按姓名、邮箱、标题或 ID 搜索",
    clear: "清除",
    previous: "上一页",
    next: "下一页",
    results: "条结果",
    noResults: "没有匹配记录",
    noResultsBody: "请调整搜索或筛选条件后重试。",
    all: "全部",
    active: "正常",
    failed: "失败",
    complete: "完成",
    queued: "排队中",
    running: "处理中",
    banned: "已停用",
    role: "角色",
    joined: "加入时间",
    lastSeen: "最近活跃",
    never: "从未",
    attempts: "答题次数",
    owner: "所有者",
    admin: "运营人员",
    user: "学习者",
    verified: "已验证",
    unverified: "未验证",
    suspend: "停用",
    restore: "恢复",
    revokeSessions: "撤销会话",
    changeRole: "更改角色",
    reason: "原因",
    reasonPlaceholder: "填写明确的运营原因",
    cancel: "取消",
    confirm: "确认操作",
    actionSucceeded: "操作已完成并写入审计记录。",
    actionFailed: "无法完成此操作。",
    retryJob: "重试任务",
    cancelJob: "取消任务",
    progress: "进度",
    updated: "更新时间",
    questions: "题目",
    watched: "已观看",
    notWatched: "未观看",
    language: "语言",
    actor: "操作人员",
    action: "操作",
    target: "目标",
    outcome: "结果",
    success: "成功",
    configuration: "配置",
    configured: "已配置",
    unavailable: "不可用",
    disabled: "已禁用",
    available: "可用",
    disabledByDesign: "按设计禁用",
    required: "必需",
    model: "题目模型",
    generationArchitecture: "生成架构",
    localAiGeneration: "ClipQuest 本地 AI 生成",
    workerGeneration: "Worker 生成",
    extensionRequirement: "本地 AI 扩展",
    pipeline: "测验流水线",
    promptVersion: "提示词版本",
    validatorVersion: "验证器版本",
    generationRollout: "v5.8 知识点优先发布范围",
    supportedGenerationProfile: "当前支持的生成配置",
    effectiveDefaultProfile: "实际默认生成配置",
    groundedExtensionRequirement: "基于证据的扩展协议",
    workerVersion: "Worker 版本",
    database: "数据库迁移",
    queueHealth: "生成状态",
    totalUsers: "用户总数",
    totalLessons: "已生成课程",
    activeJobs: "活跃生成",
    failedJobs: "需要关注",
    activity7d: "最近 7 天",
    newUsers: "新用户",
    completedAttempts: "已完成答题",
    recentFailures: "需要关注的生成",
    recentFailuresBody:
      "这里只显示有限的本地生成状态，字幕和模型响应始终保持私密。",
    noFailures: "近期没有失败任务",
    generationStreamsSubtitle:
      "只读显示由学习者本地 ClipQuest AI 扩展生成的进度。",
    generationState: "生成状态",
    generating: "生成中",
    retrying: "重试中",
    recovering: "自动恢复中",
    cooldown: "自动冷却中",
    retryRequired: "旧版恢复需求",
    actionRequired: "需要配置",
    generationFailed: "自动恢复失败",
    ready: "已就绪",
    questionsReady: "已就绪题目",
    questionTypes: "题目类型",
    aiCalls: "AI 调用",
    retries: "重试次数",
    primaryCalls: "主调用",
    automaticRetries: "自动重试",
    automaticRecoveries: "自动恢复会话",
    legacyManualContinuations: "旧版继续分类调用",
    legacyManualContinuationsNote:
      "历史协议行仅为兼容而保留此分类；它不能证明学习者曾点击继续生成控件。",
    partialCalls: "部分成功调用",
    firstQuestionLatency: "第一题延迟",
    tokenUsage: "Token 用量",
    telemetrySource: "遥测来源",
    authoritativeTelemetry: "权威调用事件",
    legacyTelemetry: "旧版汇总",
    outcomes: "结果",
    lastQuestion: "最后接收题目",
    lastCall: "最后调用尝试",
    configurationActionRequired:
      "学习者需要修复私有 DeepSeek 配置；验证后 ClipQuest 会自动恢复。",
    automaticRecoveryFailed:
      "自动恢复已安全结束。不完整题库不会计分，学习者可开始新的测验。",
    protectedData: "受保护数据边界",
    protectedDataBody:
      "密钥、认证令牌、原始转写、正确答案和密码控制永远不会在此显示。",
    openOperations: "打开运营管理台",
  },
} as const;

export function useAdminCopy() {
  const { locale } = useSettings();
  return copy[locale];
}
