import type { TranscriptSegment } from "@clipquest/contracts";
import { Innertube } from "youtubei.js/cf-worker";
import { ApiError } from "../lib/errors";
import type { AudioStream, SourceAdapter, SourceVideo } from "./types";
import { parseYouTubeId } from "./url";

async function createYouTubeClient(retrievePlayer: boolean): Promise<Innertube> {
  return Innertube.create({
    lang: "en",
    location: "US",
    retrieve_player: retrievePlayer,
    generate_session_locally: true,
    enable_session_cache: false,
  });
}

function getBestThumbnail(thumbnails: Array<{ url: string; width?: number }>): string {
  return [...thumbnails].sort((a, b) => (b.width ?? 0) - (a.width ?? 0))[0]?.url ?? "";
}

export class YouTubeAdapter implements SourceAdapter {
  async inspect(url: URL): Promise<SourceVideo> {
    const sourceVideoId = parseYouTubeId(url);
    try {
      const client = await createYouTubeClient(false);
      const info = await client.getBasicInfo(sourceVideoId, { client: "WEB" });
      const tracks = info.captions?.caption_tracks ?? [];
      const captionTracks = tracks.map((track) => ({
        language: track.language_code,
        label: track.name.toString(),
        isAutoGenerated: track.kind === "asr",
      }));

      let preferredCaptionSegments: TranscriptSegment[] | undefined;
      if (tracks.length > 0) {
        try {
          let transcript = await info.getTranscript();
          const preferredLanguage = transcript.languages.find((language) => /^(English|Chinese|中文|简体)/i.test(language));
          if (preferredLanguage && preferredLanguage !== transcript.selectedLanguage) {
            transcript = await transcript.selectLanguage(preferredLanguage);
          }
          const segments = transcript.transcript.content?.body?.initial_segments ?? [];
          preferredCaptionSegments = segments.flatMap((segment, index) => {
            if (!("start_ms" in segment) || !("end_ms" in segment) || !("snippet" in segment)) return [];
            const startMs = Number.parseInt(segment.start_ms, 10);
            const endMs = Number.parseInt(segment.end_ms, 10);
            const text = segment.snippet.toString().trim();
            if (!Number.isFinite(startMs) || !Number.isFinite(endMs) || !text) return [];
            return [{ id: `yt-${index + 1}`, startMs, endMs, text }];
          });
        } catch (error) {
          console.warn("YouTube captions were listed but could not be loaded", error);
        }
      }

      return {
        source: "youtube",
        sourceVideoId,
        canonicalUrl: `https://www.youtube.com/watch?v=${sourceVideoId}`,
        title: info.basic_info.title?.trim() || "YouTube video",
        thumbnailUrl:
          getBestThumbnail(info.basic_info.thumbnail ?? []) ||
          `https://i.ytimg.com/vi/${sourceVideoId}/hqdefault.jpg`,
        durationSeconds: Math.max(0, Math.round(info.basic_info.duration ?? 0)),
        sourceLanguage: tracks[0]?.language_code ?? null,
        captionTracks,
        ...(preferredCaptionSegments?.length ? { preferredCaptionSegments } : {}),
      };
    } catch (error) {
      console.error("YouTube inspection failed", error);
      throw new ApiError(502, "youtube_unavailable", "YouTube could not provide this video right now. Try again shortly.");
    }
  }

  async streamAudio(sourceVideoId: string, request: Request): Promise<AudioStream> {
    try {
      const client = await createYouTubeClient(true);
      const range = parseRange(request.headers.get("range"));
      const body = await client.download(sourceVideoId, {
        type: "audio",
        quality: "bestefficiency",
        format: "any",
        ...(range ? { range } : {}),
      });
      return {
        body,
        contentType: "audio/mp4",
        acceptRanges: "bytes",
      };
    } catch (error) {
      console.error("YouTube audio stream failed", error);
      throw new ApiError(502, "audio_stream_unavailable", "The audio stream could not be prepared.");
    }
  }
}

function parseRange(value: string | null): { start: number; end: number } | undefined {
  if (!value) return undefined;
  const match = value.match(/^bytes=(\d+)-(\d+)$/);
  if (!match?.[1] || !match[2]) return undefined;
  const start = Number.parseInt(match[1], 10);
  const end = Number.parseInt(match[2], 10);
  return Number.isFinite(start) && Number.isFinite(end) && end >= start ? { start, end } : undefined;
}
