plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

group = 'cc.ccwu.clipquest.audio'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "cc.ccwu.clipquest.audio"
  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36
  }
}

