import assert from "node:assert/strict";
import test from "node:test";

globalThis.document = {
  createElement() {
    return {
      set innerHTML(value) {
        this.value = value
          .replaceAll("&amp;", "&")
          .replaceAll("&lt;", "<")
          .replaceAll("&gt;", ">");
      },
      value: "",
    };
  },
};
await import("../src/caption-core.js");
const { captionsToPlainText } = await import("../src/caption-text.js");
const core = globalThis.ClipQuestCaptionCore;

test("selectTrack prefers a matching human track and supports ASR fallback", () => {
  const tracks = [
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
      languageCode: "en",
      kind: "asr",
      name: { simpleText: "English (auto-generated)" },
    },
    {
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=zh-Hans",
      languageCode: "zh-Hans",
      name: { simpleText: "Chinese" },
    },
  ];
  assert.equal(core.selectTrack(tracks, "zh-CN").language, "zh-Hans");
  assert.equal(core.selectTrack(tracks, "en").isAutoGenerated, true);
});

test("parseJson3 keeps timestamped caption text", () => {
  assert.deepEqual(
    core.parseJson3({
      events: [
        {
          tStartMs: 1_250,
          dDurationMs: 2_000,
          segs: [{ utf8: "Auto " }, { utf8: "captions\nwork" }],
        },
      ],
    }),
    [
      {
        id: "youtube-extension-0-1250",
        startMs: 1_250,
        endMs: 3_250,
        text: "Auto captions work",
      },
    ],
  );
});

test("parseXml supports legacy timed text", () => {
  assert.deepEqual(
    core.parseXml(
      '<transcript><text start="2.5" dur="1.25">A &amp; B</text></transcript>',
    ),
    [
      {
        id: "youtube-extension-xml-0-2500",
        startMs: 2_500,
        endMs: 3_750,
        text: "A & B",
      },
    ],
  );
});

test("parseXml supports the player srv3 paragraph format", () => {
  assert.deepEqual(
    core.parseXml(
      '<timedtext><body><p t="1250" d="2000">Auto &amp; local</p></body></timedtext>',
    ),
    [
      {
        id: "youtube-extension-xml-0-1250",
        startMs: 1_250,
        endMs: 3_250,
        text: "Auto & local",
      },
    ],
  );
});

test("finalizePanelSegments deduplicates and infers end times", () => {
  assert.deepEqual(
    core.finalizePanelSegments([
      { startMs: 4_000, text: "Second line" },
      { startMs: 1_000, text: "First line" },
      { startMs: 1_000, text: "First line" },
    ]),
    [
      {
        id: "youtube-extension-panel-0-1000",
        startMs: 1_000,
        endMs: 4_000,
        text: "First line",
      },
      {
        id: "youtube-extension-panel-1-4000",
        startMs: 4_000,
        endMs: 34_000,
        text: "Second line",
      },
    ],
  );
});

test("captionsToPlainText removes timestamps and preserves caption order", () => {
  assert.equal(
    captionsToPlainText([
      { startMs: 2_000, endMs: 3_000, text: "second line" },
      { startMs: 0, endMs: 1_000, text: "first line" },
    ]),
    "first line second line",
  );
});

test("captionsToPlainText removes repeated rolling-caption overlap", () => {
  assert.equal(
    captionsToPlainText([
      { startMs: 0, text: "A limit is the value a function approaches" },
      {
        startMs: 2_000,
        text: "the value a function approaches near an input",
      },
      {
        startMs: 4_000,
        text: "the value a function approaches near an input",
      },
    ]),
    "A limit is the value a function approaches near an input",
  );
});
