import { z } from "zod";

export const SourceSchema = z.enum(["youtube", "bilibili"]);
export type VideoSource = z.infer<typeof SourceSchema>;

export const LanguageSchema = z.enum(["en", "zh-CN"]);
export type AppLanguage = z.infer<typeof LanguageSchema>;

export const SessionLengthSchema = z.enum(["short", "medium", "long"]);
export type SessionLength = z.infer<typeof SessionLengthSchema>;

export const MasteryStateSchema = z.enum(["not_started", "learning", "mastered"]);
export type MasteryState = z.infer<typeof MasteryStateSchema>;

export const GenerationStageSchema = z.enum([
  "getting_video",
  "preparing_audio",
  "downloading_model",
  "transcribing_device",
  "creating_questions",
  "complete",
  "failed",
]);
export type GenerationStage = z.infer<typeof GenerationStageSchema>;

export const TranscriptSegmentSchema = z
  .object({
    id: z.string().min(1).max(80),
    startMs: z.number().int().nonnegative(),
    endMs: z.number().int().positive(),
    text: z.string().trim().min(1).max(2_000),
  })
  .refine((segment) => segment.endMs > segment.startMs, {
    message: "endMs must be greater than startMs",
  });
export type TranscriptSegment = z.infer<typeof TranscriptSegmentSchema>;

export const CaptionTrackSchema = z.object({
  language: z.string().min(2).max(35),
  label: z.string().min(1).max(80),
  isAutoGenerated: z.boolean(),
});
export type CaptionTrack = z.infer<typeof CaptionTrackSchema>;

const httpUrl = z
  .string()
  .url()
  .max(2_048)
  .refine((value) => value.startsWith("https://") || value.startsWith("http://"), {
    message: "Only HTTP(S) video links are supported",
  });

export const VideoImportRequestSchema = z.object({
  url: httpUrl,
});
export type VideoImportRequest = z.infer<typeof VideoImportRequestSchema>;

export const VideoImportResponseSchema = z.object({
  video: z.object({
    id: z.string(),
    source: SourceSchema,
    sourceVideoId: z.string(),
    title: z.string(),
    thumbnailUrl: z.string().url(),
    durationSeconds: z.number().int().nonnegative(),
    sourceLanguage: z.string().nullable(),
  }),
  captions: z.object({
    available: z.boolean(),
    tracks: z.array(CaptionTrackSchema),
    preferredSegments: z.array(TranscriptSegmentSchema).optional(),
  }),
  requiresLocalTranscription: z.boolean(),
});
export type VideoImportResponse = z.infer<typeof VideoImportResponseSchema>;

export const MediaResolveRequestSchema = z.object({
  videoId: z.string().uuid(),
});
export type MediaResolveRequest = z.infer<typeof MediaResolveRequestSchema>;

export const MediaResolveResponseSchema = z.object({
  mediaUrl: z.string().url(),
  expiresAt: z.string().datetime(),
  maximumDurationSeconds: z.literal(5_400),
});
export type MediaResolveResponse = z.infer<typeof MediaResolveResponseSchema>;

export const TranscriptUploadRequestSchema = z.object({
  videoId: z.string().uuid(),
  language: z.string().min(2).max(35),
  origin: z.enum(["captions", "device_whisper"]),
  segments: z.array(TranscriptSegmentSchema).min(1).max(12_000),
  quizLanguage: LanguageSchema,
  sessionLength: SessionLengthSchema,
  watched: z.boolean(),
});
export type TranscriptUploadRequest = z.infer<typeof TranscriptUploadRequestSchema>;

export const TranscriptUploadResponseSchema = z.object({
  jobId: z.string().uuid(),
  stage: GenerationStageSchema,
});
export type TranscriptUploadResponse = z.infer<typeof TranscriptUploadResponseSchema>;

export const GenerationStatusSchema = z.object({
  jobId: z.string().uuid(),
  stage: GenerationStageSchema,
  progress: z.number().min(0).max(1),
  quizId: z.string().uuid().nullable(),
  error: z
    .object({
      code: z.string(),
      message: z.string(),
    })
    .nullable(),
});
export type GenerationStatus = z.infer<typeof GenerationStatusSchema>;

export const ConceptSchema = z.object({
  id: z.string().min(1).max(80),
  title: z.string().min(1).max(160),
  summary: z.string().min(1).max(600),
  evidenceSegmentIds: z.array(z.string()).min(1),
});
export type Concept = z.infer<typeof ConceptSchema>;

const QuestionBaseSchema = z.object({
  id: z.string().min(1).max(80),
  conceptId: z.string().min(1).max(80),
  prompt: z.string().min(4).max(1_200),
  explanation: z.string().min(4).max(600),
  evidenceSegmentIds: z.array(z.string()).min(1).max(12),
  difficulty: z.number().int().min(1).max(5),
  reformulatedPrompt: z.string().min(4).max(1_200),
});

export const MultipleChoiceQuestionSchema = QuestionBaseSchema.extend({
  type: z.literal("multiple_choice"),
  options: z.array(z.string().min(1).max(500)).min(2).max(6),
  correctAnswer: z.number().int().nonnegative(),
}).refine((question) => question.correctAnswer < question.options.length, {
  message: "correctAnswer must index an option",
});

export const TrueFalseQuestionSchema = QuestionBaseSchema.extend({
  type: z.literal("true_false"),
  correctAnswer: z.boolean(),
});

export const OrderingQuestionSchema = QuestionBaseSchema.extend({
  type: z.literal("ordering"),
  items: z.array(z.string().min(1).max(300)).min(2).max(7),
  correctAnswer: z.array(z.number().int().nonnegative()).min(2).max(7),
}).refine(
  (question) =>
    question.correctAnswer.length === question.items.length &&
    new Set(question.correctAnswer).size === question.items.length &&
    question.correctAnswer.every((index) => index < question.items.length),
  { message: "correctAnswer must be a permutation of item indexes" },
);

export const ShortAnswerQuestionSchema = QuestionBaseSchema.extend({
  type: z.literal("short_answer"),
  rubric: z.object({
    requiredIdeas: z.array(z.string().min(1).max(300)).min(1).max(6),
    acceptableAlternatives: z.array(z.string().min(1).max(300)).max(10),
  }),
});

export const GeneratedQuestionSchema = z.discriminatedUnion("type", [
  MultipleChoiceQuestionSchema,
  TrueFalseQuestionSchema,
  OrderingQuestionSchema,
  ShortAnswerQuestionSchema,
]);
export type GeneratedQuestion = z.infer<typeof GeneratedQuestionSchema>;

export const QuizGenerationSchema = z.object({
  educational: z.literal(true),
  classificationReason: z.string().min(4).max(500),
  sourceLanguage: z.string().min(2).max(35),
  primer: z.string().min(20).max(2_000),
  concepts: z.array(ConceptSchema).min(2).max(20),
  questions: z.array(GeneratedQuestionSchema).min(5).max(30),
});
export type QuizGeneration = z.infer<typeof QuizGenerationSchema>;

export const QuizStartRequestSchema = z.object({
  mode: z.enum(["learn", "review"]).default("learn"),
  sessionLength: SessionLengthSchema,
});
export type QuizStartRequest = z.infer<typeof QuizStartRequestSchema>;

export const PublicQuestionSchema = z.object({
  id: z.string().uuid(),
  type: z.enum(["multiple_choice", "true_false", "ordering", "short_answer"]),
  prompt: z.string(),
  options: z.array(z.string()).optional(),
  items: z.array(z.string()).optional(),
  difficulty: z.number().int().min(1).max(5),
  position: z.number().int().positive(),
  total: z.number().int().positive(),
  isRetry: z.boolean(),
});
export type PublicQuestion = z.infer<typeof PublicQuestionSchema>;

export const QuizStartResponseSchema = z.object({
  attemptId: z.string().uuid(),
  primer: z.string().nullable(),
  question: PublicQuestionSchema,
});
export type QuizStartResponse = z.infer<typeof QuizStartResponseSchema>;

export const AnswerValueSchema = z.union([
  z.number().int().nonnegative(),
  z.boolean(),
  z.array(z.number().int().nonnegative()),
  z.string().trim().min(1).max(2_000),
]);

export const AttemptAnswerRequestSchema = z.object({
  questionId: z.string().uuid(),
  answer: AnswerValueSchema,
});
export type AttemptAnswerRequest = z.infer<typeof AttemptAnswerRequestSchema>;

export const AttemptAnswerResponseSchema = z.object({
  correct: z.boolean(),
  explanation: z.string().min(1),
  evidenceSegmentIds: z.array(z.string()),
  nextQuestion: PublicQuestionSchema.nullable(),
  completed: z.boolean(),
  score: z.number().min(0).max(100).nullable(),
  mastery: MasteryStateSchema.nullable(),
});
export type AttemptAnswerResponse = z.infer<typeof AttemptAnswerResponseSchema>;

export const AttemptResumeResponseSchema = z.object({
  attemptId: z.string().uuid(),
  question: PublicQuestionSchema.nullable(),
  completed: z.boolean(),
  score: z.number().min(0).max(100).nullable(),
  mastery: MasteryStateSchema.nullable(),
});
export type AttemptResumeResponse = z.infer<typeof AttemptResumeResponseSchema>;

export const LibraryCardSchema = z.object({
  videoId: z.string().uuid(),
  quizId: z.string().uuid().nullable(),
  attemptId: z.string().uuid().nullable(),
  originalUrl: httpUrl,
  source: SourceSchema,
  title: z.string(),
  thumbnailUrl: z.string().url(),
  bestScore: z.number().min(0).max(100).nullable(),
  mastery: MasteryStateSchema,
  action: z.enum(["start", "continue", "review"]),
  dueForReview: z.boolean(),
});
export type LibraryCard = z.infer<typeof LibraryCardSchema>;

export const LibraryResponseSchema = z.object({
  dueReviews: z.array(LibraryCardSchema),
  saved: z.array(LibraryCardSchema),
  youtubeSuggestions: z.array(LibraryCardSchema),
});
export type LibraryResponse = z.infer<typeof LibraryResponseSchema>;

export const PushRegisterRequestSchema = z.object({
  token: z.string().min(8).max(1_000),
  platform: z.enum(["ios", "android", "web"]),
  locale: LanguageSchema,
});

export const YouTubeDeviceStartResponseSchema = z.object({
  flowId: z.string().uuid(),
  userCode: z.string().min(4),
  verificationUrl: z.string().url(),
  expiresAt: z.string().datetime(),
  intervalSeconds: z.number().int().positive(),
});

export const YouTubeDeviceStatusSchema = z.object({
  state: z.enum(["pending", "connected", "expired", "failed"]),
  importedCandidates: z.number().int().nonnegative().optional(),
  message: z.string().optional(),
});

const youtubeHosts = new Set(["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"]);
const bilibiliHosts = new Set(["bilibili.com", "www.bilibili.com", "m.bilibili.com", "b23.tv"]);

export function identifyVideoSource(rawUrl: string): VideoSource | null {
  try {
    const host = new URL(rawUrl).hostname.toLowerCase();
    if (youtubeHosts.has(host)) return "youtube";
    if (bilibiliHosts.has(host)) return "bilibili";
    return null;
  } catch {
    return null;
  }
}

export function questionLimitForSession(length: SessionLength): number {
  return length === "short" ? 5 : length === "medium" ? 10 : 15;
}
