import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  requestExtensionYouTubeTranscript: vi.fn(),
  apiRequest: vi.fn(),
  downloadYouTubeCaptions: vi.fn(),
  downloadBrowserYouTubeTranscript: vi.fn(),
}));

vi.mock("react-native", () => ({ Platform: { OS: "web" } }));
vi.mock("../src/transcription/clipquest-extension", () => ({
  requestExtensionYouTubeTranscript: mocks.requestExtensionYouTubeTranscript,
}));
vi.mock("../src/lib/api", () => ({ apiRequest: mocks.apiRequest }));
vi.mock("../src/transcription/youtube-captions", async () => {
  const actual = await vi.importActual<
    typeof import("../src/transcription/youtube-captions")
  >("../src/transcription/youtube-captions");
  return {
    ...actual,
    downloadYouTubeCaptions: mocks.downloadYouTubeCaptions,
    downloadBrowserYouTubeTranscript: mocks.downloadBrowserYouTubeTranscript,
  };
});

import { acquireTextTranscript } from "../src/transcription/acquire-text-transcript";

const imported = {
  video: {
    id: "11111111-1111-4111-8111-111111111111",
    source: "youtube" as const,
    sourceVideoId: "dQw4w9WgXcQ",
    durationSeconds: 60,
    sourceLanguage: "en",
  },
  captions: {
    available: false,
    browserSourceAvailable: false,
    browserLookupAvailable: false,
  },
};

const extensionTranscript = {
  videoId: "dQw4w9WgXcQ",
  durationSeconds: 60,
  language: "English",
  isAutoGenerated: true,
  sourceSegmentCount: 2,
  method: "caption_track" as const,
  segments: [
    { id: "one", startMs: 0, endMs: 30_000, text: "A complete concept." },
    { id: "two", startMs: 30_000, endMs: 60_000, text: "A second concept." },
  ],
};

describe("shared text transcript acquisition", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("shares one extension request across concurrent prework and generation callers", async () => {
    let resolveRequest!: (value: typeof extensionTranscript) => void;
    mocks.requestExtensionYouTubeTranscript.mockImplementation(
      () =>
        new Promise((resolve) => {
          resolveRequest = resolve;
        }),
    );

    const first = acquireTextTranscript(
      imported as never,
      new AbortController().signal,
      undefined,
      "en",
    );
    const second = acquireTextTranscript(
      imported as never,
      new AbortController().signal,
      undefined,
      "en",
    );

    await vi.waitFor(() =>
      expect(mocks.requestExtensionYouTubeTranscript).toHaveBeenCalledOnce(),
    );
    resolveRequest(extensionTranscript);
    const [firstResult, secondResult] = await Promise.all([first, second]);

    expect(firstResult?.acquisition).toBe("youtube_browser_extension");
    expect(secondResult).toEqual(firstResult);
    expect(mocks.downloadBrowserYouTubeTranscript).not.toHaveBeenCalled();
  });

  it("does not abort the shared request when one consumer leaves", async () => {
    let resolveRequest!: (value: typeof extensionTranscript) => void;
    const requestSignal = vi.fn();
    mocks.requestExtensionYouTubeTranscript.mockImplementation(
      (_videoId: string, _language: string, signal: AbortSignal) => {
        signal.addEventListener("abort", requestSignal, { once: true });
        return new Promise((resolve) => {
          resolveRequest = resolve;
        });
      },
    );
    const firstController = new AbortController();
    const secondController = new AbortController();
    const first = acquireTextTranscript(
      imported as never,
      firstController.signal,
      undefined,
      "en",
    );
    const second = acquireTextTranscript(
      imported as never,
      secondController.signal,
      undefined,
      "en",
    );
    await vi.waitFor(() =>
      expect(mocks.requestExtensionYouTubeTranscript).toHaveBeenCalledOnce(),
    );
    firstController.abort();
    await expect(first).rejects.toThrow();
    expect(requestSignal).not.toHaveBeenCalled();
    resolveRequest(extensionTranscript);
    await expect(second).resolves.toMatchObject({
      acquisition: "youtube_browser_extension",
    });
  });
});
