import {
  CaptionResolveResponseSchema,
  createTranscriptCompleteness,
  transcriptCompletenessMatches,
  type TranscriptCompleteness,
  type TranscriptSegment,
  type VideoImportResponse,
  type CaptionSourceCategory,
} from "@clipquest/contracts";
import { Platform } from "react-native";
import { apiRequest } from "../lib/api";
import { requestExtensionYouTubeTranscript } from "./clipquest-extension";
import {
  downloadBrowserYouTubeTranscript,
  downloadYouTubeCaptions,
} from "./youtube-captions";

export type AcquiredTextTranscript = {
  segments: TranscriptSegment[];
  language: string;
  verifiedDurationSeconds: number;
  captionSourceCategory: CaptionSourceCategory;
  completeness: TranscriptCompleteness;
  acquisition:
    | "server_captions"
    | "youtube_browser_extension"
    | "youtube_signed_captions"
    | "youtube_text_provider";
};

export async function acquireTextTranscript(
  imported: VideoImportResponse,
  signal: AbortSignal,
  onProgress?: (progress: number) => void,
  preferredLanguage?: string | null,
): Promise<AcquiredTextTranscript | null> {
  if (imported.captions.preferredSegments?.length) {
    const completeness = imported.captions.preferredCompleteness;
    if (
      !completeness ||
      !transcriptCompletenessMatches(
        completeness,
        imported.captions.preferredSegments,
        imported.video.durationSeconds,
      )
    ) {
      throw new Error(
        "The caption source did not prove that it returned the complete subtitle text.",
      );
    }
    return {
      segments: imported.captions.preferredSegments,
      language: imported.video.sourceLanguage ?? "und",
      verifiedDurationSeconds: imported.video.durationSeconds,
      captionSourceCategory:
        imported.captions.tracks.find(
          (track) => track.language === imported.video.sourceLanguage,
        )?.isAutoGenerated === true
          ? "automatic"
          : imported.captions.tracks.length
            ? "manual"
            : "unknown",
      acquisition: "server_captions",
      completeness,
    };
  }
  if (imported.video.source !== "youtube") return null;

  if (Platform.OS === "web") {
    try {
      onProgress?.(0.1);
      const startedAt = Date.now();
      const transcript = await requestExtensionYouTubeTranscript(
        imported.video.sourceVideoId,
        preferredLanguage ?? imported.video.sourceLanguage,
        signal,
      );
      if (
        imported.video.durationSeconds > 0 &&
        Math.abs(imported.video.durationSeconds - transcript.durationSeconds) >
          Math.max(5, imported.video.durationSeconds * 0.02)
      ) {
        throw new Error(
          "The extension duration did not match the imported YouTube video.",
        );
      }
      const verifiedDurationSeconds =
        imported.video.durationSeconds > 0
          ? imported.video.durationSeconds
          : transcript.durationSeconds;
      const completeness = createTranscriptCompleteness(
        transcript.segments,
        verifiedDurationSeconds,
        transcript.sourceSegmentCount,
      );
      console.info(
        JSON.stringify({
          scope: "caption_acquisition",
          event: "browser_extension.completed",
          sourceVideoId: imported.video.sourceVideoId,
          method: transcript.method,
          isAutoGenerated: transcript.isAutoGenerated,
          sourceSegmentCount: transcript.sourceSegmentCount,
          segmentCount: transcript.segments.length,
          characterCount: completeness.characterCount,
          transcriptComplete: true,
          elapsedMs: Date.now() - startedAt,
        }),
      );
      return {
        segments: transcript.segments,
        language: transcript.language,
        verifiedDurationSeconds,
        captionSourceCategory: transcript.isAutoGenerated
          ? "automatic"
          : "manual",
        acquisition: "youtube_browser_extension",
        completeness,
      };
    } catch (error) {
      if (signal.aborted) throw error;
      console.warn(
        JSON.stringify({
          scope: "caption_acquisition",
          event: "browser_extension.failed",
          sourceVideoId: imported.video.sourceVideoId,
          errorName: error instanceof Error ? error.name : "UnknownError",
        }),
      );
    }
  }

  if (imported.captions.browserSourceAvailable) {
    if (imported.video.durationSeconds < 1) return null;
    try {
      onProgress?.(0.15);
      const startedAt = Date.now();
      const source = await apiRequest(
        `/api/videos/${encodeURIComponent(imported.video.id)}/captions/resolve`,
        { method: "POST", signal },
        CaptionResolveResponseSchema,
      );
      const document = await downloadYouTubeCaptions(source.captionUrl, signal);
      const completeness = createTranscriptCompleteness(
        document.segments,
        imported.video.durationSeconds,
        document.sourceSegmentCount,
      );
      console.info(
        JSON.stringify({
          scope: "caption_acquisition",
          event: "signed_captions.completed",
          sourceVideoId: imported.video.sourceVideoId,
          sourceSegmentCount: document.sourceSegmentCount,
          segmentCount: document.segments.length,
          characterCount: completeness.characterCount,
          transcriptComplete: true,
          elapsedMs: Date.now() - startedAt,
        }),
      );
      if (document.segments.length) {
        return {
          segments: document.segments,
          language: source.language,
          verifiedDurationSeconds: imported.video.durationSeconds,
          captionSourceCategory: "unknown",
          acquisition: "youtube_signed_captions",
          completeness,
        };
      }
    } catch (error) {
      if (signal.aborted) throw error;
      console.warn(
        JSON.stringify({
          scope: "caption_acquisition",
          event: "signed_captions.failed",
          sourceVideoId: imported.video.sourceVideoId,
          errorName: error instanceof Error ? error.name : "UnknownError",
        }),
      );
    }
  }

  if (imported.captions.browserLookupAvailable) {
    try {
      onProgress?.(0.4);
      const startedAt = Date.now();
      const transcript = await downloadBrowserYouTubeTranscript(
        imported.video.sourceVideoId,
        signal,
      );
      if (
        imported.video.durationSeconds > 0 &&
        transcript.durationSeconds &&
        Math.abs(imported.video.durationSeconds - transcript.durationSeconds) >
          Math.max(5, imported.video.durationSeconds * 0.02)
      ) {
        throw new Error(
          "The transcript duration did not match the imported YouTube video.",
        );
      }
      const inferredDurationSeconds = Math.max(
        1,
        Math.ceil(
          Math.max(...transcript.segments.map((segment) => segment.endMs)) /
            1_000,
        ),
      );
      const verifiedDurationSeconds =
        imported.video.durationSeconds > 0
          ? imported.video.durationSeconds
          : (transcript.durationSeconds ?? inferredDurationSeconds);
      const completeness = createTranscriptCompleteness(
        transcript.segments,
        verifiedDurationSeconds,
        transcript.sourceSegmentCount,
      );
      console.info(
        JSON.stringify({
          scope: "caption_acquisition",
          event: "browser_text.completed",
          sourceVideoId: imported.video.sourceVideoId,
          sourceSegmentCount: transcript.sourceSegmentCount,
          segmentCount: transcript.segments.length,
          characterCount: completeness.characterCount,
          transcriptComplete: true,
          elapsedMs: Date.now() - startedAt,
        }),
      );
      return {
        segments: transcript.segments,
        language: transcript.language,
        verifiedDurationSeconds,
        captionSourceCategory: "unknown",
        acquisition: "youtube_text_provider",
        completeness,
      };
    } catch (error) {
      if (signal.aborted) throw error;
      console.warn(
        JSON.stringify({
          scope: "caption_acquisition",
          event: "browser_text.failed",
          sourceVideoId: imported.video.sourceVideoId,
          errorName: error instanceof Error ? error.name : "UnknownError",
        }),
      );
    }
  }
  return null;
}
