import {
  CONCEPT_FIRST_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  AutomaticRetryKindSchema,
  AUTOMATIC_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  GROUNDED_V5_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  GenerationStageSchema,
  GenerationFailureCodeSchema,
  LEGACY_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  STABLE_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  LocalGenerationCallEventSchema,
  LocalConceptQuizGenerationResultSchema,
  LocalConceptQuizQuestionChunkSchema,
  LocalQuizContextSchema,
  CheatSheetContextSchema,
  CheatSheetDocumentSchema,
  LocalAnswerGradeSchema,
  LocalAnswerGradeRequestSchema,
  MAX_COMPLETE_TRANSCRIPT_SEGMENTS,
  TranscriptSegmentSchema,
  type GenerationStage,
  type GenerationFailureCode,
  type LocalConceptQuizQuestionChunk,
  type LocalConceptQuizGenerationResult,
  type LocalGenerationCallEvent,
  type LocalQuizContext,
  type TranscriptSegment,
} from "@clipquest/contracts";
import { Platform } from "react-native";
import {
  MINIMUM_LEGACY_LOCAL_AI_EXTENSION_VERSION,
  MINIMUM_AUTOMATIC_LOCAL_AI_EXTENSION_VERSION,
  MINIMUM_GROUNDED_LOCAL_AI_EXTENSION_VERSION,
  MINIMUM_CONCEPT_FIRST_LOCAL_AI_EXTENSION_VERSION,
  MINIMUM_LOCAL_AI_EXTENSION_VERSION,
  MINIMUM_STABLE_LOCAL_AI_EXTENSION_VERSION,
  isCompatibleClipQuestExtensionVersion,
} from "./extension-compat";

export {
  MINIMUM_LEGACY_LOCAL_AI_EXTENSION_VERSION,
  MINIMUM_LOCAL_AI_EXTENSION_VERSION,
  isCompatibleClipQuestExtensionVersion,
  supportsQuestionStream,
} from "./extension-compat";

const CHANNEL = "clipquest:captions:v1";
const WEBSITE_SOURCE = "clipquest-website";
const EXTENSION_SOURCE = "clipquest-extension";
const DETECTION_TIMEOUT_MS = 900;
const EXTRACTION_TIMEOUT_MS = 55_000;
// DeepSeek request construction can include bounded local evidence selection
// before fetch is dispatched. Keep this watchdog long enough for slower mobile
// browsers/extension service workers without changing the overall generation
// timeout or blocking quiz navigation.
// Dispatch should fail quickly enough to hand the accepted question prefix to
// the bounded recovery path. DeepSeek's stream itself has a separate idle
// watchdog; this timeout only covers the extension handoff before a call has
// started.
const LOCAL_GENERATION_DISPATCH_TIMEOUT_MS = 20_000;
// A lifecycle "started" event is emitted before DeepSeek begins streaming.
// Grounded evidence selection can be quiet for well over thirty seconds on a
// real mobile/network path, so do not abort a healthy call just because no
// question chunk has arrived yet. The engine still enforces its bounded
// request and recovery budgets.
const LOCAL_GENERATION_IDLE_TIMEOUT_MS = 180_000;

type ExtensionReadyMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "ready";
  version?: string;
  configured?: boolean;
  capabilities?: unknown;
};

type ExtensionExtractionResult = {
  videoId: string;
  durationSeconds: number;
  language: string;
  isAutoGenerated: boolean | null;
  sourceSegmentCount: number;
  segments: TranscriptSegment[];
  method:
    | "caption_track"
    | "youtube_player_capture"
    | "youtube_transcript_api"
    | "transcript_panel";
};

type ExtensionResultMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "result";
  requestId: string;
  response?: {
    ok?: boolean;
    result?: unknown;
    error?: string;
  };
};

type ExtensionSourceReadyResultMessage = Omit<
  ExtensionResultMessage,
  "type"
> & { type: "source-ready-result" };

type ExtensionGenerationProgressMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-progress";
  requestId: string;
  stage: GenerationStage;
  progress: number;
  attempt?: number;
  maxAttempts?: number;
  status?: "generating" | "retrying" | "complete";
  retryDelayMs?: number;
  retryOrdinal?: number;
  ordinalAttempt?: number;
  retryKind?: unknown;
  reasonCode?: unknown;
  recoverySessionId?: string;
};

export type LocalGenerationProgress = {
  attempt?: number;
  maxAttempts?: number;
  status?: "generating" | "retrying" | "complete";
  retryDelayMs?: number;
  retryOrdinal?: number;
  ordinalAttempt?: number;
  retryKind?: import("@clipquest/contracts").AutomaticRetryKind;
  reasonCode?: GenerationFailureCode;
  recoverySessionId?: string;
};

type ExtensionGenerationResultMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-result";
  requestId: string;
  response?: {
    ok?: boolean;
    result?: unknown;
    error?: string;
    reasonCode?: string;
  };
};

type ExtensionGenerationQuestionMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-question";
  requestId: string;
  result?: unknown;
};

type ExtensionGenerationCallMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-call";
  requestId: string;
  event?: unknown;
};

export type ClipQuestExtensionStatus =
  | { available: false }
  | {
      available: true;
      configured: boolean;
      version?: string;
      capabilities: string[];
    };

export class LocalGenerationRequestError extends Error {
  constructor(
    message: string,
    readonly reasonCode: GenerationFailureCode,
  ) {
    super(message);
  }
}

function canUseExtensionBridge(): boolean {
  return (
    Platform.OS === "web" &&
    typeof window !== "undefined" &&
    typeof window.postMessage === "function"
  );
}

function isReadyMessage(value: unknown): value is ExtensionReadyMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionReadyMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "ready"
  );
}

function isResultMessage(value: unknown): value is ExtensionResultMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionResultMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "result" &&
    typeof message.requestId === "string"
  );
}

function isSourceReadyResultMessage(
  value: unknown,
): value is ExtensionSourceReadyResultMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionSourceReadyResultMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "source-ready-result" &&
    typeof message.requestId === "string"
  );
}

function isGenerationProgressMessage(
  value: unknown,
): value is ExtensionGenerationProgressMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationProgressMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-progress" &&
    typeof message.requestId === "string" &&
    GenerationStageSchema.safeParse(message.stage).success &&
    typeof message.progress === "number" &&
    message.progress >= 0 &&
    message.progress <= 1 &&
    (message.attempt === undefined ||
      (Number.isInteger(message.attempt) &&
        message.attempt >= 1 &&
        message.attempt <= 12)) &&
    (message.maxAttempts === undefined ||
      (Number.isInteger(message.maxAttempts) &&
        message.maxAttempts >= 1 &&
        message.maxAttempts <= 24)) &&
    (message.status === undefined ||
      ["generating", "retrying", "complete"].includes(message.status)) &&
    (message.retryDelayMs === undefined ||
      (Number.isInteger(message.retryDelayMs) &&
        message.retryDelayMs >= 0 &&
        message.retryDelayMs <= 300_000)) &&
    (message.retryOrdinal === undefined ||
      (Number.isInteger(message.retryOrdinal) &&
        message.retryOrdinal >= 1 &&
        message.retryOrdinal <= 15)) &&
    (message.ordinalAttempt === undefined ||
      (Number.isInteger(message.ordinalAttempt) &&
        message.ordinalAttempt >= 1 &&
        message.ordinalAttempt <= 12)) &&
    (message.retryKind === undefined ||
      AutomaticRetryKindSchema.safeParse(message.retryKind).success) &&
    (message.reasonCode === undefined ||
      GenerationFailureCodeSchema.safeParse(message.reasonCode).success) &&
    (message.recoverySessionId === undefined ||
      /^[0-9a-f-]{36}$/i.test(message.recoverySessionId))
  );
}

function isGenerationResultMessage(
  value: unknown,
): value is ExtensionGenerationResultMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationResultMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-result" &&
    typeof message.requestId === "string"
  );
}

function isGenerationQuestionMessage(
  value: unknown,
): value is ExtensionGenerationQuestionMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationQuestionMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-question" &&
    typeof message.requestId === "string"
  );
}

function isGenerationCallMessage(
  value: unknown,
): value is ExtensionGenerationCallMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationCallMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-call" &&
    typeof message.requestId === "string"
  );
}

function post(message: Record<string, unknown>): void {
  window.postMessage(
    { channel: CHANNEL, source: WEBSITE_SOURCE, ...message },
    window.location.origin,
  );
}

export function subscribeToClipQuestExtension(
  listener: (status: {
    version?: string;
    configured: boolean;
    capabilities: string[];
  }) => void,
): () => void {
  if (!canUseExtensionBridge()) return () => undefined;
  const receive = (event: MessageEvent<unknown>) => {
    if (event.source !== window || event.origin !== window.location.origin)
      return;
    if (!isReadyMessage(event.data)) return;
    listener({
      configured: event.data.configured === true,
      capabilities: extensionCapabilities(event.data.capabilities),
      ...(typeof event.data.version === "string"
        ? { version: event.data.version }
        : {}),
    });
  };
  window.addEventListener("message", receive);
  return () => window.removeEventListener("message", receive);
}

export async function detectClipQuestExtension(
  timeoutMs = DETECTION_TIMEOUT_MS,
): Promise<ClipQuestExtensionStatus> {
  if (!canUseExtensionBridge()) return { available: false };
  return new Promise((resolve) => {
    let settled = false;
    const finish = (status: ClipQuestExtensionStatus) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      window.removeEventListener("message", receive);
      resolve(status);
    };
    const receive = (event: MessageEvent<unknown>) => {
      if (event.source !== window || event.origin !== window.location.origin)
        return;
      if (!isReadyMessage(event.data)) return;
      finish({
        available: true,
        configured: event.data.configured === true,
        capabilities: extensionCapabilities(event.data.capabilities),
        ...(typeof event.data.version === "string"
          ? { version: event.data.version }
          : {}),
      });
    };
    const timeout = setTimeout(() => finish({ available: false }), timeoutMs);
    window.addEventListener("message", receive);
    post({ type: "ping" });
  });
}

function extensionCapabilities(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter(
        (capability): capability is string => typeof capability === "string",
      )
    : [];
}

function parseExtractionResult(value: unknown): ExtensionExtractionResult {
  if (!value || typeof value !== "object") {
    throw new Error("The ClipQuest extension returned an invalid response.");
  }
  const result = value as Partial<ExtensionExtractionResult>;
  const invalidFields: string[] = [];
  if (typeof result.videoId !== "string") invalidFields.push("videoId");
  if (
    !Number.isInteger(result.durationSeconds) ||
    (result.durationSeconds ?? 0) < 1
  )
    invalidFields.push("durationSeconds");
  if (
    typeof result.language !== "string" ||
    result.language.length < 2 ||
    result.language.length > 35
  )
    invalidFields.push("language");
  if (
    !Number.isInteger(result.sourceSegmentCount) ||
    (result.sourceSegmentCount ?? 0) < 1
  )
    invalidFields.push("sourceSegmentCount");
  if (
    result.method !== "caption_track" &&
    result.method !== "youtube_player_capture" &&
    result.method !== "youtube_transcript_api" &&
    result.method !== "transcript_panel"
  )
    invalidFields.push("method");
  if (
    result.isAutoGenerated !== true &&
    result.isAutoGenerated !== false &&
    result.isAutoGenerated !== null
  )
    invalidFields.push("isAutoGenerated");
  if (
    !Array.isArray(result.segments) ||
    result.segments.length > MAX_COMPLETE_TRANSCRIPT_SEGMENTS
  )
    invalidFields.push("segments");
  if (invalidFields.length) {
    throw new Error(
      `The ClipQuest extension returned invalid fields: ${invalidFields.join(", ")}.`,
    );
  }
  return {
    videoId: result.videoId!,
    durationSeconds: result.durationSeconds as number,
    language: result.language!,
    isAutoGenerated: result.isAutoGenerated!,
    sourceSegmentCount: result.sourceSegmentCount as number,
    method: result.method!,
    segments: result.segments!.map((segment) =>
      TranscriptSegmentSchema.parse(segment),
    ),
  };
}

function requestId(): string {
  return (
    globalThis.crypto?.randomUUID?.() ??
    `cq-${Date.now()}-${Math.random().toString(36).slice(2)}`
  );
}

export async function requestExtensionYouTubeTranscript(
  videoId: string,
  preferredLanguage: string | null,
  signal: AbortSignal,
): Promise<ExtensionExtractionResult> {
  if (!/^[\w-]{11}$/.test(videoId)) {
    throw new Error("The YouTube video id is invalid.");
  }
  const extension = await detectClipQuestExtension();
  if (!extension.available) {
    throw new Error("ClipQuest Captions is not installed.");
  }
  const id = requestId();
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      signal.removeEventListener("abort", abort);
      window.removeEventListener("message", receive);
      callback();
    };
    const abort = () =>
      finish(() =>
        reject(
          signal.reason instanceof Error
            ? signal.reason
            : new DOMException("The request was cancelled.", "AbortError"),
        ),
      );
    const receive = (event: MessageEvent<unknown>) => {
      if (event.source !== window || event.origin !== window.location.origin)
        return;
      if (
        (!isResultMessage(event.data) &&
          !isSourceReadyResultMessage(event.data)) ||
        event.data.requestId !== id
      )
        return;
      const response = event.data.response;
      if (!response?.ok) {
        finish(() =>
          reject(
            new Error(
              typeof response?.error === "string"
                ? response.error
                : "The ClipQuest extension could not read captions.",
            ),
          ),
        );
        return;
      }
      finish(() => {
        try {
          const result = parseExtractionResult(response.result);
          if (result.videoId !== videoId) {
            throw new Error(
              "The extension transcript did not match the requested video.",
            );
          }
          resolve(result);
        } catch (error) {
          reject(error);
        }
      });
    };
    const timeout = setTimeout(
      () =>
        finish(() =>
          reject(new Error("The ClipQuest extension request timed out.")),
        ),
      EXTRACTION_TIMEOUT_MS,
    );
    window.addEventListener("message", receive);
    signal.addEventListener("abort", abort, { once: true });
    post({
      type: "ensure-source-ready",
      requestId: id,
      videoId,
      ...(preferredLanguage ? { preferredLanguage } : {}),
    });
  });
}

export const ensureExtensionSourceReady = requestExtensionYouTubeTranscript;

export function openClipQuestExtensionSettings(): void {
  if (!canUseExtensionBridge()) return;
  post({ type: "open-settings" });
}

export async function requestExtensionLocalQuiz(
  rawContext: LocalQuizContext,
  signal: AbortSignal,
  onProgress: (
    stage: GenerationStage,
    progress: number,
    detail: LocalGenerationProgress,
  ) => void,
  onQuestion: (chunk: LocalConceptQuizQuestionChunk) => void = () => undefined,
  onCall: (event: LocalGenerationCallEvent) => void = () => undefined,
): Promise<LocalConceptQuizGenerationResult> {
  const context = LocalQuizContextSchema.parse(rawContext);
  const minimumExtensionVersion =
    context.continuation?.resultProtocolVersion === 5
      ? MINIMUM_GROUNDED_LOCAL_AI_EXTENSION_VERSION
      : context.generationProfile === "prompt_first_auto_v5_12"
        ? MINIMUM_LOCAL_AI_EXTENSION_VERSION
        : context.generationProfile === "prompt_first_auto_v5_11"
          ? "0.8.16"
          : context.generationProfile === "prompt_first_auto_v5_10"
            ? "0.8.15"
            : context.generationProfile === "prompt_first_auto_v5_9"
              ? "0.8.14"
              : context.generationProfile === "concept_first_auto_v5_8"
                ? MINIMUM_CONCEPT_FIRST_LOCAL_AI_EXTENSION_VERSION
                : context.generationProfile === "evidence_grounded_auto_v5_4"
                  ? MINIMUM_GROUNDED_LOCAL_AI_EXTENSION_VERSION
                  : context.generationProfile === "stable_auto_recovery_v5_3"
                    ? MINIMUM_AUTOMATIC_LOCAL_AI_EXTENSION_VERSION
                    : context.generationProfile === "stable_non_thinking_v5_2"
                      ? MINIMUM_STABLE_LOCAL_AI_EXTENSION_VERSION
                      : MINIMUM_LEGACY_LOCAL_AI_EXTENSION_VERSION;
  const requiredCapability =
    context.generationProfile === "prompt_first_auto_v5_12" ||
    context.generationProfile === "prompt_first_auto_v5_11" ||
    context.generationProfile === "prompt_first_auto_v5_10" ||
    context.generationProfile === "prompt_first_auto_v5_9"
      ? LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY
      : context.generationProfile === "concept_first_auto_v5_8"
        ? CONCEPT_FIRST_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY
        : context.generationProfile === "evidence_grounded_auto_v5_4"
          ? GROUNDED_V5_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY
          : context.generationProfile === "stable_auto_recovery_v5_3"
            ? AUTOMATIC_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY
            : context.generationProfile === "stable_non_thinking_v5_2"
              ? STABLE_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY
              : LEGACY_LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY;
  const extension = await detectClipQuestExtension();
  if (!extension.available) {
    throw new Error("ClipQuest Local AI is not installed.");
  }
  if (
    !isCompatibleClipQuestExtensionVersion(
      extension.version,
      minimumExtensionVersion,
    )
  ) {
    throw new Error(
      `ClipQuest Local AI ${minimumExtensionVersion} or newer is required for streamed questions. Download and reload the current extension.`,
    );
  }
  if (!extension.capabilities.includes(requiredCapability)) {
    throw new Error(
      `Update ClipQuest Local AI. This extension does not support ${requiredCapability}.`,
    );
  }
  if (!extension.configured) {
    throw new Error(
      "Open ClipQuest Local AI from the Chrome toolbar and add your DeepSeek API key.",
    );
  }
  const id = requestId();
  return new Promise((resolve, reject) => {
    let settled = false;
    let timeout: ReturnType<typeof setTimeout>;
    let dispatchTimeout: ReturnType<typeof setTimeout> | undefined;
    let idleTimeout: ReturnType<typeof setTimeout> | undefined;
    const conceptFirst =
      context.generationProfile === "concept_first_auto_v5_8" ||
      context.generationProfile === "prompt_first_auto_v5_9" ||
      context.generationProfile === "prompt_first_auto_v5_10" ||
      context.generationProfile === "prompt_first_auto_v5_11" ||
      context.generationProfile === "prompt_first_auto_v5_12";
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      if (dispatchTimeout) clearTimeout(dispatchTimeout);
      if (idleTimeout) clearTimeout(idleTimeout);
      signal.removeEventListener("abort", abort);
      window.removeEventListener("message", receive);
      callback();
    };
    const abort = () =>
      finish(() =>
        reject(
          signal.reason instanceof Error
            ? signal.reason
            : new DOMException("The request was cancelled.", "AbortError"),
        ),
      );
    const resetIdleWatchdog = () => {
      if (!conceptFirst || settled) return;
      if (idleTimeout) clearTimeout(idleTimeout);
      idleTimeout = setTimeout(
        () =>
          finish(() =>
            reject(
              new LocalGenerationRequestError(
                "The extension stopped reporting generation activity.",
                "stream_idle_timeout",
              ),
            ),
          ),
        LOCAL_GENERATION_IDLE_TIMEOUT_MS,
      );
    };
    const receive = (event: MessageEvent<unknown>) => {
      if (event.source !== window || event.origin !== window.location.origin)
        return;
      if (
        isGenerationProgressMessage(event.data) &&
        event.data.requestId === id
      ) {
        resetIdleWatchdog();
        onProgress(event.data.stage, event.data.progress, {
          attempt: event.data.attempt,
          maxAttempts: event.data.maxAttempts,
          status: event.data.status,
          retryDelayMs: event.data.retryDelayMs,
          retryOrdinal: event.data.retryOrdinal,
          ordinalAttempt: event.data.ordinalAttempt,
          retryKind: AutomaticRetryKindSchema.safeParse(event.data.retryKind)
            .data,
          reasonCode: GenerationFailureCodeSchema.safeParse(
            event.data.reasonCode,
          ).data,
          recoverySessionId: event.data.recoverySessionId,
        });
        return;
      }
      if (
        isGenerationQuestionMessage(event.data) &&
        event.data.requestId === id
      ) {
        resetIdleWatchdog();
        const chunk = LocalConceptQuizQuestionChunkSchema.safeParse(
          event.data.result,
        );
        if (!chunk.success) {
          finish(() =>
            reject(new Error("The extension returned an invalid quiz chunk.")),
          );
          return;
        }
        onQuestion(chunk.data);
        return;
      }
      if (isGenerationCallMessage(event.data) && event.data.requestId === id) {
        resetIdleWatchdog();
        const call = LocalGenerationCallEventSchema.safeParse(event.data.event);
        if (!call.success) {
          finish(() =>
            reject(
              new Error(
                "The extension returned an invalid generation call event.",
              ),
            ),
          );
          return;
        }
        if (
          "lifecycleState" in call.data &&
          call.data.lifecycleState === "started" &&
          dispatchTimeout
        ) {
          clearTimeout(dispatchTimeout);
          dispatchTimeout = undefined;
        }
        onCall(call.data);
        return;
      }
      if (
        !isGenerationResultMessage(event.data) ||
        event.data.requestId !== id
      ) {
        return;
      }
      const response = event.data.response;
      resetIdleWatchdog();
      if (!response?.ok) {
        finish(() =>
          reject(
            new LocalGenerationRequestError(
              typeof response?.error === "string"
                ? response.error
                : "Local quiz generation failed.",
              GenerationFailureCodeSchema.safeParse(response?.reasonCode)
                .data ?? "local_state_conflict",
            ),
          ),
        );
        return;
      }
      finish(() => {
        try {
          resolve(parseLocalConceptQuizResult(response.result));
        } catch (error) {
          reject(error);
        }
      });
    };
    timeout = setTimeout(
      () =>
        finish(() =>
          reject(
            new Error(
              "Local generation exceeded its supervised recovery limit. DeepSeek was not allowed to continue silently.",
            ),
          ),
        ),
      conceptFirst ? 15 * 60 * 1_000 : 45 * 60 * 1_000,
    );
    if (conceptFirst) {
      dispatchTimeout = setTimeout(
        () =>
          finish(() =>
            reject(
              new LocalGenerationRequestError(
                "The extension did not dispatch the first generation call in time.",
                "call_dispatch_timeout",
              ),
            ),
          ),
        LOCAL_GENERATION_DISPATCH_TIMEOUT_MS,
      );
      resetIdleWatchdog();
    }
    window.addEventListener("message", receive);
    signal.addEventListener("abort", abort, { once: true });
    post({ type: "generate", requestId: id, context });
  });
}

export async function requestExtensionLocalCheatSheet(
  rawContext: import("@clipquest/contracts").CheatSheetContext,
  signal?: AbortSignal,
): Promise<import("@clipquest/contracts").CheatSheetDocument> {
  const context = CheatSheetContextSchema.parse(rawContext);
  const extension = await detectClipQuestExtension();
  if (!extension.available || !extension.configured)
    throw new Error(
      "Open ClipQuest Local AI from the Chrome toolbar and add your DeepSeek API key.",
    );
  const id = requestId();
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      signal?.removeEventListener("abort", abort);
      window.removeEventListener("message", receive);
      callback();
    };
    const abort = () =>
      finish(() =>
        reject(
          signal?.reason ??
            new DOMException("The request was cancelled.", "AbortError"),
        ),
      );
    const receive = (event: MessageEvent<unknown>) => {
      if (
        event.source !== window ||
        event.origin !== window.location.origin ||
        !isGenerationResultMessage(event.data) ||
        event.data.requestId !== id
      )
        return;
      const response = event.data.response;
      if (!response?.ok)
        return finish(() =>
          reject(
            new Error(response?.error ?? "Cheat-sheet generation failed."),
          ),
        );
      const parsed = CheatSheetDocumentSchema.safeParse({
        ...(response.result && typeof response.result === "object"
          ? response.result
          : {}),
        generatedAt: new Date().toISOString(),
        sourceRevision: context.sourceRevision,
      });
      if (!parsed.success)
        return finish(() =>
          reject(new Error("The extension returned an invalid cheat sheet.")),
        );
      finish(() => resolve(parsed.data));
    };
    const timeout = setTimeout(
      () =>
        finish(() =>
          reject(new Error("The ClipQuest extension request timed out.")),
        ),
      120_000,
    );
    window.addEventListener("message", receive);
    signal?.addEventListener("abort", abort, { once: true });
    post({ type: "generate", kind: "cheat-sheet", requestId: id, context });
  });
}

export async function requestExtensionLocalAnswerGrade(
  rawRequest: import("@clipquest/contracts").LocalAnswerGradeRequest,
  signal?: AbortSignal,
): Promise<import("@clipquest/contracts").LocalAnswerGrade> {
  const request = LocalAnswerGradeRequestSchema.parse(rawRequest);
  const extension = await detectClipQuestExtension();
  if (!extension.available || !extension.configured)
    throw new Error(
      "Open ClipQuest Local AI from the Chrome toolbar and add your DeepSeek API key.",
    );
  if (!extension.capabilities.includes("answer-grading-v1")) {
    throw new Error(
      "Update ClipQuest Local AI to enable softer answer grading.",
    );
  }
  const id = requestId();
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      signal?.removeEventListener("abort", abort);
      window.removeEventListener("message", receive);
      callback();
    };
    const abort = () =>
      finish(() =>
        reject(
          signal?.reason ??
            new DOMException("The request was cancelled.", "AbortError"),
        ),
      );
    const receive = (event: MessageEvent<unknown>) => {
      const data =
        event.data && typeof event.data === "object"
          ? (event.data as Record<string, unknown>)
          : null;
      if (
        event.source !== window ||
        event.origin !== window.location.origin ||
        data?.channel !== CHANNEL ||
        data?.source !== EXTENSION_SOURCE ||
        data?.type !== "answer-grade-result" ||
        data?.requestId !== id
      )
        return;
      const response = data.response as
        { ok?: boolean; error?: string; result?: unknown } | undefined;
      if (!response?.ok) {
        return finish(() =>
          reject(new Error(response?.error ?? "Answer grading failed.")),
        );
      }
      const parsed = LocalAnswerGradeSchema.safeParse(response.result);
      if (!parsed.success) {
        return finish(() =>
          reject(new Error("The extension returned an invalid answer grade.")),
        );
      }
      finish(() => resolve(parsed.data));
    };
    const timeout = setTimeout(
      () => finish(() => reject(new Error("Answer grading timed out."))),
      45_000,
    );
    window.addEventListener("message", receive);
    signal?.addEventListener("abort", abort, { once: true });
    post({ type: "grade-answer", requestId: id, request });
  });
}

function parseLocalConceptQuizResult(
  value: unknown,
): LocalConceptQuizGenerationResult {
  const parsed = LocalConceptQuizGenerationResultSchema.safeParse(value);
  if (!parsed.success) {
    throw new Error("The extension returned an invalid local quiz.");
  }
  return parsed.data;
}
