import {
  GenerationStageSchema,
  LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY,
  LocalConceptQuizGenerationResultSchema,
  LocalConceptQuizQuestionChunkSchema,
  LocalQuizContextSchema,
  MAX_COMPLETE_TRANSCRIPT_SEGMENTS,
  TranscriptSegmentSchema,
  type GenerationStage,
  type LocalConceptQuizQuestionChunk,
  type LocalConceptQuizGenerationResult,
  type LocalQuizContext,
  type TranscriptSegment,
} from "@clipquest/contracts";
import { Platform } from "react-native";

const CHANNEL = "clipquest:captions:v1";
const WEBSITE_SOURCE = "clipquest-website";
const EXTENSION_SOURCE = "clipquest-extension";
const DETECTION_TIMEOUT_MS = 900;
const EXTRACTION_TIMEOUT_MS = 55_000;
export const MINIMUM_LOCAL_AI_EXTENSION_VERSION = "0.8.0";

type ExtensionReadyMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "ready";
  version?: string;
  configured?: boolean;
  capabilities?: unknown;
};

type ExtensionExtractionResult = {
  videoId: string;
  durationSeconds: number;
  language: string;
  isAutoGenerated: boolean | null;
  sourceSegmentCount: number;
  segments: TranscriptSegment[];
  method:
    | "caption_track"
    | "youtube_player_capture"
    | "youtube_transcript_api"
    | "transcript_panel";
};

type ExtensionResultMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "result";
  requestId: string;
  response?: {
    ok?: boolean;
    result?: unknown;
    error?: string;
  };
};

type ExtensionGenerationProgressMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-progress";
  requestId: string;
  stage: GenerationStage;
  progress: number;
  attempt?: number;
  maxAttempts?: number;
  status?: "generating" | "retrying" | "complete";
};

export type LocalGenerationProgress = {
  attempt?: number;
  maxAttempts?: number;
  status?: "generating" | "retrying" | "complete";
};

type ExtensionGenerationResultMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-result";
  requestId: string;
  response?: {
    ok?: boolean;
    result?: unknown;
    error?: string;
    reasonCode?: string;
  };
};

type ExtensionGenerationQuestionMessage = {
  channel: typeof CHANNEL;
  source: typeof EXTENSION_SOURCE;
  type: "generation-question";
  requestId: string;
  result?: unknown;
};

export type ClipQuestExtensionStatus =
  | { available: false }
  | {
      available: true;
      configured: boolean;
      version?: string;
      capabilities: string[];
    };

export class LocalGenerationRequestError extends Error {
  constructor(
    message: string,
    readonly reasonCode: string,
  ) {
    super(message);
  }
}

export function isCompatibleClipQuestExtensionVersion(
  version: string | undefined,
): boolean {
  if (!version) return false;
  const actual = version.split(".").map((part) => Number(part));
  const required = MINIMUM_LOCAL_AI_EXTENSION_VERSION.split(".").map((part) =>
    Number(part),
  );
  if (
    actual.length < 3 ||
    actual.some((part) => !Number.isInteger(part) || part < 0)
  ) {
    return false;
  }
  for (let index = 0; index < required.length; index += 1) {
    const requiredPart = required[index] ?? 0;
    if ((actual[index] ?? 0) > requiredPart) return true;
    if ((actual[index] ?? 0) < requiredPart) return false;
  }
  return true;
}

export function supportsQuestionStream(
  capabilities: readonly string[],
): boolean {
  return capabilities.includes(LOCAL_QUIZ_QUESTION_STREAM_CAPABILITY);
}

function canUseExtensionBridge(): boolean {
  return (
    Platform.OS === "web" &&
    typeof window !== "undefined" &&
    typeof window.postMessage === "function"
  );
}

function isReadyMessage(value: unknown): value is ExtensionReadyMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionReadyMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "ready"
  );
}

function isResultMessage(value: unknown): value is ExtensionResultMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionResultMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "result" &&
    typeof message.requestId === "string"
  );
}

function isGenerationProgressMessage(
  value: unknown,
): value is ExtensionGenerationProgressMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationProgressMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-progress" &&
    typeof message.requestId === "string" &&
    GenerationStageSchema.safeParse(message.stage).success &&
    typeof message.progress === "number" &&
    message.progress >= 0 &&
    message.progress <= 1 &&
    (message.attempt === undefined ||
      (Number.isInteger(message.attempt) && message.attempt >= 1)) &&
    (message.maxAttempts === undefined ||
      (Number.isInteger(message.maxAttempts) && message.maxAttempts >= 1)) &&
    (message.status === undefined ||
      ["generating", "retrying", "complete"].includes(message.status))
  );
}

function isGenerationResultMessage(
  value: unknown,
): value is ExtensionGenerationResultMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationResultMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-result" &&
    typeof message.requestId === "string"
  );
}

function isGenerationQuestionMessage(
  value: unknown,
): value is ExtensionGenerationQuestionMessage {
  if (!value || typeof value !== "object") return false;
  const message = value as Partial<ExtensionGenerationQuestionMessage>;
  return (
    message.channel === CHANNEL &&
    message.source === EXTENSION_SOURCE &&
    message.type === "generation-question" &&
    typeof message.requestId === "string"
  );
}

function post(message: Record<string, unknown>): void {
  window.postMessage(
    { channel: CHANNEL, source: WEBSITE_SOURCE, ...message },
    window.location.origin,
  );
}

export function subscribeToClipQuestExtension(
  listener: (status: {
    version?: string;
    configured: boolean;
    capabilities: string[];
  }) => void,
): () => void {
  if (!canUseExtensionBridge()) return () => undefined;
  const receive = (event: MessageEvent<unknown>) => {
    if (event.source !== window || event.origin !== window.location.origin)
      return;
    if (!isReadyMessage(event.data)) return;
    listener({
      configured: event.data.configured === true,
      capabilities: extensionCapabilities(event.data.capabilities),
      ...(typeof event.data.version === "string"
        ? { version: event.data.version }
        : {}),
    });
  };
  window.addEventListener("message", receive);
  return () => window.removeEventListener("message", receive);
}

export async function detectClipQuestExtension(
  timeoutMs = DETECTION_TIMEOUT_MS,
): Promise<ClipQuestExtensionStatus> {
  if (!canUseExtensionBridge()) return { available: false };
  return new Promise((resolve) => {
    let settled = false;
    const finish = (status: ClipQuestExtensionStatus) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      window.removeEventListener("message", receive);
      resolve(status);
    };
    const receive = (event: MessageEvent<unknown>) => {
      if (event.source !== window || event.origin !== window.location.origin)
        return;
      if (!isReadyMessage(event.data)) return;
      finish({
        available: true,
        configured: event.data.configured === true,
        capabilities: extensionCapabilities(event.data.capabilities),
        ...(typeof event.data.version === "string"
          ? { version: event.data.version }
          : {}),
      });
    };
    const timeout = setTimeout(() => finish({ available: false }), timeoutMs);
    window.addEventListener("message", receive);
    post({ type: "ping" });
  });
}

function extensionCapabilities(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter(
        (capability): capability is string => typeof capability === "string",
      )
    : [];
}

function parseExtractionResult(value: unknown): ExtensionExtractionResult {
  if (!value || typeof value !== "object") {
    throw new Error("The ClipQuest extension returned an invalid response.");
  }
  const result = value as Partial<ExtensionExtractionResult>;
  const invalidFields: string[] = [];
  if (typeof result.videoId !== "string") invalidFields.push("videoId");
  if (
    !Number.isInteger(result.durationSeconds) ||
    (result.durationSeconds ?? 0) < 1
  )
    invalidFields.push("durationSeconds");
  if (
    typeof result.language !== "string" ||
    result.language.length < 2 ||
    result.language.length > 35
  )
    invalidFields.push("language");
  if (
    !Number.isInteger(result.sourceSegmentCount) ||
    (result.sourceSegmentCount ?? 0) < 1
  )
    invalidFields.push("sourceSegmentCount");
  if (
    result.method !== "caption_track" &&
    result.method !== "youtube_player_capture" &&
    result.method !== "youtube_transcript_api" &&
    result.method !== "transcript_panel"
  )
    invalidFields.push("method");
  if (
    result.isAutoGenerated !== true &&
    result.isAutoGenerated !== false &&
    result.isAutoGenerated !== null
  )
    invalidFields.push("isAutoGenerated");
  if (
    !Array.isArray(result.segments) ||
    result.segments.length > MAX_COMPLETE_TRANSCRIPT_SEGMENTS
  )
    invalidFields.push("segments");
  if (invalidFields.length) {
    throw new Error(
      `The ClipQuest extension returned invalid fields: ${invalidFields.join(", ")}.`,
    );
  }
  return {
    videoId: result.videoId!,
    durationSeconds: result.durationSeconds as number,
    language: result.language!,
    isAutoGenerated: result.isAutoGenerated!,
    sourceSegmentCount: result.sourceSegmentCount as number,
    method: result.method!,
    segments: result.segments!.map((segment) =>
      TranscriptSegmentSchema.parse(segment),
    ),
  };
}

function requestId(): string {
  return (
    globalThis.crypto?.randomUUID?.() ??
    `cq-${Date.now()}-${Math.random().toString(36).slice(2)}`
  );
}

export async function requestExtensionYouTubeTranscript(
  videoId: string,
  preferredLanguage: string | null,
  signal: AbortSignal,
): Promise<ExtensionExtractionResult> {
  if (!/^[\w-]{11}$/.test(videoId)) {
    throw new Error("The YouTube video id is invalid.");
  }
  const extension = await detectClipQuestExtension();
  if (!extension.available) {
    throw new Error("ClipQuest Captions is not installed.");
  }
  const id = requestId();
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      signal.removeEventListener("abort", abort);
      window.removeEventListener("message", receive);
      callback();
    };
    const abort = () =>
      finish(() =>
        reject(
          signal.reason instanceof Error
            ? signal.reason
            : new DOMException("The request was cancelled.", "AbortError"),
        ),
      );
    const receive = (event: MessageEvent<unknown>) => {
      if (event.source !== window || event.origin !== window.location.origin)
        return;
      if (!isResultMessage(event.data) || event.data.requestId !== id) return;
      const response = event.data.response;
      if (!response?.ok) {
        finish(() =>
          reject(
            new Error(
              typeof response?.error === "string"
                ? response.error
                : "The ClipQuest extension could not read captions.",
            ),
          ),
        );
        return;
      }
      finish(() => {
        try {
          const result = parseExtractionResult(response.result);
          if (result.videoId !== videoId) {
            throw new Error(
              "The extension transcript did not match the requested video.",
            );
          }
          resolve(result);
        } catch (error) {
          reject(error);
        }
      });
    };
    const timeout = setTimeout(
      () =>
        finish(() =>
          reject(new Error("The ClipQuest extension request timed out.")),
        ),
      EXTRACTION_TIMEOUT_MS,
    );
    window.addEventListener("message", receive);
    signal.addEventListener("abort", abort, { once: true });
    post({
      type: "extract",
      requestId: id,
      videoId,
      ...(preferredLanguage ? { preferredLanguage } : {}),
    });
  });
}

export async function requestExtensionLocalQuiz(
  rawContext: LocalQuizContext,
  signal: AbortSignal,
  onProgress: (
    stage: GenerationStage,
    progress: number,
    detail: LocalGenerationProgress,
  ) => void,
  onQuestion: (chunk: LocalConceptQuizQuestionChunk) => void = () => undefined,
): Promise<LocalConceptQuizGenerationResult> {
  const context = LocalQuizContextSchema.parse(rawContext);
  const extension = await detectClipQuestExtension();
  if (!extension.available) {
    throw new Error("ClipQuest Local AI is not installed.");
  }
  if (!isCompatibleClipQuestExtensionVersion(extension.version)) {
    throw new Error(
      `ClipQuest Local AI ${MINIMUM_LOCAL_AI_EXTENSION_VERSION} or newer is required for streamed questions. Download and reload the current extension.`,
    );
  }
  if (!supportsQuestionStream(extension.capabilities)) {
    throw new Error(
      "Update ClipQuest Local AI. This extension does not support question-stream-v1.",
    );
  }
  if (!extension.configured) {
    throw new Error(
      "Open ClipQuest Local AI from the Chrome toolbar and add your DeepSeek API key.",
    );
  }
  const id = requestId();
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      signal.removeEventListener("abort", abort);
      window.removeEventListener("message", receive);
      callback();
    };
    const abort = () =>
      finish(() =>
        reject(
          signal.reason instanceof Error
            ? signal.reason
            : new DOMException("The request was cancelled.", "AbortError"),
        ),
      );
    const receive = (event: MessageEvent<unknown>) => {
      if (event.source !== window || event.origin !== window.location.origin)
        return;
      if (
        isGenerationProgressMessage(event.data) &&
        event.data.requestId === id
      ) {
        onProgress(event.data.stage, event.data.progress, {
          attempt: event.data.attempt,
          maxAttempts: event.data.maxAttempts,
          status: event.data.status,
        });
        return;
      }
      if (
        isGenerationQuestionMessage(event.data) &&
        event.data.requestId === id
      ) {
        const chunk = LocalConceptQuizQuestionChunkSchema.safeParse(
          event.data.result,
        );
        if (!chunk.success) {
          finish(() =>
            reject(new Error("The extension returned an invalid quiz chunk.")),
          );
          return;
        }
        onQuestion(chunk.data);
        return;
      }
      if (
        !isGenerationResultMessage(event.data) ||
        event.data.requestId !== id
      ) {
        return;
      }
      const response = event.data.response;
      if (!response?.ok) {
        finish(() =>
          reject(
            new LocalGenerationRequestError(
              typeof response?.error === "string"
                ? response.error
                : "Local quiz generation failed.",
              typeof response?.reasonCode === "string"
                ? response.reasonCode
                : "automatic_retries_exhausted",
            ),
          ),
        );
        return;
      }
      finish(() => {
        try {
          resolve(parseLocalConceptQuizResult(response.result));
        } catch (error) {
          reject(error);
        }
      });
    };
    const timeout = setTimeout(
      () =>
        finish(() =>
          reject(
            new Error(
              "Local generation exceeded 45 minutes. DeepSeek was not allowed to continue silently.",
            ),
          ),
        ),
      45 * 60 * 1_000,
    );
    window.addEventListener("message", receive);
    signal.addEventListener("abort", abort, { once: true });
    post({ type: "generate", requestId: id, context });
  });
}

function parseLocalConceptQuizResult(
  value: unknown,
): LocalConceptQuizGenerationResult {
  const parsed = LocalConceptQuizGenerationResultSchema.safeParse(value);
  if (!parsed.success) {
    throw new Error("The extension returned an invalid local quiz.");
  }
  return parsed.data;
}
