import {
  compactTranscriptSegments,
  type TranscriptSegment,
} from "@clipquest/contracts";

const MAX_CAPTION_BYTES = 8 * 1024 * 1024;
const YOUTUBE_WATCH_ORIGIN = "https://www.youtube.com";
const YOUTUBE_DIRECT_ATTEMPTS = 2;
const YOUTUBE_WATCH_TIMEOUT_MS = 10_000;
const YOUTUBE_PLAYER_CLIENT_NAME = "28";
const YOUTUBE_PLAYER_CLIENT_VERSION = "1.65.10";
const YOUTUBE_PLAYER_USER_AGENT =
  "com.google.android.apps.youtube.vr.oculus/1.65.10 (Linux; U; Android 12L; eureka-user Build/SQ3A.220605.009.A1) gzip";
const YOUTUBE_PLAYER_CLIENT = {
  clientName: "ANDROID_VR",
  clientVersion: YOUTUBE_PLAYER_CLIENT_VERSION,
  deviceMake: "Oculus",
  deviceModel: "Quest 3",
  androidSdkVersion: 32,
  userAgent: YOUTUBE_PLAYER_USER_AGENT,
  osName: "Android",
  osVersion: "12L",
};
const TRANSCRIPT_PROVIDER_ORIGIN = "https://youtube-transcript.ai";
const TRANSCRIPT_PROVIDER_ATTEMPTS = 2;
const TRANSCRIPT_PROVIDER_TIMEOUT_MS = 4_000;

type TimedTextPayload = {
  events?: {
    tStartMs?: number;
    dDurationMs?: number;
    segs?: { utf8?: string }[];
  }[];
};

type CompleteCaptionDocument = {
  segments: TranscriptSegment[];
  sourceSegmentCount: number;
};

function splitCaptionText(text: string): string[] {
  const normalized = text.replaceAll("\n", " ").replace(/\s+/g, " ").trim();
  if (!normalized) return [];
  if (normalized.length <= 2_000) return [normalized];
  const pieces: string[] = [];
  let remaining = normalized;
  while (remaining.length > 2_000) {
    const splitAt = remaining.lastIndexOf(" ", 1_900);
    if (splitAt < 1) {
      throw new Error(
        "A YouTube caption event is too large to preserve safely.",
      );
    }
    pieces.push(remaining.slice(0, splitAt));
    remaining = remaining.slice(splitAt + 1);
  }
  if (remaining) pieces.push(remaining);
  return pieces;
}

export function parseYouTubeTimedTextDocument(
  payload: TimedTextPayload,
): CompleteCaptionDocument {
  const rawSegments = (payload.events ?? []).flatMap((event, eventIndex) => {
    const startMs = Math.max(0, Math.floor(event.tStartMs ?? 0));
    const endMs = startMs + Math.max(1, Math.floor(event.dDurationMs ?? 3_000));
    const text = (event.segs ?? [])
      .map((segment) => segment.utf8 ?? "")
      .join("");
    const pieces = splitCaptionText(text);
    return pieces.map((piece, pieceIndex) => ({
      id:
        pieces.length === 1
          ? `youtube-${eventIndex}-${startMs}`
          : `youtube-${eventIndex}-${pieceIndex}-${startMs}`,
      startMs: startMs + pieceIndex,
      endMs: Math.max(startMs + pieceIndex + 1, endMs),
      text: piece,
    }));
  });
  const segments = compactTranscriptSegments(rawSegments);
  const characters = segments.reduce(
    (total, segment) => total + segment.text.length,
    0,
  );
  return {
    segments: characters >= 20 ? segments : [],
    sourceSegmentCount: rawSegments.length,
  };
}

export function parseYouTubeTimedText(
  payload: TimedTextPayload,
): TranscriptSegment[] {
  return parseYouTubeTimedTextDocument(payload).segments;
}

type BrowserTranscript = {
  language: string;
  durationSeconds: number | null;
  segments: TranscriptSegment[];
  sourceSegmentCount: number;
};

export type DirectYouTubeTranscript = BrowserTranscript & {
  isAutoGenerated: boolean;
};

type YouTubeCaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
};

type YouTubePlayerResponse = {
  videoDetails?: {
    videoId?: string;
    lengthSeconds?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YouTubeCaptionTrack[];
    };
  };
};

export type YouTubeWatchCaptionSource = {
  captionUrl: string;
  language: string;
  durationSeconds: number | null;
  isAutoGenerated: boolean;
};

function playerResponseObjects(body: string): YouTubePlayerResponse[] {
  const marker = "ytInitialPlayerResponse";
  const responses: YouTubePlayerResponse[] = [];
  let searchFrom = 0;
  while (searchFrom < body.length) {
    const markerIndex = body.indexOf(marker, searchFrom);
    if (markerIndex < 0) break;
    searchFrom = markerIndex + marker.length;
    const start = body.indexOf("{", searchFrom);
    if (start < 0 || start - searchFrom > 80) continue;
    let depth = 0;
    let inString = false;
    let escaped = false;
    for (let index = start; index < body.length; index += 1) {
      const character = body[index];
      if (inString) {
        if (escaped) escaped = false;
        else if (character === "\\") escaped = true;
        else if (character === '"') inString = false;
        continue;
      }
      if (character === '"') {
        inString = true;
        continue;
      }
      if (character === "{") depth += 1;
      else if (character === "}") depth -= 1;
      if (depth !== 0) continue;
      try {
        responses.push(
          JSON.parse(body.slice(start, index + 1)) as YouTubePlayerResponse,
        );
      } catch {
        // A later assignment can still contain the authoritative player
        // response. Keep scanning instead of accepting partial page data.
      }
      searchFrom = index + 1;
      break;
    }
  }
  return responses;
}

function languageScore(language: string, preferredLanguage: string): number {
  const normalized = normalizeTranscriptLanguage(language);
  const preferred = normalizeTranscriptLanguage(preferredLanguage);
  if (normalized === preferred) return 0;
  if (
    normalized.split("-")[0] &&
    normalized.split("-")[0] === preferred.split("-")[0]
  )
    return 1;
  return 3;
}

export function parseYouTubePlayerCaptionSource(
  player: YouTubePlayerResponse,
  expectedVideoId: string,
  preferredLanguage = "en",
): YouTubeWatchCaptionSource {
  if (player.videoDetails?.videoId !== expectedVideoId) {
    throw new Error("YouTube did not return the requested video metadata.");
  }
  const tracks =
    player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const track = [...tracks]
    .filter(
      (
        candidate,
      ): candidate is Required<
        Pick<YouTubeCaptionTrack, "baseUrl" | "languageCode">
      > &
        YouTubeCaptionTrack =>
        typeof candidate.baseUrl === "string" &&
        typeof candidate.languageCode === "string",
    )
    .sort((left, right) => {
      const languageDifference =
        languageScore(left.languageCode, preferredLanguage) -
        languageScore(right.languageCode, preferredLanguage);
      if (languageDifference !== 0) return languageDifference;
      return Number(left.kind === "asr") - Number(right.kind === "asr");
    })[0];
  if (!track) throw new Error("YouTube did not expose a caption track.");
  const captionUrl = new URL(track.baseUrl);
  if (
    captionUrl.protocol !== "https:" ||
    (captionUrl.hostname !== "youtube.com" &&
      !captionUrl.hostname.endsWith(".youtube.com"))
  ) {
    throw new Error("YouTube returned an invalid caption source.");
  }
  captionUrl.searchParams.set("fmt", "json3");
  const durationSeconds = Number(player.videoDetails?.lengthSeconds);
  return {
    captionUrl: captionUrl.href,
    language: normalizeTranscriptLanguage(track.languageCode),
    durationSeconds:
      Number.isFinite(durationSeconds) && durationSeconds > 0
        ? durationSeconds
        : null,
    isAutoGenerated: track.kind === "asr",
  };
}

export function parseYouTubeWatchCaptionSource(
  body: string,
  expectedVideoId: string,
  preferredLanguage = "en",
): YouTubeWatchCaptionSource {
  if (!/^[\w-]{11}$/.test(expectedVideoId)) {
    throw new Error("The YouTube video id is invalid.");
  }
  const player = playerResponseObjects(body).find(
    (candidate) => candidate.videoDetails?.videoId === expectedVideoId,
  );
  if (!player) {
    throw new Error("YouTube did not return the requested video metadata.");
  }
  return parseYouTubePlayerCaptionSource(
    player,
    expectedVideoId,
    preferredLanguage,
  );
}

function extractYouTubeWatchConfig(body: string, property: string): string {
  const escapedProperty = property.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = body.match(
    new RegExp(`"${escapedProperty}":("(?:\\\\.|[^"\\\\])*")`),
  );
  if (!match?.[1]) {
    throw new Error("YouTube caption discovery returned incomplete metadata.");
  }
  const value = JSON.parse(match[1]) as unknown;
  if (typeof value !== "string" || !value.trim()) {
    throw new Error("YouTube caption discovery returned incomplete metadata.");
  }
  return value;
}

/**
 * Caption providers sometimes return a human language name (for example
 * "English") even though the API contract stores a BCP-47-style code. Keep
 * that provider detail from leaking into source-metadata validation or the
 * local generation context.
 */
export function normalizeTranscriptLanguage(
  language: string | null | undefined,
): string {
  const value = String(language ?? "").trim();
  if (!value) return "und";
  const normalized = value.toLocaleLowerCase("en-US");
  const aliases: Record<string, string> = {
    english: "en",
    "american english": "en-US",
    "british english": "en-GB",
    chinese: "zh",
    mandarin: "zh",
    "simplified chinese": "zh-CN",
    "traditional chinese": "zh-TW",
    spanish: "es",
    french: "fr",
    german: "de",
    italian: "it",
    japanese: "ja",
    korean: "ko",
    portuguese: "pt",
    russian: "ru",
    arabic: "ar",
    hindi: "hi",
  };
  const alias = aliases[normalized];
  if (alias) return alias;
  return /^[a-z]{2,3}(?:-[a-z0-9]{2,8})*$/iu.test(value) ? value : "und";
}

function timestampMs(first: string, second: string, third?: string): number {
  const hours = third === undefined ? 0 : Number(first);
  const minutes = Number(third === undefined ? first : second);
  const seconds = Number(third === undefined ? second : third);
  return (hours * 3_600 + minutes * 60 + seconds) * 1_000;
}

function comparableWord(word: string): string {
  return word
    .toLocaleLowerCase()
    .replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
}

export function collapseAdjacentCaptionRepeats(text: string): string {
  const words = text.replace(/\s+/g, " ").trim().split(" ").filter(Boolean);
  const output: string[] = [];
  let index = 0;
  while (index < words.length) {
    const remaining = words.length - index;
    let repeatedSpan = 0;
    let repeatedCopies = 0;
    const maximumSpan = Math.min(48, Math.floor(remaining / 2));
    for (let span = maximumSpan; span >= 1; span -= 1) {
      let matches = true;
      for (let offset = 0; offset < span; offset += 1) {
        if (
          comparableWord(words[index + offset] ?? "") !==
          comparableWord(words[index + span + offset] ?? "")
        ) {
          matches = false;
          break;
        }
      }
      if (!matches) continue;
      let copies = 2;
      while (index + (copies + 1) * span <= words.length) {
        let nextMatches = true;
        for (let offset = 0; offset < span; offset += 1) {
          if (
            comparableWord(words[index + offset] ?? "") !==
            comparableWord(words[index + copies * span + offset] ?? "")
          ) {
            nextMatches = false;
            break;
          }
        }
        if (!nextMatches) break;
        copies += 1;
      }
      if (span > 1 || copies >= 3) {
        repeatedSpan = span;
        repeatedCopies = copies;
        break;
      }
    }
    if (!repeatedSpan) {
      output.push(words[index] ?? "");
      index += 1;
      continue;
    }
    output.push(...words.slice(index, index + repeatedSpan));
    index += repeatedSpan * repeatedCopies;
  }
  return output.join(" ").trim();
}

export function parseBrowserTranscript(
  body: string,
  expectedVideoId: string,
): BrowserTranscript {
  if (!/^[\w-]{11}$/.test(expectedVideoId)) {
    throw new Error("The YouTube video id is invalid.");
  }
  const sourceLine = body.match(/^Source video:\s+(https?:\/\/\S+)\s*$/m);
  if (!sourceLine?.[1]) {
    throw new Error("The transcript source could not be verified.");
  }
  const sourceUrl = new URL(sourceLine[1]);
  const actualVideoId =
    sourceUrl.hostname === "youtu.be"
      ? sourceUrl.pathname.slice(1)
      : sourceUrl.searchParams.get("v");
  if (actualVideoId !== expectedVideoId) {
    throw new Error("The transcript source did not match the requested video.");
  }
  const language = normalizeTranscriptLanguage(
    body.match(/^Language:\s*([^\s·|]+)/m)?.[1] ?? "und",
  );
  const durationMatch = body.match(
    /(?:^|[·|])\s*Duration:\s*(\d{1,3}):([0-5]\d)(?::([0-5]\d))?/m,
  );
  const durationSeconds = durationMatch?.[1]
    ? timestampMs(
        durationMatch[1],
        durationMatch[2] ?? "00",
        durationMatch[3],
      ) / 1_000
    : null;
  const parsed = body.split(/\r?\n/).flatMap((line) => {
    const match = line.match(/^\[(\d{1,3}):([0-5]\d)(?::([0-5]\d))?\]\s+(.+)$/);
    if (!match?.[1] || !match[2] || !match[4]) return [];
    const text = collapseAdjacentCaptionRepeats(match[4]);
    if (!text) return [];
    return [{ startMs: timestampMs(match[1], match[2], match[3]), text }];
  });
  const rawSegments = parsed.flatMap((segment, index) => {
    const nextStartMs = parsed[index + 1]?.startMs;
    const endMs = Math.max(
      segment.startMs + 1,
      nextStartMs ?? segment.startMs + 30_000,
    );
    const pieces = splitCaptionText(segment.text);
    return pieces.map((piece, pieceIndex) => ({
      id:
        pieces.length === 1
          ? `youtube-text-${index}-${segment.startMs}`
          : `youtube-text-${index}-${pieceIndex}-${segment.startMs}`,
      startMs: segment.startMs + pieceIndex,
      endMs: Math.max(segment.startMs + pieceIndex + 1, endMs),
      text: piece,
    }));
  });
  const segments = compactTranscriptSegments(rawSegments);
  const characters = segments.reduce(
    (total, segment) => total + segment.text.length,
    0,
  );
  if (segments.length === 0 || characters < 20) {
    throw new Error("The transcript provider returned empty captions.");
  }
  return {
    language,
    durationSeconds,
    segments,
    sourceSegmentCount: rawSegments.length,
  };
}

async function fetchBoundedCaptionText(
  url: string,
  signal: AbortSignal,
  options: {
    accept: string;
    timeoutMs: number;
    timeoutMessage: string;
    validateResponse(response: Response): void;
    request?: {
      method?: string;
      body?: string;
      headers?: Record<string, string>;
    };
  },
): Promise<string> {
  const controller = new AbortController();
  const abort = () =>
    controller.abort(
      signal.reason ?? new DOMException("Aborted", "AbortError"),
    );
  if (signal.aborted) abort();
  else signal.addEventListener("abort", abort, { once: true });
  const timeout = setTimeout(
    () => controller.abort(new Error(options.timeoutMessage)),
    options.timeoutMs,
  );
  try {
    const response = await fetch(url, {
      method: options.request?.method,
      body: options.request?.body,
      signal: controller.signal,
      cache: "no-store",
      credentials: "omit",
      headers: { ...options.request?.headers, Accept: options.accept },
    });
    try {
      options.validateResponse(response);
    } catch (error) {
      await response.body?.cancel().catch(() => undefined);
      throw error;
    }
    return await readBoundedCaptionResponseText(response);
  } finally {
    clearTimeout(timeout);
    signal.removeEventListener("abort", abort);
  }
}

export async function readBoundedCaptionResponseText(
  response: Response,
  maximumBytes = MAX_CAPTION_BYTES,
): Promise<string> {
  const declaredLength = Number(response.headers.get("content-length") ?? 0);
  if (declaredLength > maximumBytes) {
    await response.body?.cancel().catch(() => undefined);
    throw new Error("YouTube captions exceeded the safe size limit.");
  }
  if (!response.body) return "";

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let receivedBytes = 0;
  let body = "";
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      receivedBytes += value.byteLength;
      if (receivedBytes > maximumBytes) {
        await reader.cancel().catch(() => undefined);
        throw new Error("YouTube captions exceeded the safe size limit.");
      }
      body += decoder.decode(value, { stream: true });
    }
    return body + decoder.decode();
  } finally {
    reader.releaseLock();
  }
}

export async function downloadBrowserYouTubeTranscript(
  videoId: string,
  signal: AbortSignal,
): Promise<BrowserTranscript> {
  if (!/^[\w-]{11}$/.test(videoId)) {
    throw new Error("The YouTube video id is invalid.");
  }
  let lastError: unknown;
  for (let attempt = 1; attempt <= TRANSCRIPT_PROVIDER_ATTEMPTS; attempt += 1) {
    try {
      const body = await fetchBoundedCaptionText(
        `${TRANSCRIPT_PROVIDER_ORIGIN}/transcript/${encodeURIComponent(videoId)}.txt`,
        signal,
        {
          accept: "text/markdown, text/plain;q=0.9",
          timeoutMs: TRANSCRIPT_PROVIDER_TIMEOUT_MS,
          timeoutMessage: "Transcript lookup timed out.",
          validateResponse(response) {
            if (!response.ok) {
              throw new Error(
                `Browser transcript lookup failed (${response.status}).`,
              );
            }
            const contentType = response.headers
              .get("content-type")
              ?.toLowerCase();
            if (
              contentType &&
              !contentType.startsWith("text/plain") &&
              !contentType.startsWith("text/markdown")
            ) {
              throw new Error(
                "The transcript provider returned an unsafe content type.",
              );
            }
          },
        },
      );
      return parseBrowserTranscript(body, videoId);
    } catch (error) {
      if (signal.aborted) throw error;
      lastError = error;
      if (attempt < TRANSCRIPT_PROVIDER_ATTEMPTS) {
        await new Promise((resolve) => setTimeout(resolve, 250));
      }
    }
  }
  throw lastError instanceof Error
    ? lastError
    : new Error("Browser transcript lookup failed.");
}

export async function downloadDirectYouTubeTranscript(
  videoId: string,
  signal: AbortSignal,
  preferredLanguage = "en",
): Promise<DirectYouTubeTranscript> {
  if (!/^[\w-]{11}$/.test(videoId)) {
    throw new Error("The YouTube video id is invalid.");
  }
  let lastError: unknown;
  for (let attempt = 1; attempt <= YOUTUBE_DIRECT_ATTEMPTS; attempt += 1) {
    try {
      const watchUrl = new URL("/watch", YOUTUBE_WATCH_ORIGIN);
      watchUrl.searchParams.set("v", videoId);
      watchUrl.searchParams.set(
        "hl",
        normalizeTranscriptLanguage(preferredLanguage),
      );
      watchUrl.searchParams.set("has_verified", "1");
      const body = await fetchBoundedCaptionText(watchUrl.href, signal, {
        accept: "text/html,application/xhtml+xml",
        timeoutMs: YOUTUBE_WATCH_TIMEOUT_MS,
        timeoutMessage: "YouTube caption discovery timed out.",
        validateResponse(response) {
          if (!response.ok) {
            throw new Error(
              `YouTube caption discovery failed (${response.status}).`,
            );
          }
          const contentType = response.headers
            .get("content-type")
            ?.toLowerCase();
          if (contentType && !contentType.startsWith("text/html")) {
            throw new Error(
              "YouTube caption discovery returned an unsafe content type.",
            );
          }
        },
      });
      const visitorData = extractYouTubeWatchConfig(body, "VISITOR_DATA");
      const apiKey = extractYouTubeWatchConfig(body, "INNERTUBE_API_KEY");
      const playerUrl = new URL("/youtubei/v1/player", YOUTUBE_WATCH_ORIGIN);
      playerUrl.searchParams.set("prettyPrint", "false");
      playerUrl.searchParams.set("key", apiKey);
      const playerBody = await fetchBoundedCaptionText(playerUrl.href, signal, {
        accept: "application/json",
        timeoutMs: YOUTUBE_WATCH_TIMEOUT_MS,
        timeoutMessage: "YouTube caption discovery timed out.",
        request: {
          method: "POST",
          body: JSON.stringify({
            context: {
              client: { ...YOUTUBE_PLAYER_CLIENT, visitorData },
            },
            videoId,
          }),
          headers: {
            "Content-Type": "application/json",
            "User-Agent": YOUTUBE_PLAYER_USER_AGENT,
            "X-YouTube-Client-Name": YOUTUBE_PLAYER_CLIENT_NAME,
            "X-YouTube-Client-Version": YOUTUBE_PLAYER_CLIENT_VERSION,
          },
        },
        validateResponse(response) {
          if (!response.ok) {
            throw new Error(
              `YouTube caption discovery failed (${response.status}).`,
            );
          }
          const contentType = response.headers
            .get("content-type")
            ?.toLowerCase();
          if (contentType && !contentType.includes("application/json")) {
            throw new Error(
              "YouTube caption discovery returned an unsafe content type.",
            );
          }
        },
      });
      const source = parseYouTubePlayerCaptionSource(
        JSON.parse(playerBody) as YouTubePlayerResponse,
        videoId,
        preferredLanguage,
      );
      const document = await downloadYouTubeCaptions(source.captionUrl, signal);
      return {
        language: source.language,
        durationSeconds: source.durationSeconds,
        segments: document.segments,
        sourceSegmentCount: document.sourceSegmentCount,
        isAutoGenerated: source.isAutoGenerated,
      };
    } catch (error) {
      if (signal.aborted) throw error;
      lastError = error;
      if (attempt < YOUTUBE_DIRECT_ATTEMPTS) {
        await new Promise((resolve) => setTimeout(resolve, 250));
      }
    }
  }
  throw lastError instanceof Error
    ? lastError
    : new Error("YouTube caption discovery failed.");
}

export async function downloadYouTubeCaptions(
  captionUrl: string,
  signal: AbortSignal,
): Promise<CompleteCaptionDocument> {
  const url = new URL(captionUrl);
  if (
    url.protocol !== "https:" ||
    (url.hostname !== "youtube.com" && !url.hostname.endsWith(".youtube.com"))
  ) {
    throw new Error("YouTube returned an invalid caption source.");
  }
  const body = await fetchBoundedCaptionText(url.href, signal, {
    accept: "application/json",
    timeoutMs: 15_000,
    timeoutMessage: "YouTube caption download timed out.",
    validateResponse(response) {
      if (!response.ok) {
        throw new Error(
          `YouTube caption download failed (${response.status}).`,
        );
      }
    },
  });
  const document = parseYouTubeTimedTextDocument(
    JSON.parse(body) as TimedTextPayload,
  );
  if (!document.segments.length)
    throw new Error("YouTube returned empty captions.");
  return document;
}
