import { expect, test, type Page, type Route } from "@playwright/test";

const BASE_URL = "http://localhost:8081";
const VIDEO_ID = "11111111-1111-4111-8111-111111111111";
const VIDEO_ID_TWO = "22222222-2222-4222-8222-222222222222";
const QUIZ_ID = "33333333-3333-4333-8333-333333333333";
const ATTEMPT_ID = "44444444-4444-4444-8444-444444444444";
const COMPLETE_ATTEMPT_ID = "55555555-5555-4555-8555-555555555555";
const QUESTION_ID = "66666666-6666-4666-8666-666666666666";
const NEXT_QUESTION_ID = "77777777-7777-4777-8777-777777777777";
const JOB_ID = "88888888-8888-4888-8888-888888888888";
const THUMBNAIL_URL = `${BASE_URL}/test-thumbnail.svg`;
const SCREENSHOT_DIR = "docs/screenshots/final";

type Scenario = {
  answerCorrect: boolean;
  completedAttempt: boolean;
  generationMode: "stable" | "failed";
  importMode: "success" | "unavailable";
  requestedPaths: string[];
};

const baseQuestion = {
  id: QUESTION_ID,
  type: "multiple_choice" as const,
  prompt: "Why does retrieval practice strengthen long-term memory?",
  options: [
    "It requires the brain to reconstruct the idea",
    "It makes every video shorter",
    "It removes the need for sleep",
    "It guarantees perfect recall",
  ],
  difficulty: 2,
  position: 1,
  total: 5,
  isRetry: false,
};

const nextQuestion = {
  id: NEXT_QUESTION_ID,
  type: "true_false" as const,
  prompt: "Spacing practice over time can improve retention.",
  difficulty: 2,
  position: 2,
  total: 5,
  isRetry: false,
};

const importedVideo = {
  video: {
    id: VIDEO_ID,
    source: "youtube" as const,
    sourceVideoId: "clipquest-learning-science",
    title: "How memory really works: retrieval, spacing, and sleep",
    thumbnailUrl: THUMBNAIL_URL,
    durationSeconds: 754,
    sourceLanguage: "en",
  },
  captions: {
    available: true,
    tracks: [{ language: "en", label: "English", isAutoGenerated: false }],
    preferredSegments: [
      {
        id: "segment-1",
        startMs: 0,
        endMs: 24_000,
        text: "Retrieval practice strengthens the paths used to reconstruct an idea.",
      },
    ],
  },
  requiresLocalTranscription: false,
};

const dueCard = {
  videoId: VIDEO_ID,
  quizId: QUIZ_ID,
  attemptId: ATTEMPT_ID,
  originalUrl: "https://www.youtube.com/watch?v=clipquest-learning-science",
  source: "youtube" as const,
  title: "How memory really works: retrieval, spacing, and sleep",
  thumbnailUrl: THUMBNAIL_URL,
  bestScore: 76,
  mastery: "learning" as const,
  action: "continue" as const,
  dueForReview: true,
};

const savedCard = {
  ...dueCard,
  videoId: VIDEO_ID_TWO,
  quizId: null,
  attemptId: null,
  originalUrl: "https://www.bilibili.com/video/BV1clipquest",
  source: "bilibili" as const,
  title: "A visual guide to the Feynman technique",
  bestScore: null,
  mastery: "not_started" as const,
  action: "start" as const,
  dueForReview: false,
};

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    window.localStorage.setItem(
      "clipquest:settings:v1",
      JSON.stringify({ locale: "en", themeMode: "light", reduceMotion: true }),
    );
  });
});

test("desktop learning journey and visual states", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  const scenario = await installMocks(page);

  await page.goto("/welcome");
  await expect(
    page.getByLabel("Paste a YouTube or bilibili link"),
  ).toBeVisible();

  await page.goto("/");
  await expect(
    page.getByRole("heading", { name: "What do you want to master?" }),
  ).toBeVisible();
  await capture(page, "desktop-link-import");

  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await page.goto(`/create/${VIDEO_ID}`);
  await expect(
    page.getByRole("heading", { name: "Video ready" }),
  ).toBeVisible();
  await capture(page, "desktop-video-preview");

  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "visual-idempotency",
    jobId: JOB_ID,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expect(
    page.getByRole("heading", { name: "Creating questions" }),
  ).toBeVisible();
  await capture(page, "desktop-processing");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.completedAttempt = false;
  scenario.answerCorrect = true;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "desktop-quiz-initial");

  const firstAnswer = page.getByRole("button", {
    name: baseQuestion.options[0],
  });
  await firstAnswer.focus();
  await firstAnswer.press("Space");
  await expect(
    page.getByRole("button", { name: "Check answer" }),
  ).toBeEnabled();
  await capture(page, "desktop-quiz-selected");
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(page.getByText("Nice! That’s right.")).toBeVisible();
  await capture(page, "desktop-feedback-correct");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.answerCorrect = false;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  await capture(page, "desktop-feedback-incorrect");

  scenario.completedAttempt = true;
  await page.goto(`/quiz/${COMPLETE_ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toBeVisible();
  await capture(page, "desktop-completion");

  await page.goto("/library");
  await expect(page.getByRole("heading", { name: "Library" })).toBeVisible();
  await capture(page, "desktop-library");

  await page.goto("/settings");
  await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  await capture(page, "desktop-settings");

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("mobile link, processing, lesson feedback, and completion", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const scenario = await installMocks(page);

  await page.goto("/");
  await expect(
    page.getByLabel("Paste a YouTube or bilibili link"),
  ).toBeVisible();
  await capture(page, "mobile-link-import");

  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "mobile-idempotency",
    jobId: JOB_ID,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expect(
    page.getByRole("heading", { name: "Creating questions" }),
  ).toBeVisible();
  await capture(page, "mobile-processing");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.completedAttempt = false;
  scenario.answerCorrect = false;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "mobile-quiz");
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  await capture(page, "mobile-feedback");

  scenario.completedAttempt = true;
  await page.goto(`/quiz/${COMPLETE_ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toBeVisible();
  await capture(page, "mobile-completion");
  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("tablet layout and target viewport sweep remain link-first without overflow", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  const viewports = [
    { width: 1440, height: 1000 },
    { width: 1280, height: 900 },
    { width: 1024, height: 900 },
    { width: 768, height: 1024 },
    { width: 412, height: 915 },
    { width: 393, height: 852 },
    { width: 390, height: 844 },
    { width: 375, height: 812 },
    { width: 360, height: 800 },
  ];

  for (const viewport of viewports) {
    await page.setViewportSize(viewport);
    await page.goto("/");
    await expect(
      page.getByLabel("Paste a YouTube or bilibili link"),
    ).toBeVisible();
    const dimensions = await page.evaluate(() => ({
      scrollWidth: document.documentElement.scrollWidth,
      width: window.innerWidth,
    }));
    expect(
      dimensions.scrollWidth,
      `${viewport.width}px viewport should not overflow`,
    ).toBeLessThanOrEqual(dimensions.width + 1);
    if (viewport.width === 768) await capture(page, "tablet-link-import");
  }

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("manual YouTube and bilibili imports validate and recover from unavailable video", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1024, height: 850 });
  const scenario = await installMocks(page);
  await page.goto("/");
  const input = page.getByLabel("Paste a YouTube or bilibili link");

  await input.fill("https://example.com/not-supported");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page.getByRole("alert")).toContainText(
    "valid YouTube or bilibili",
  );

  scenario.importMode = "unavailable";
  await input.fill("https://www.youtube.com/watch?v=private-video");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page.getByRole("alert")).toContainText("unavailable");

  scenario.importMode = "success";
  await input.fill("https://www.bilibili.com/video/BV1clipquest");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page).toHaveURL(new RegExp(`/create/${VIDEO_ID}$`));
  await expect(page.getByText("Bilibili", { exact: true })).toBeVisible();

  await page.goto("/");
  await input.fill(
    "https://www.youtube.com/watch?v=clipquest-learning-science",
  );
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page).toHaveURL(new RegExp(`/create/${VIDEO_ID}$`));
  await expect(page.getByText("YouTube", { exact: true }).last()).toBeVisible();

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("processing failure exposes retry and resumes the same durable job", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  const scenario = await installMocks(page);
  scenario.generationMode = "failed";
  await page.goto("/");
  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "retry-idempotency",
    jobId: JOB_ID,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expect(
    page.getByRole("heading", { name: "Quiz creation stopped" }),
  ).toBeVisible();
  await expect(page.getByRole("alert")).toContainText(
    "could not create trustworthy questions",
  );
  await page.getByRole("button", { name: "Retry" }).click();
  await expect(
    page.getByRole("heading", { name: "Creating questions" }),
  ).toBeVisible();
});

async function installMocks(page: Page): Promise<Scenario> {
  const scenario: Scenario = {
    answerCorrect: true,
    completedAttempt: false,
    generationMode: "stable",
    importMode: "success",
    requestedPaths: [],
  };

  await page.route("**/test-thumbnail.svg", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "image/svg+xml",
      body: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#4856D8"/><stop offset="1" stop-color="#43BCEB"/></linearGradient></defs><rect width="800" height="450" rx="28" fill="url(#g)"/><circle cx="630" cy="100" r="82" fill="#B8F244" opacity=".9"/><path d="M322 118v214l184-107z" fill="#fff" opacity=".94"/><text x="54" y="390" fill="#fff" font-size="36" font-family="Arial" font-weight="700">LEARNING SCIENCE</text></svg>`,
    });
  });

  await page.route("**/api/**", async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    const path = url.pathname;
    scenario.requestedPaths.push(path);

    if (path === "/api/auth/get-session") {
      await json(route, sessionFixture());
      return;
    }
    if (path === "/api/library") {
      await json(route, {
        dueReviews: [dueCard],
        saved: [savedCard],
        youtubeSuggestions: [],
      });
      return;
    }
    if (path === "/api/videos/import") {
      if (scenario.importMode === "unavailable") {
        await json(
          route,
          {
            error: {
              code: "video_unavailable",
              message: "This video is private or unavailable.",
            },
          },
          422,
        );
        return;
      }
      const body = request.postDataJSON() as { url?: string };
      const bilibili = body.url?.includes("bilibili");
      await json(route, {
        ...importedVideo,
        video: {
          ...importedVideo.video,
          source: bilibili ? "bilibili" : "youtube",
          sourceVideoId: bilibili
            ? "BV1clipquest"
            : importedVideo.video.sourceVideoId,
        },
      });
      return;
    }
    if (path === `/api/generation/${JOB_ID}` && request.method() === "GET") {
      if (scenario.generationMode === "failed") {
        await json(route, {
          jobId: JOB_ID,
          stage: "failed",
          progress: 0.58,
          quizId: null,
          error: {
            code: "generation_failed",
            message: "The transcript could not create trustworthy questions.",
          },
        });
        return;
      }
      await json(route, {
        jobId: JOB_ID,
        stage: "creating_questions",
        progress: 0.58,
        quizId: null,
        error: null,
      });
      return;
    }
    if (
      path === `/api/generation/${JOB_ID}/retry` &&
      request.method() === "POST"
    ) {
      scenario.generationMode = "stable";
      await json(route, {
        jobId: JOB_ID,
        stage: "creating_questions",
        progress: 0.08,
        quizId: null,
        error: null,
      });
      return;
    }
    if (path === `/api/generation/${JOB_ID}` && request.method() === "DELETE") {
      await json(route, {
        jobId: JOB_ID,
        stage: "failed",
        progress: 0,
        quizId: null,
        error: null,
      });
      return;
    }
    if (path.endsWith("/resume") && path.includes("/api/attempts/")) {
      const completed =
        scenario.completedAttempt || path.includes(COMPLETE_ATTEMPT_ID);
      await json(route, {
        attemptId: completed ? COMPLETE_ATTEMPT_ID : ATTEMPT_ID,
        question: completed ? null : baseQuestion,
        completed,
        score: completed ? 88 : null,
        mastery: completed ? "mastered" : null,
      });
      return;
    }
    if (path.endsWith("/answer") && path.includes("/api/attempts/")) {
      await json(route, {
        correct: scenario.answerCorrect,
        explanation: scenario.answerCorrect
          ? "Reconstructing an idea strengthens the retrieval path and reveals what still needs practice."
          : "The key is effortful reconstruction: recalling the idea strengthens access to it later.",
        evidenceSegmentIds: ["segment-1"],
        nextQuestion,
        completed: false,
        score: null,
        mastery: null,
      });
      return;
    }

    await json(
      route,
      {
        error: { code: "unmocked_request", message: `No fixture for ${path}` },
      },
      404,
    );
  });

  return scenario;
}

async function seed(page: Page, key: string, value: unknown): Promise<void> {
  await page.evaluate(
    ({ storageKey, storedValue }) =>
      window.localStorage.setItem(storageKey, JSON.stringify(storedValue)),
    { storageKey: key, storedValue: value },
  );
}

async function seedAttempt(
  page: Page,
  attemptId: string,
  question: typeof baseQuestion,
): Promise<void> {
  await seed(page, `clipquest:attempt:${attemptId}`, {
    attemptId,
    primer: null,
    question,
    primerSeen: true,
  });
}

async function capture(page: Page, name: string): Promise<void> {
  await page.screenshot({
    path: `${SCREENSHOT_DIR}/${name}.png`,
    fullPage: true,
    animations: "disabled",
  });
}

async function json(route: Route, body: unknown, status = 200): Promise<void> {
  await route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

function sessionFixture() {
  return {
    user: {
      id: "99999999-9999-4999-8999-999999999999",
      name: "Avery Learner",
      email: "avery@example.com",
      emailVerified: true,
      image: null,
      ageConfirmed: true,
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
    },
    session: {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      userId: "99999999-9999-4999-8999-999999999999",
      token: "playwright-session",
      expiresAt: "2026-08-31T00:00:00.000Z",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
    },
  };
}
