import { expect, test, type Page, type Route } from "@playwright/test";
import {
  DEFAULT_QUIZ_QUESTION_TYPES,
  createTranscriptCompleteness,
  type GenerationRecordV2,
  type PublicQuestion,
} from "@clipquest/contracts";

const BASE_URL = "http://localhost:8081";
const VIDEO_ID = "11111111-1111-4111-8111-111111111111";
const VIDEO_ID_TWO = "22222222-2222-4222-8222-222222222222";
const QUIZ_ID = "33333333-3333-4333-8333-333333333333";
const ATTEMPT_ID = "44444444-4444-4444-8444-444444444444";
const COMPLETE_ATTEMPT_ID = "55555555-5555-4555-8555-555555555555";
const QUESTION_ID = "66666666-6666-4666-8666-666666666666";
const NEXT_QUESTION_ID = "77777777-7777-4777-8777-777777777777";
const JOB_ID = "88888888-8888-4888-8888-888888888888";
const THUMBNAIL_URL = `${BASE_URL}/test-thumbnail.svg`;
const SCREENSHOT_DIR =
  process.env.CLIPQUEST_SCREENSHOT_DIR ?? "docs/screenshots/final";
const ADMIN_USER_ID = "12121212-1212-4121-8121-121212121212";
const GENERATION_ID = "abababab-abab-4bab-8bab-abababababab";
const GENERATION_SESSION_ID = "bcbcbcbc-bcbc-4bcb-8bcb-bcbcbcbcbcbc";
const GENERATION_IMPORT_KEY = "cdcdcdcd-cdcd-4dcd-8dcd-cdcdcdcdcdcd";

type Scenario = {
  adminMode: "allowed" | "denied";
  answerCorrect: boolean;
  completedAttempt: boolean;
  generationMode: "stable" | "failed";
  importMode: "success" | "unavailable";
  thumbnailMode: "stable" | "fail-once" | "failed";
  thumbnailFailureTag?: string;
  thumbnailRequestCount: number;
  extensionCaptionImport: boolean;
  requestedPaths: string[];
  quizImportBodies: unknown[];
  quizImportKeys: (string | null)[];
  quizStartBodies: unknown[];
  answerBodies: unknown[];
  progressiveAvailable: number;
  progressiveTotal: 5 | 10 | 15;
  progressiveState:
    | "generating"
    | "retrying"
    | "recovering"
    | "cooldown"
    | "retry_required"
    | "action_required"
    | "generation_failed"
    | "ready";
  claimLeased: boolean;
  question: PublicQuestion;
};

const baseQuestion = {
  id: QUESTION_ID,
  type: "multiple_choice" as const,
  prompt: "Why does retrieval practice strengthen long-term memory?",
  options: [
    "It requires the brain to reconstruct the idea",
    "It makes every video shorter",
    "It removes the need for sleep",
    "It guarantees perfect recall",
  ],
  difficulty: 2,
  position: 1,
  total: 5,
  isRetry: false,
};

const nextQuestion = {
  id: NEXT_QUESTION_ID,
  type: "true_false" as const,
  prompt: "Spacing practice over time can improve retention.",
  difficulty: 2,
  position: 2,
  total: 5,
  isRetry: false,
};

const trueFalseQuestion: PublicQuestion = {
  ...baseQuestion,
  id: "67676767-6767-4767-8767-676767676767",
  type: "true_false",
  prompt: "Retrieval practice is the same as passively rereading notes.",
  options: undefined,
};

const shortAnswerQuestion: PublicQuestion = {
  ...baseQuestion,
  id: "68686868-6868-4868-8868-686868686868",
  type: "short_answer",
  prompt: "Name one reason spaced retrieval improves long-term memory.",
  options: undefined,
};

const formulaProseQuestion: PublicQuestion = {
  ...baseQuestion,
  id: "69696969-6969-4969-8969-696969696969",
  type: "true_false",
  prompt:
    "For a function f defined on an interval from x = a to x = b, the average rate of change is (f(b)-f(a))/(b-a), and this value is the slope of the secant line through the points (a, f(a)) and (b, f(b)).",
  options: undefined,
};

const captionSegments = [
  {
    id: "segment-1",
    startMs: 0,
    endMs: 24_000,
    text: "Retrieval practice strengthens the paths used to reconstruct an idea.",
  },
];

const importedVideo = {
  video: {
    id: VIDEO_ID,
    source: "youtube" as const,
    sourceVideoId: "clipquest-learning-science",
    title: "How memory really works: retrieval, spacing, and sleep",
    thumbnailUrl: THUMBNAIL_URL,
    durationSeconds: 754,
    sourceLanguage: "en",
  },
  captions: {
    available: true,
    tracks: [{ language: "en", label: "English", isAutoGenerated: false }],
    preferredSegments: captionSegments,
    preferredCompleteness: createTranscriptCompleteness(captionSegments, 754),
  },
  transcriptionMode: "captions" as const,
  capture: { expectedDurationSeconds: 754, requiresUserGesture: false },
  requiresLocalTranscription: false,
};

const dueCard = {
  videoId: VIDEO_ID,
  quizId: QUIZ_ID,
  attemptId: ATTEMPT_ID,
  originalUrl: "https://www.youtube.com/watch?v=clipquest-learning-science",
  source: "youtube" as const,
  title: "How memory really works: retrieval, spacing, and sleep",
  thumbnailUrl: THUMBNAIL_URL,
  bestScore: 76,
  mastery: "learning" as const,
  action: "continue" as const,
  dueForReview: true,
};

const savedCard = {
  ...dueCard,
  videoId: VIDEO_ID_TWO,
  quizId: QUIZ_ID,
  attemptId: null,
  originalUrl: "https://www.youtube.com/watch?v=feynman-learning",
  source: "youtube" as const,
  title: "A visual guide to the Feynman technique",
  bestScore: null,
  mastery: "not_started" as const,
  action: "start" as const,
  dueForReview: false,
  startSettings: {
    sessionLength: "long" as const,
    questionTypes: ["short_answer"] as const,
  },
};

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    if (window.sessionStorage.getItem("clipquest:e2e-preserve-theme") !== "1") {
      window.localStorage.setItem(
        "clipquest:settings:v1",
        JSON.stringify({
          locale: "en",
          themeMode: "light",
          reduceMotion: true,
        }),
      );
    }
    window.addEventListener("message", (event) => {
      if (
        event.source !== window ||
        event.data?.channel !== "clipquest:captions:v1" ||
        event.data?.source !== "clipquest-website" ||
        window.sessionStorage.getItem("clipquest:e2e-extension-missing") === "1"
      ) {
        return;
      }
      if (event.data.type === "ping") {
        const outdated =
          window.sessionStorage.getItem("clipquest:e2e-extension-outdated") ===
          "1";
        window.postMessage(
          {
            channel: "clipquest:captions:v1",
            source: "clipquest-extension",
            type: "ready",
            version: outdated ? "0.7.9" : "0.8.8",
            configured: true,
            capabilities: outdated
              ? []
              : [
                  "question-stream-v1",
                  "question-stream-v2",
                  "question-stream-v3",
                  "question-stream-v4",
                  "question-stream-v5",
                  "question-stream-v6",
                  "ensure-source-ready-v1",
                ],
          },
          window.location.origin,
        );
      }
      if (event.data.type === "generate") {
        const conceptFirst =
          event.data.context?.generationProfile === "concept_first_auto_v5_8";
        const automatic =
          conceptFirst ||
          event.data.context?.generationProfile ===
            "evidence_grounded_auto_v5_4";
        const questionCount = event.data.context?.questionCount ?? 10;
        const generatedStartIndex =
          event.data.context?.continuation?.startIndex ?? 0;
        const legacyAutomaticRecovery =
          event.data.context?.continuation?.resultProtocolVersion === 5 &&
          generatedStartIndex > 0;
        const selectedTypes = event.data.context?.questionTypes ?? [
          "multiple_choice",
          "true_false",
          "short_answer",
        ];
        const questionPlan = event.data.context?.continuation?.questionPlan ?? {
          seed: "a".repeat(64),
          types: Array.from(
            { length: questionCount },
            (_, index) => selectedTypes[index % selectedTypes.length],
          ),
        };
        let trueFalseIndex = 0;
        const questions = Array.from({ length: questionCount }, (_, index) => {
          const type = questionPlan.types[index];
          const common = {
            id: `q${index + 1}`,
            concept: `Concept ${index + 1}`,
            question: `How does concept ${index + 1} apply?`,
            explanation: `Concept ${index + 1} supports this answer.`,
            ...(automatic
              ? {
                  claimKey: `concept ${index + 1} supports answer ${index + 1}`,
                  conceptCluster: `concept ${index + 1}`,
                }
              : {}),
          };
          if (type === "true_false") {
            const answer = trueFalseIndex % 2 === 0;
            trueFalseIndex += 1;
            return {
              ...common,
              type: "true_false",
              answer,
              correction: `Concept ${index + 1} is corrected here.`,
            };
          }
          if (type === "short_answer") {
            return {
              ...common,
              type: "short_answer",
              answer: `Reference answer ${index + 1}`,
              rubricIdeas: [`Concept ${index + 1}`],
              acceptableAnswers: [`Equivalent answer ${index + 1}`],
            };
          }
          return {
            ...common,
            type: "multiple_choice",
            choices: [
              `Correct ${index + 1}`,
              `Distractor A ${index + 1}`,
              `Distractor B ${index + 1}`,
              `Distractor C ${index + 1}`,
            ],
            answerIndex: 0,
            answer: `Correct ${index + 1}`,
          };
        });
        const metadata = conceptFirst
          ? {
              protocolVersion: 9,
              pipelineVersion: 9,
              model: "deepseek-v4-flash",
              reasoningEffort: "none",
              promptVersion: "quiz-local-json-stream-v5.8",
              validatorVersion: "validator-local-progressive-v4.7",
              importVersion: "extension-progressive-import-v7",
              generationProfile: "concept_first_auto_v5_8",
              generationId: event.data.context.generationId,
              generationSessionId: event.data.context.generationSessionId,
              recoverySessionId: event.data.context.recoverySessionId,
              questionPlan,
              promptFingerprint: "a".repeat(64),
            }
          : automatic
            ? {
                protocolVersion: 8,
                pipelineVersion: 9,
                model: "deepseek-v4-flash",
                reasoningEffort: "none",
                promptVersion: "quiz-local-json-stream-v5.7",
                validatorVersion: "validator-local-progressive-v4.6",
                importVersion: "extension-progressive-import-v6",
                generationProfile: "evidence_grounded_auto_v5_4",
                generationId: event.data.context.generationId,
                generationSessionId: event.data.context.generationSessionId,
                recoverySessionId: event.data.context.recoverySessionId,
                questionPlan,
              }
            : {
                protocolVersion: 5,
                pipelineVersion: 9,
                model: "deepseek-v4-flash",
                reasoningEffort: "high",
                promptVersion: "quiz-local-json-stream-v5.0",
                validatorVersion: "validator-local-progressive-v4.0",
              };
        const initialCallIndex =
          event.data.context?.continuation?.nextCallIndex ?? 0;
        const postQuestion = (
          question: (typeof questions)[number],
          index: number,
        ) => {
          const relativeCallIndex = index - generatedStartIndex;
          const firstRecoveryAttempt =
            relativeCallIndex === 0
              ? (event.data.context?.continuation?.nextOrdinalAttempt ?? 1)
              : 1;
          const callEventBase = {
            protocolVersion: conceptFirst ? 9 : automatic ? 8 : 5,
            purpose:
              automatic || conceptFirst ? "generation" : "automatic_recovery",
            generationSessionId: event.data.context.generationSessionId,
            recoverySessionId: event.data.context.recoverySessionId,
            callIndex: initialCallIndex + relativeCallIndex,
            startIndex: index,
            ordinalAttempt: firstRecoveryAttempt,
            requestedCount: 1,
            classification:
              firstRecoveryAttempt > 1 ? "automatic_retry" : "primary",
            ...(firstRecoveryAttempt > 1
              ? {
                  retryKind:
                    event.data.context?.continuation?.retryKind ??
                    "automatic_resume",
                }
              : {}),
            retryDelayMs: 0,
            usageComplete: false,
          };
          if (conceptFirst) {
            window.postMessage(
              {
                channel: "clipquest:captions:v1",
                source: "clipquest-extension",
                type: "generation-call",
                requestId: event.data.requestId,
                event: {
                  ...callEventBase,
                  lifecycleState: "started",
                  acceptedCount: 0,
                },
              },
              window.location.origin,
            );
          }
          window.postMessage(
            {
              channel: "clipquest:captions:v1",
              source: "clipquest-extension",
              type: "generation-question",
              requestId: event.data.requestId,
              result: {
                ...metadata,
                title: "Local concept quiz",
                startIndex: index,
                totalQuestions: questionCount,
                question,
                metrics: {
                  aiCalls: index === 0 ? 1 : 0,
                  retryCount: 0,
                  inputTokens: 0,
                  outputTokens: 0,
                  reasoningTokens: 0,
                  elapsedMs: 10,
                },
              },
            },
            window.location.origin,
          );
          if (automatic || legacyAutomaticRecovery) {
            window.postMessage(
              {
                channel: "clipquest:captions:v1",
                source: "clipquest-extension",
                type: "generation-call",
                requestId: event.data.requestId,
                event: {
                  ...callEventBase,
                  ...(conceptFirst ? { lifecycleState: "completed" } : {}),
                  acceptedCount: 1,
                  outcome: "complete",
                  elapsedMs: 10,
                  ...(conceptFirst ? { lastStreamActivityElapsedMs: 8 } : {}),
                },
              },
              window.location.origin,
            );
          }
        };
        postQuestion(questions[generatedStartIndex], generatedStartIndex);
        const completionDelay = Number(
          window.sessionStorage.getItem(
            "clipquest:e2e-generation-completion-delay-ms",
          ) ?? "1200",
        );
        window.setTimeout(() => {
          window.sessionStorage.setItem(
            "clipquest:e2e-second-question-sent",
            "1",
          );
          questions
            .slice(generatedStartIndex + 1)
            .forEach((question, index) =>
              postQuestion(question, generatedStartIndex + index + 1),
            );
          window.postMessage(
            {
              channel: "clipquest:captions:v1",
              source: "clipquest-extension",
              type: "generation-result",
              requestId: event.data.requestId,
              response: {
                ok: true,
                result: {
                  ...metadata,
                  ...(generatedStartIndex > 0
                    ? {
                        title: "Local concept quiz",
                        generatedStartIndex,
                        totalQuestions: questionCount,
                      }
                    : {
                        quiz: { title: "Local concept quiz", questions },
                      }),
                  metrics: {
                    aiCalls: 1,
                    retryCount: 0,
                    inputTokens: 100,
                    outputTokens: 200,
                    reasoningTokens: 0,
                    elapsedMs: 1000,
                  },
                },
              },
            },
            window.location.origin,
          );
        }, completionDelay);
      }
      if (
        event.data.type === "extract" ||
        event.data.type === "ensure-source-ready"
      ) {
        window.postMessage(
          {
            channel: "clipquest:captions:v1",
            source: "clipquest-extension",
            type:
              event.data.type === "ensure-source-ready"
                ? "source-ready-result"
                : "result",
            requestId: event.data.requestId,
            response: {
              ok: true,
              result: {
                videoId: event.data.videoId,
                language: "en",
                isAutoGenerated: true,
                method: "caption_track",
                sourceSegmentCount: 1,
                durationSeconds: 754,
                segments: [
                  {
                    id: "youtube-extension-e2e-0",
                    startMs: 0,
                    endMs: 5_000,
                    text: "The extension returned this complete caption segment.",
                  },
                ],
              },
            },
          },
          window.location.origin,
        );
      }
    });
  });
});

test("sign-in splits on desktop and collapses cleanly on mobile", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  await page.goto("/sign-in");

  const brandPane = page.getByTestId("auth-split-brand-pane");
  const formPane = page.getByTestId("auth-split-form-pane");
  const divider = page.getByTestId("auth-split-divider");

  await expect(brandPane).toBeVisible();
  await expect(formPane).toBeVisible();
  await expect(divider).toBeVisible();
  await expect(
    brandPane.getByText("Turn YouTube lessons into lasting knowledge"),
  ).toBeVisible();
  await expect(
    formPane.getByRole("heading", { name: "Welcome back" }),
  ).toBeVisible();

  const desktopLayout = await page.evaluate(() => {
    const brand = document.querySelector<HTMLElement>(
      '[data-testid="auth-split-brand-pane"]',
    );
    const form = document.querySelector<HTMLElement>(
      '[data-testid="auth-split-form-pane"]',
    );
    const split = document.querySelector<HTMLElement>(
      '[data-testid="auth-split-divider"]',
    );
    if (!brand || !form || !split) throw new Error("Missing sign-in split");
    const brandRect = brand.getBoundingClientRect();
    const formRect = form.getBoundingClientRect();
    const dividerRect = split.getBoundingClientRect();
    const lockup = brand.querySelector<HTMLElement>(
      '[data-testid="clipquest-auth-wordmark"]',
    );
    const lockupRect = lockup?.getBoundingClientRect();
    return {
      brandWidth: brandRect.width,
      formWidth: formRect.width,
      dividerX: dividerRect.x,
      brandBackground: getComputedStyle(brand).backgroundColor,
      formBackground: getComputedStyle(form).backgroundColor,
      dividerShadow: getComputedStyle(split).boxShadow,
      lockupWidth: lockupRect?.width,
      markWidth: lockup?.querySelector("img")?.getBoundingClientRect().width,
      lockupLeftGutter: lockupRect ? lockupRect.left - brandRect.left : null,
      lockupRightGutter: lockupRect ? brandRect.right - lockupRect.right : null,
      hasOverflow:
        document.documentElement.scrollWidth >
        document.documentElement.clientWidth + 1,
    };
  });

  expect(desktopLayout.brandWidth).toBeCloseTo(720, 0);
  expect(desktopLayout.formWidth).toBeCloseTo(720, 0);
  expect(desktopLayout.dividerX).toBeCloseTo(720, 0);
  expect(desktopLayout.brandBackground).not.toBe(desktopLayout.formBackground);
  expect(desktopLayout.dividerShadow).not.toBe("none");
  expect(desktopLayout.dividerShadow).toContain("24px 0px 24px -8px");
  expect(desktopLayout.lockupWidth).toBeGreaterThan(440);
  expect(desktopLayout.lockupWidth).toBeLessThan(480);
  expect(desktopLayout.markWidth).toBe(148);
  expect(desktopLayout.lockupLeftGutter).toBeCloseTo(
    desktopLayout.lockupRightGutter ?? 0,
    0,
  );
  expect(desktopLayout.hasOverflow).toBe(false);

  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await expect(
    page.getByRole("heading", { name: "Welcome back" }),
  ).toBeVisible();
  await expect(page.getByTestId("auth-split-brand-pane")).toHaveCount(0);
  await expect(page.getByTestId("auth-split-form-pane")).toHaveCount(0);
  await expect(page.getByTestId("auth-split-divider")).toHaveCount(0);
  await expect(page.getByRole("img", { name: "ClipQuest" })).toBeVisible();

  const mobileOverflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth >
      document.documentElement.clientWidth + 1,
  );
  expect(mobileOverflow).toBe(false);
});

test("unauthenticated entry defaults to sign-in and sign-up links to welcome", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  await page.goto("/");
  await expect(page).toHaveURL(/\/sign-in$/);
  await expect(
    page.getByRole("heading", { name: "Welcome back" }),
  ).toBeVisible();

  await page.goto("/forgot-password");
  await expect(
    page.getByRole("heading", { name: "Forgot password?" }),
  ).toBeVisible();
  await expect(page.locator("img")).toHaveCount(1);
  await expect(
    page.getByRole("button", { name: "Send reset link" }).locator("img"),
  ).toHaveCount(0);

  await page.goto("/sign-up");
  const trialLink = page.getByTestId("try-without-account-link");
  await expect(trialLink).toHaveText(
    "Don’t want to create an account but want to try?",
  );
  await expect(trialLink).toBeVisible();

  const cornerAlignment = await page.evaluate(() => {
    const trial = document.querySelector<HTMLElement>(
      '[data-testid="try-without-account-link"]',
    );
    if (!trial) throw new Error("Missing sign-up trial link");
    const rect = trial.getBoundingClientRect();
    return {
      rightGap: window.innerWidth - rect.right,
      bottomGap: window.innerHeight - rect.bottom,
    };
  });
  expect(cornerAlignment.rightGap).toBeCloseTo(32, 0);
  expect(cornerAlignment.bottomGap).toBeCloseTo(32, 0);

  await trialLink.click();
  await expect(page).toHaveURL(/\/welcome$/);
  await expect(
    page.getByRole("heading", {
      name: "Paste a YouTube video. Build real mastery.",
    }),
  ).toBeVisible();

  const quickOpenVideo = "https://www.youtube.com/watch?v=AbCdEfGhI12";
  await page.goto(`/welcome?url=${encodeURIComponent(quickOpenVideo)}`);
  await expect(page.locator('input[type="url"]')).toHaveValue(quickOpenVideo);

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/sign-up");
  const mobileTrialLink = page.getByTestId("try-without-account-link");
  await expect(mobileTrialLink).toBeVisible();
  const mobileAlignment = await page.evaluate(() => {
    const trial = document.querySelector<HTMLElement>(
      '[data-testid="try-without-account-link"]',
    );
    const input = document.querySelector<HTMLInputElement>(
      'input[aria-label="Username"]',
    );
    if (!trial || !input?.parentElement)
      throw new Error("Missing mobile sign-up controls");
    return {
      trialRight: trial.getBoundingClientRect().right,
      fieldRight: input.parentElement.getBoundingClientRect().right,
    };
  });
  expect(mobileAlignment.trialRight).toBeCloseTo(mobileAlignment.fieldRight, 0);
  const mobileOverflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth >
      document.documentElement.clientWidth + 1,
  );
  expect(mobileOverflow).toBe(false);
});

test("requires the local caption extension and reconnects automatically", async ({
  page,
}) => {
  await installMocks(page);
  await page.goto("/");
  await page.evaluate(() =>
    window.sessionStorage.setItem("clipquest:e2e-extension-missing", "1"),
  );
  await page.reload();

  await expect(
    page.getByRole("heading", { name: "Install the Chrome extension" }),
  ).toBeVisible();
  await expect(page.getByTestId("download-caption-extension")).toBeVisible();
  await expect(
    page.getByText("chrome://extensions", { exact: false }),
  ).toBeVisible();

  await page.evaluate(() =>
    window.sessionStorage.removeItem("clipquest:e2e-extension-missing"),
  );
  await page.getByTestId("check-caption-extension").click();
  await expect(
    page.getByRole("heading", { name: "Install the Chrome extension" }),
  ).toBeHidden();
  await expect(page).toHaveURL(/\/$/);
  await expect(
    page.getByRole("heading", {
      name: "What do you want to master?",
    }),
  ).toBeVisible();
});

test("an older extension is gated until question streaming is available", async ({
  page,
}) => {
  await installMocks(page);
  await page.goto("/");
  await page.evaluate(() =>
    window.sessionStorage.setItem("clipquest:e2e-extension-outdated", "1"),
  );
  await page.reload();

  await expect(
    page.getByRole("heading", { name: "Update ClipQuest Local AI" }),
  ).toBeVisible();
  await expect(
    page.getByText("0.8.8 or newer", { exact: false }),
  ).toBeVisible();

  await page.evaluate(() =>
    window.sessionStorage.removeItem("clipquest:e2e-extension-outdated"),
  );
  await page.getByTestId("check-caption-extension").click();
  await expect(
    page.getByRole("heading", { name: "Update ClipQuest Local AI" }),
  ).toBeHidden();
});

test("imports the extension quiz, opens the learner flow, and accepts an answer", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.extensionCaptionImport = true;
  await page.goto("/");
  await page
    .getByLabel("Paste a YouTube link")
    .fill("https://www.youtube.com/watch?v=SVb9OV0bLzI&t=44s");
  await expectCreateRouteWithGeneration(page);
  await page.getByRole("radio", { name: "Short · 5" }).click();
  await page.getByRole("button", { name: "Create my quiz" }).click();

  await expectQuizRoute(page, true);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  expect(
    await page.evaluate(() =>
      window.sessionStorage.getItem("clipquest:e2e-second-question-sent"),
    ),
  ).toBeNull();
  await expect(page.getByTestId("question-stream-indicator")).toContainText(
    "1/5 questions ready",
  );
  expect(scenario.requestedPaths).toContain("/api/videos/import");
  expect(scenario.requestedPaths).toContain("/api/quiz-imports/progressive");
  expect(scenario.requestedPaths).toContain(`/api/quizzes/${QUIZ_ID}/start`);
  expect(scenario.quizImportKeys).toHaveLength(1);
  expect(scenario.quizImportKeys[0]).toMatch(
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
  );
  expect(JSON.stringify(scenario.quizImportBodies)).not.toContain("segments");
  expect(JSON.stringify(scenario.quizImportBodies)).not.toContain("transcript");

  await expect(page.getByTestId("question-stream-indicator")).toBeHidden({
    timeout: 5_000,
  });

  await page.getByRole("button", { name: baseQuestion.options[0] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText(
      "Reconstructing an idea strengthens the retrieval path and reveals what still needs practice.",
    ),
  ).toBeVisible();
  expect(scenario.answerBodies).toHaveLength(1);
  expect(scenario.answerBodies[0]).toMatchObject({
    questionId: QUESTION_ID,
    answer: 0,
  });
});

test("reopens a completed progressive quiz with its stored Library settings", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.progressiveAvailable = 15;
  scenario.progressiveTotal = 15;
  await page.goto("/library");
  await page
    .getByRole("button", { name: /A visual guide to the Feynman technique/u })
    .click();
  await expectQuizRoute(page);
  expect(scenario.quizStartBodies).toEqual([
    {
      mode: "learn",
      sessionLength: "long",
      questionTypes: ["short_answer"],
    },
  ]);
});

test("multiple-choice views reshuffle only on activation and submit canonical indexes", async ({
  page,
}) => {
  await page.addInitScript(() => {
    const cryptoObject = window.crypto;
    const original = cryptoObject.getRandomValues.bind(cryptoObject);
    Object.defineProperty(cryptoObject, "getRandomValues", {
      configurable: true,
      value: <T extends ArrayBufferView | null>(array: T): T => {
        const current = Number(
          window.sessionStorage.getItem("clipquest:e2e-random-draws") ?? "0",
        );
        window.sessionStorage.setItem(
          "clipquest:e2e-random-draws",
          String(current + 1),
        );
        return original(array);
      },
    });
  });
  const scenario = await installMocks(page);
  scenario.answerCorrect = false;
  await page.goto("/");
  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  await seedGenerationRecord(page, {
    quizId: QUIZ_ID,
    attemptId: ATTEMPT_ID,
    acceptedCount: 1,
    state: "generating",
  });
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();

  const initialOrder = await displayedChoiceOrder(page, baseQuestion.options);
  const initialDraws = await randomDrawCount(page);
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  expect(await displayedChoiceOrder(page, baseQuestion.options)).toEqual(
    initialOrder,
  );
  expect(await randomDrawCount(page)).toBe(initialDraws);
  expect(scenario.answerBodies[0]).toMatchObject({ answer: 1 });

  scenario.answerCorrect = true;
  await page.getByRole("button", { name: "Next" }).click();
  await expect(
    page.getByRole("heading", {
      name: `Try again: ${baseQuestion.prompt}`,
    }),
  ).toBeVisible();
  expect(await randomDrawCount(page)).toBeGreaterThan(initialDraws);
  expect(await displayedChoiceOrder(page, baseQuestion.options)).toHaveLength(
    4,
  );

  await page.getByRole("button", { name: baseQuestion.options[0] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(page.getByText("Nice! That’s right.")).toBeVisible();
  expect(scenario.answerBodies[1]).toMatchObject({ answer: 0 });
});

test("a fast learner waits without partial completion and resumes when question two arrives", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.progressiveAvailable = 1;
  scenario.progressiveTotal = 5;
  scenario.progressiveState = "generating";
  scenario.claimLeased = true;
  await page.goto("/");
  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();

  await page.getByRole("button", { name: baseQuestion.options[0] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(page.getByText("Nice! That’s right.")).toBeVisible();
  await page.getByRole("button", { name: "Next" }).click();
  await expect(
    page.getByRole("heading", { name: "Preparing your next question" }),
  ).toBeVisible();
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toHaveCount(0);

  scenario.progressiveAvailable = 2;
  scenario.question = nextQuestion;
  await expect(
    page.getByRole("heading", { name: nextQuestion.prompt }),
  ).toBeVisible({ timeout: 4_000 });
  await expect(page.getByTestId("question-stream-indicator")).toContainText(
    "2/5 questions ready",
  );
});

test("legacy retry-required quizzes recover automatically from the authoritative missing suffix", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.progressiveAvailable = 3;
  scenario.progressiveTotal = 5;
  scenario.progressiveState = "retry_required";
  await page.goto("/");
  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "99999999-9999-4999-8999-999999999999",
    quizLanguage: "en",
    questionTypes: DEFAULT_QUIZ_QUESTION_TYPES,
    sessionLength: "short",
    watched: true,
    quizId: QUIZ_ID,
    attemptId: ATTEMPT_ID,
    acceptedCount: 3,
    plannedCount: 5,
  });
  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  await page.goto(`/quiz/${ATTEMPT_ID}`);

  await expect(page.getByTestId("question-stream-indicator")).toContainText(
    "Recovering legacy generation automatically · 3/5 ready",
  );
  await expect(
    page.getByRole("button", { name: "Continue generating" }),
  ).toHaveCount(0);
  await expect
    .poll(
      () =>
        scenario.requestedPaths.filter(
          (path) => path === `/api/attempts/${ATTEMPT_ID}/generation/claim`,
        ).length,
    )
    .toBeGreaterThan(0);
  await expect(page.getByTestId("question-stream-indicator")).toContainText(
    "/5",
  );
  await expect(page.getByTestId("question-stream-indicator")).toBeHidden({
    timeout: 5_000,
  });
  expect(scenario.progressiveAvailable).toBe(5);
  const appendedIndexes = scenario.quizImportBodies
    .map((body) =>
      typeof body === "object" && body
        ? (body as { chunk?: { startIndex?: number } }).chunk?.startIndex
        : undefined,
    )
    .filter((index): index is number => typeof index === "number");
  expect(appendedIndexes).toEqual([3, 4]);
});

test("a reloaded legacy quiz reclaims and recovers without learner action", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.progressiveAvailable = 1;
  scenario.progressiveTotal = 5;
  scenario.progressiveState = "retry_required";
  await page.goto("/");
  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "91919191-9191-4191-8191-919191919191",
    quizLanguage: "en",
    questionTypes: DEFAULT_QUIZ_QUESTION_TYPES,
    sessionLength: "short",
    watched: true,
    quizId: QUIZ_ID,
    attemptId: ATTEMPT_ID,
    acceptedCount: 1,
    plannedCount: 5,
  });
  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  await page.goto(`/quiz/${ATTEMPT_ID}`);

  await expect(
    page.getByRole("button", { name: "Continue generating" }),
  ).toHaveCount(0);
  await expect(page.getByTestId("question-stream-indicator")).toBeHidden({
    timeout: 5_000,
  });
  const appendedIndexes = scenario.quizImportBodies
    .map((body) =>
      typeof body === "object" && body
        ? (body as { chunk?: { startIndex?: number } }).chunk?.startIndex
        : undefined,
    )
    .filter((index): index is number => typeof index === "number");
  expect(appendedIndexes).toEqual([1, 2, 3, 4]);
});

test("the streaming indicator stays inside each gutter and above the quiz footer", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  await page.goto("/");
  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  const generationId = await seedGenerationRecord(page, {
    sessionLength: "short",
    plannedCount: 5,
  });
  await page.evaluate(() =>
    window.sessionStorage.setItem(
      "clipquest:e2e-generation-completion-delay-ms",
      "30000",
    ),
  );
  await page.goto(
    `/generation/${VIDEO_ID}?generationId=${generationId}&watched=true&quizLanguage=en&sessionLength=short`,
  );
  await expectQuizRoute(page, true);
  await expect(page.getByTestId("question-stream-indicator")).toBeVisible();

  for (const viewport of [
    { width: 1440, height: 1024, gutter: 32 },
    { width: 768, height: 1024, gutter: 24 },
    { width: 390, height: 844, gutter: 20 },
  ]) {
    await page.setViewportSize(viewport);
    const indicator = await page
      .getByTestId("question-stream-indicator")
      .boundingBox();
    const check = await page
      .getByRole("button", { name: "Check answer" })
      .boundingBox();
    expect(indicator).not.toBeNull();
    expect(check).not.toBeNull();
    expect(
      viewport.width - (indicator?.x ?? 0) - (indicator?.width ?? 0),
    ).toBeCloseTo(viewport.gutter, 0);
    expect((indicator?.y ?? 0) + (indicator?.height ?? 0)).toBeLessThan(
      check?.y ?? 0,
    );
    for (const option of baseQuestion.options) {
      const answer = await page
        .getByRole("button", { name: option })
        .boundingBox();
      expect(boxesOverlap(indicator, answer)).toBe(false);
    }
  }

  scenario.question = shortAnswerQuestion;
  await seedAttempt(page, ATTEMPT_ID, shortAnswerQuestion);
  await page.reload();
  const shortAnswer = page.getByLabel("Short answer");
  await expect(shortAnswer).toBeVisible();
  await shortAnswer.focus();
  const focusedIndicator = await page
    .getByTestId("question-stream-indicator")
    .boundingBox();
  const focusedFooter = await page
    .getByRole("button", { name: "Check answer" })
    .boundingBox();
  expect(boxesOverlap(focusedIndicator, focusedFooter)).toBe(false);

  expect(scenario.progressiveState).toBe("generating");
});

test("YouTube quick open lands on Home and starts one import automatically", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  const quickOpenVideo = "https://www.youtube.com/watch?v=SVb9OV0bLzI&t=44s";

  await page.goto(`/?url=${encodeURIComponent(quickOpenVideo)}&autostart=1`);

  await expectCreateRouteWithGeneration(page);
  expect(
    scenario.requestedPaths.filter((path) => path === "/api/videos/import"),
  ).toHaveLength(1);
});

test("a cold thumbnail retries without shifting the create page", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.thumbnailMode = "fail-once";
  scenario.thumbnailFailureTag = "cold";
  await page.goto("/");
  await seed(page, `clipquest:creation:${VIDEO_ID}`, {
    ...importedVideo,
    video: {
      ...importedVideo.video,
      thumbnailUrl: `${THUMBNAIL_URL}?thumbnail_case=cold`,
    },
  });

  await page.goto(`/create/${VIDEO_ID}`);
  const thumbnail = page.getByTestId("create-video-thumbnail");
  await expect(thumbnail).toBeVisible();
  const loadingBounds = await thumbnail.boundingBox();

  await expect
    .poll(() => scenario.thumbnailRequestCount, { timeout: 5_000 })
    .toBe(2);
  await expect(
    page.getByTestId("create-video-thumbnail-placeholder"),
  ).toBeHidden();

  const loadedBounds = await thumbnail.boundingBox();
  expect(loadingBounds).not.toBeNull();
  expect(loadedBounds).not.toBeNull();
  expect(loadedBounds?.width).toBeCloseTo(loadingBounds?.width ?? 0, 0);
  expect(loadedBounds?.height).toBeCloseTo(loadingBounds?.height ?? 0, 0);
  await expect(
    page.getByRole("button", { name: "Create my quiz" }),
  ).toBeEnabled();
});

test("a permanent thumbnail failure keeps quiz setup usable", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.thumbnailMode = "failed";
  scenario.thumbnailFailureTag = "permanent";
  await page.goto("/");
  await seed(page, `clipquest:creation:${VIDEO_ID}`, {
    ...importedVideo,
    video: {
      ...importedVideo.video,
      thumbnailUrl: `${THUMBNAIL_URL}?thumbnail_case=permanent`,
    },
  });

  await page.goto(`/create/${VIDEO_ID}`);
  await expect(page.getByTestId("create-video-thumbnail-retry")).toBeVisible({
    timeout: 7_000,
  });
  expect(scenario.thumbnailRequestCount).toBe(4);
  await expect(
    page.getByText("The thumbnail is taking longer than expected."),
  ).toBeVisible();
  await expect(
    page.getByRole("button", { name: "Create my quiz" }),
  ).toBeEnabled();
});

test("desktop learning journey and visual states", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  const scenario = await installMocks(page);

  await page.goto("/welcome");
  await expect(page.getByLabel("Paste a YouTube link")).toBeVisible();

  await page.goto("/");
  await expect(
    page.getByRole("heading", { name: "What do you want to master?" }),
  ).toBeVisible();
  const homeVisuals = await page.evaluate(() => {
    const byText = (selector: string, value: string) =>
      [...document.querySelectorAll<HTMLElement>(selector)].find((element) =>
        element.textContent?.includes(value),
      );
    const action = byText('[role="button"]', "Make my quest");
    const questionType =
      document.querySelector<HTMLElement>('[role="checkbox"]');
    const savedCard = byText(
      '[role="button"]',
      "A visual guide to the Feynman technique",
    );
    if (!action || !questionType || !savedCard) {
      throw new Error("Missing styled Home controls");
    }
    const actionStyle = getComputedStyle(action);
    const questionStyle = getComputedStyle(questionType);
    const cardStyle = getComputedStyle(savedCard);
    return {
      actionBackground: actionStyle.backgroundColor,
      actionHeight: action.getBoundingClientRect().height,
      questionBorder: questionStyle.borderTopWidth,
      cardBorder: cardStyle.borderTopWidth,
      cardWidth: savedCard.getBoundingClientRect().width,
      hasOverflow:
        document.documentElement.scrollWidth >
        document.documentElement.clientWidth + 1,
    };
  });
  expect(homeVisuals.actionBackground).not.toBe("rgba(0, 0, 0, 0)");
  expect(homeVisuals.actionHeight).toBeGreaterThanOrEqual(52);
  expect(homeVisuals.questionBorder).not.toBe("0px");
  expect(homeVisuals.cardBorder).not.toBe("0px");
  expect(homeVisuals.cardWidth).toBeGreaterThan(260);
  expect(homeVisuals.cardWidth).toBeLessThan(380);
  expect(homeVisuals.hasOverflow).toBe(false);
  await capture(page, "desktop-link-import");

  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await page.goto(`/create/${VIDEO_ID}`);
  await expect(
    page.getByRole("heading", { name: "Video ready" }),
  ).toBeVisible();
  await capture(page, "desktop-video-preview");

  const generationId = await seedGenerationRecord(page, {
    sessionLength: "medium",
    plannedCount: 10,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?generationId=${generationId}&watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expectQuizRoute(page, true);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "desktop-generated-quiz");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.completedAttempt = false;
  scenario.answerCorrect = true;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  const quizCloseButton = page.getByRole("button", { name: "Cancel" });
  await expect(quizCloseButton).toContainText("×");
  await expect(quizCloseButton.locator("img")).toHaveCount(0);
  await capture(page, "desktop-quiz-initial");

  const firstAnswer = page.getByRole("button", {
    name: baseQuestion.options[0],
  });
  await firstAnswer.focus();
  await firstAnswer.press("Space");
  await expect(
    page.getByRole("button", { name: "Check answer" }),
  ).toBeEnabled();
  await capture(page, "desktop-quiz-selected");
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(page.getByText("Nice! That’s right.")).toBeVisible();
  await capture(page, "desktop-feedback-correct");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.answerCorrect = false;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  await capture(page, "desktop-feedback-incorrect");

  scenario.completedAttempt = true;
  await page.goto(`/quiz/${COMPLETE_ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toBeVisible();
  await capture(page, "desktop-completion");

  await page.goto("/library");
  await expect(page.getByRole("heading", { name: "Library" })).toBeVisible();
  await capture(page, "desktop-library");

  await page.goto("/settings");
  await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Account" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Appearance" })).toBeVisible();
  await expect(
    page.getByRole("heading", { name: "Review reminders" }),
  ).toHaveCount(0);
  await expect(
    page.getByRole("heading", { name: "Privacy & storage" }),
  ).toHaveCount(0);
  await capture(page, "desktop-settings");

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("mobile link, processing, lesson feedback, and completion", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const scenario = await installMocks(page);

  await page.goto("/");
  await expect(page.getByLabel("Paste a YouTube link")).toBeVisible();
  await capture(page, "mobile-link-import");

  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  const generationId = await seedGenerationRecord(page, {
    sessionLength: "medium",
    plannedCount: 10,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?generationId=${generationId}&watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expectQuizRoute(page, true);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "mobile-generated-quiz");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.completedAttempt = false;
  scenario.answerCorrect = false;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "mobile-quiz");
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  await capture(page, "mobile-feedback");

  scenario.completedAttempt = true;
  await page.goto(`/quiz/${COMPLETE_ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toBeVisible();
  await capture(page, "mobile-completion");
  await page.getByRole("button", { name: "Return to library" }).click();
  await expect(page).toHaveURL(/\/library$/);
  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("all generated question types keep the tactile learning layout", async ({
  page,
}) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  const scenario = await installMocks(page);
  await page.goto("/");

  scenario.question = trueFalseQuestion;
  await seedAttempt(page, ATTEMPT_ID, trueFalseQuestion);
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: trueFalseQuestion.prompt }),
  ).toBeVisible();
  await expect(page.getByRole("button", { name: "True" })).toBeVisible();
  await expect(page.getByRole("button", { name: "False" })).toBeVisible();
  await expect(
    page.getByRole("button", { name: "True" }).locator("img"),
  ).toHaveCount(0);
  await expect(
    page.getByRole("button", { name: "False" }).locator("img"),
  ).toHaveCount(0);
  await capture(page, "tablet-quiz-true-false");

  scenario.question = shortAnswerQuestion;
  scenario.progressiveAvailable = 2;
  scenario.progressiveTotal = 5;
  scenario.progressiveState = "generating";
  await seedAttempt(page, ATTEMPT_ID, shortAnswerQuestion);
  await seedGenerationRecord(page, {
    quizId: QUIZ_ID,
    attemptId: ATTEMPT_ID,
    acceptedCount: 2,
    state: "generating",
  });
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: shortAnswerQuestion.prompt }),
  ).toBeVisible();
  const shortAnswer = page.getByLabel("Short answer");
  await expect(shortAnswer).toBeVisible();
  await shortAnswer.focus();
  await expect(page.getByTestId("question-stream-indicator")).toBeVisible();
  expect(
    boxesOverlap(
      await page.getByTestId("question-stream-indicator").boundingBox(),
      await page.getByRole("button", { name: "Check answer" }).boundingBox(),
    ),
  ).toBe(false);
  await capture(page, "tablet-quiz-short-answer");
});

test("formula-containing question prose keeps the display typeface", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.question = formulaProseQuestion;
  await page.goto("/");
  await seedAttempt(page, ATTEMPT_ID, formulaProseQuestion);
  await page.goto(`/quiz/${ATTEMPT_ID}`);

  const heading = page.getByRole("heading", {
    name: formulaProseQuestion.prompt,
  });
  await expect(heading).toBeVisible();
  await expect
    .poll(() =>
      heading.evaluate((element) => getComputedStyle(element).fontFamily),
    )
    .toContain("Fredoka_600SemiBold");
  await expect
    .poll(() =>
      heading.evaluate((element) => getComputedStyle(element).letterSpacing),
    )
    .toBe("-0.3px");
});

test("dark theme stays polished across learner, auth, settings, and admin shells", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  const scenario = await installMocks(page);
  await page.goto("/");
  await page.evaluate(() => {
    window.sessionStorage.setItem("clipquest:e2e-preserve-theme", "1");
    window.localStorage.setItem(
      "clipquest:settings:v1",
      JSON.stringify({ locale: "en", themeMode: "dark", reduceMotion: true }),
    );
  });
  await page.reload();
  await expect(
    page.getByRole("heading", { name: "What do you want to master?" }),
  ).toBeVisible();
  await expect
    .poll(() =>
      page
        .locator("body")
        .evaluate((body) => getComputedStyle(body).backgroundColor),
    )
    .toBe("rgb(16, 27, 21)");
  await capture(page, "dark-desktop-home");

  await page.goto("/settings");
  await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  await capture(page, "dark-desktop-settings");

  scenario.question = trueFalseQuestion;
  await seedAttempt(page, ATTEMPT_ID, trueFalseQuestion);
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: trueFalseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "dark-desktop-quiz");

  await page.goto("/admin");
  await expect(page.getByRole("heading", { name: "Overview" })).toBeVisible();
  await capture(page, "dark-desktop-admin");

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/welcome");
  await expect(
    page.getByRole("heading", {
      name: "Paste a YouTube video. Build real mastery.",
    }),
  ).toBeVisible();
  await capture(page, "dark-mobile-welcome");
  await page.goto("/");
  await expect(
    page.getByRole("heading", { name: "What do you want to master?" }),
  ).toBeVisible();
  await capture(page, "dark-mobile-home");
});

test("tablet layout and target viewport sweep remain link-first without overflow", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  const viewports = [
    { width: 1440, height: 1000 },
    { width: 1280, height: 900 },
    { width: 1024, height: 900 },
    { width: 768, height: 1024 },
    { width: 412, height: 915 },
    { width: 393, height: 852 },
    { width: 390, height: 844 },
    { width: 375, height: 812 },
    { width: 360, height: 800 },
  ];

  for (const viewport of viewports) {
    await page.setViewportSize(viewport);
    await page.goto("/");
    await expect(page.getByLabel("Paste a YouTube link")).toBeVisible();
    const dimensions = await page.evaluate(() => ({
      scrollWidth: document.documentElement.scrollWidth,
      width: window.innerWidth,
    }));
    expect(
      dimensions.scrollWidth,
      `${viewport.width}px viewport should not overflow`,
    ).toBeLessThanOrEqual(dimensions.width + 1);
    if (viewport.width === 768) await capture(page, "tablet-link-import");
  }

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("YouTube-only imports validate and recover from unavailable video", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1024, height: 850 });
  const scenario = await installMocks(page);
  await page.goto("/");
  const input = page.getByLabel("Paste a YouTube link");

  await input.fill("https://example.com/not-supported");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page.getByRole("alert")).toContainText("valid public YouTube");

  await input.fill("https://vimeo.com/123456789");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page.getByRole("alert")).toContainText("valid public YouTube");

  scenario.importMode = "unavailable";
  await input.fill("https://www.youtube.com/watch?v=private-video");
  await expect(page.getByRole("alert")).toContainText("unavailable");

  scenario.importMode = "success";
  await input.fill(
    "https://www.youtube.com/watch?v=clipquest-learning-science",
  );
  await expectCreateRouteWithGeneration(page);
  await expect(page.getByText("YouTube", { exact: true }).last()).toBeVisible();

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("admin operations console is responsive and uses real management contracts", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  await installMocks(page);
  await page.goto("/admin");
  await expect(page.getByRole("heading", { name: "Overview" })).toBeVisible();
  await expect(page.getByText("Protected data boundary")).toBeVisible();
  await capture(page, "admin-overview-desktop-1440");

  await page.getByRole("tab", { name: "People" }).click();
  await expect(page).toHaveURL(/\/admin\/users$/);
  await expect(page.getByText("Morgan Operator")).toBeVisible();
  await expect(page.getByRole("button", { name: "Suspend" })).toBeVisible();
  await capture(page, "admin-users-desktop-1440");
  await page.getByRole("button", { name: "Suspend" }).click();
  await page
    .getByLabel("Reason")
    .fill("Confirmed policy violation after support review");
  await page.getByRole("button", { name: "Suspend" }).last().click();
  await expect(
    page.getByText("Action completed and added to the audit log."),
  ).toBeVisible();

  await page.getByRole("tab", { name: "Generation streams" }).click();
  await expect(
    page.getByText("How memory really works: retrieval, spacing, and sleep"),
  ).toBeVisible();
  await capture(page, "admin-processing-desktop-1440");

  await page.getByRole("tab", { name: "Lessons" }).click();
  await expect(page.getByRole("heading", { name: "Lessons" })).toBeVisible();
  await expect(
    page.getByText("How memory really works: retrieval, spacing, and sleep"),
  ).toBeVisible();

  await page.getByRole("tab", { name: "Audit log" }).click();
  await expect(page.getByRole("heading", { name: "Audit log" })).toBeVisible();
  await expect(page.getByText("Generation retry")).toBeVisible();

  await page.getByRole("tab", { name: "System" }).click();
  await expect(page.getByRole("heading", { name: "System" })).toBeVisible();
  await expect(page.getByText("Disabled by design")).toBeVisible();
  await expect(
    page.getByText("0020_generation_call_lifecycle.sql"),
  ).toBeVisible();

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/admin/users");
  await expect(page.getByRole("heading", { name: "People" })).toBeVisible();
  const overflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth -
      document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(1);
  await capture(page, "admin-users-mobile-390");
});

test("admin console rejects a signed-in learner using the server role guard", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.adminMode = "denied";
  await page.goto("/admin");
  await expect(
    page.getByRole("heading", { name: "Operations access required" }),
  ).toBeVisible();
  await expect(
    page.getByRole("button", { name: "Return to ClipQuest" }),
  ).toBeVisible();
});

async function installMocks(page: Page): Promise<Scenario> {
  const scenario: Scenario = {
    adminMode: "allowed",
    answerCorrect: true,
    completedAttempt: false,
    generationMode: "stable",
    importMode: "success",
    thumbnailMode: "stable",
    thumbnailRequestCount: 0,
    extensionCaptionImport: false,
    requestedPaths: [],
    quizImportBodies: [],
    quizImportKeys: [],
    quizStartBodies: [],
    answerBodies: [],
    progressiveAvailable: 5,
    progressiveTotal: 5,
    progressiveState: "ready",
    claimLeased: false,
    question: baseQuestion,
  };

  await page.route("**/test-thumbnail.svg*", async (route) => {
    const thumbnailUrl = new URL(route.request().url());
    const targeted = scenario.thumbnailFailureTag
      ? thumbnailUrl.searchParams.get("thumbnail_case") ===
        scenario.thumbnailFailureTag
      : true;
    if (targeted) scenario.thumbnailRequestCount += 1;
    if (
      targeted &&
      (scenario.thumbnailMode === "failed" ||
        (scenario.thumbnailMode === "fail-once" &&
          scenario.thumbnailRequestCount === 1))
    ) {
      await route.fulfill({
        status: 503,
        headers: { "Cache-Control": "no-store", "Retry-After": "1" },
      });
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: "image/svg+xml",
      body: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#4856D8"/><stop offset="1" stop-color="#43BCEB"/></linearGradient></defs><rect width="800" height="450" rx="28" fill="url(#g)"/><circle cx="630" cy="100" r="82" fill="#B8F244" opacity=".9"/><path d="M322 118v214l184-107z" fill="#fff" opacity=".94"/><text x="54" y="390" fill="#fff" font-size="36" font-family="Arial" font-weight="700">LEARNING SCIENCE</text></svg>`,
    });
  });

  const generation = () => ({
    state: scenario.progressiveState,
    availableQuestions: scenario.progressiveAvailable,
    totalQuestions: scenario.progressiveTotal,
    ...(scenario.progressiveState === "retry_required"
      ? { reasonCode: "automatic_retries_exhausted" }
      : {}),
  });

  await page.route("**/api/**", async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    const path = url.pathname;
    scenario.requestedPaths.push(path);

    if (path === "/api/auth/get-session") {
      await json(route, sessionFixture());
      return;
    }
    if (path === "/api/admin/me") {
      if (scenario.adminMode === "denied") {
        await json(
          route,
          {
            error: {
              code: "admin_access_required",
              message: "You do not have access to ClipQuest operations.",
            },
          },
          403,
        );
        return;
      }
      await json(route, {
        user: {
          id: "99999999-9999-4999-8999-999999999999",
          name: "Avery Learner",
          email: "avery@example.com",
          role: "owner",
        },
        permissions: [
          "overview:read",
          "users:read",
          "users:moderate",
          "users:set-role",
          "jobs:read",
          "lessons:read",
          "audit:read",
          "system:read",
        ],
      });
      return;
    }
    if (path === "/api/admin/overview") {
      await json(route, {
        totals: { users: 1284, lessons: 3762, activeJobs: 7, failedJobs: 3 },
        activity: { newUsers7d: 86, lessons7d: 412, completedAttempts7d: 1205 },
        recentFailures: [
          {
            id: JOB_ID,
            videoTitle: "Neural networks explained visually",
            ownerEmail: "learner@example.com",
            errorCode: "automatic_retries_exhausted",
            errorMessage: null,
            updatedAt: "2026-07-31T09:40:00.000Z",
          },
        ],
      });
      return;
    }
    if (path === "/api/admin/users" && request.method() === "GET") {
      await json(route, {
        users: [
          {
            id: ADMIN_USER_ID,
            name: "Morgan Operator",
            email: "morgan@example.com",
            username: "morgan",
            role: "admin",
            banned: false,
            banReason: null,
            banExpiresAt: null,
            emailVerified: true,
            createdAt: "2026-07-12T08:00:00.000Z",
            lastSeenAt: "2026-07-31T09:45:00.000Z",
            lessonCount: 18,
            attemptCount: 42,
          },
          {
            id: "13131313-1313-4131-8131-131313131313",
            name: "Lin Student",
            email: "lin@example.com",
            username: "linlearns",
            role: "user",
            banned: true,
            banReason: "Repeated abuse reports",
            banExpiresAt: null,
            emailVerified: true,
            createdAt: "2026-07-20T08:00:00.000Z",
            lastSeenAt: "2026-07-29T10:00:00.000Z",
            lessonCount: 5,
            attemptCount: 9,
          },
        ],
        pagination: { page: 1, pageSize: 20, total: 2 },
      });
      return;
    }
    if (path === "/api/admin/jobs" && request.method() === "GET") {
      await json(route, {
        jobs: [],
        pagination: { page: 1, pageSize: 20, total: 0 },
      });
      return;
    }
    if (path === "/api/admin/generations" && request.method() === "GET") {
      await json(route, {
        generations: [
          {
            quizId: QUIZ_ID,
            state: "retry_required",
            acceptedQuestions: 6,
            plannedQuestions: 10,
            progress: 0.6,
            requestedQuestionTypes: [
              "multiple_choice",
              "true_false",
              "short_answer",
            ],
            aiCalls: 6,
            retryCount: 1,
            elapsedMs: 36_000,
            telemetrySource: "authoritative_calls",
            primaryCalls: 4,
            automaticRetries: 1,
            manualContinuations: 1,
            partialCalls: 1,
            outcomeCounts: {
              complete: 4,
              transient_http: 1,
              partial_accepted: 1,
            },
            tokenUsage: {
              inputTokens: 12_400,
              outputTokens: 2_160,
              reasoningTokens: 0,
              completeCalls: 5,
              unknownCalls: 1,
              complete: false,
            },
            firstQuestionLatencyMs: 7_200,
            reasonCode: "automatic_retries_exhausted",
            stalled: false,
            lastProgressAt: "2026-07-31T09:40:00.000Z",
            lastQuestionAt: "2026-07-31T09:40:00.000Z",
            lastAttemptAt: "2026-07-31T09:41:00.000Z",
            stateChangedAt: "2026-07-31T09:41:00.000Z",
            createdAt: "2026-07-31T09:30:00.000Z",
            owner: {
              id: ADMIN_USER_ID,
              name: "Morgan Operator",
              email: "morgan@example.com",
            },
            video: {
              id: VIDEO_ID,
              title: importedVideo.video.title,
              source: "youtube",
            },
          },
        ],
        pagination: { page: 1, pageSize: 20, total: 1 },
      });
      return;
    }
    if (path === "/api/admin/lessons" && request.method() === "GET") {
      await json(route, {
        lessons: [
          {
            id: QUIZ_ID,
            language: "en",
            sessionLength: "medium",
            watched: true,
            createdAt: "2026-07-31T08:00:00.000Z",
            questionCount: 10,
            attemptCount: 6,
            owner: {
              id: ADMIN_USER_ID,
              name: "Morgan Operator",
              email: "morgan@example.com",
            },
            video: {
              id: VIDEO_ID,
              title: importedVideo.video.title,
              source: "youtube",
            },
          },
        ],
        pagination: { page: 1, pageSize: 20, total: 1 },
      });
      return;
    }
    if (path === "/api/admin/audit" && request.method() === "GET") {
      await json(route, {
        entries: [
          {
            id: "14141414-1414-4141-8141-141414141414",
            action: "generation.retry",
            targetType: "generation_job",
            targetId: JOB_ID,
            reason: "Provider recovered after a short outage",
            outcome: "success",
            metadata: { previousState: "failed" },
            createdAt: "2026-07-31T09:50:00.000Z",
            actor: {
              id: "99999999-9999-4999-8999-999999999999",
              name: "Avery Learner",
              email: "avery@example.com",
            },
          },
        ],
        pagination: { page: 1, pageSize: 25, total: 1 },
      });
      return;
    }
    if (path === "/api/admin/system") {
      await json(route, {
        configuration: {
          authentication: true,
          generation: true,
          email: true,
          youtubeEncryption: true,
          youtubeDemoHistory: false,
        },
        model: "deepseek-v4-flash",
        jobs: { queued: 4, running: 3, complete: 3755, failed: 3 },
        database: {
          migration: "0020_generation_call_lifecycle.sql",
          auditEnabled: true,
        },
        generation: {
          mode: "extension_local",
          backendEnabled: false,
          extensionEnabled: true,
          extensionRequired: true,
          model: "deepseek-v4-flash",
          pipelineVersion: 9,
          promptVersion: "quiz-local-json-stream-v5.8",
          validatorVersion: "validator-local-progressive-v4.7",
          rolloutMode: "disabled",
          supportedProfile: "concept_first_auto_v5_8",
          supportedPromptVersion: "quiz-local-json-stream-v5.8",
          supportedValidatorVersion: "validator-local-progressive-v4.7",
          effectiveDefaultProfile: "legacy_reasoning_v5_1",
          requiredExtensionVersion: "0.8.8",
          requiredCapability: "question-stream-v6",
          states: {
            generating: 2,
            retrying: 1,
            recovering: 0,
            cooldown: 0,
            retryRequired: 3,
            actionRequired: 0,
            generationFailed: 0,
            ready: 3755,
          },
        },
        worker: {
          versionId: "873e0843-ab3b-4a2a-9d0d-4581dcceb810",
          versionTag: "e2e",
        },
      });
      return;
    }
    if (path.startsWith("/api/admin/") && request.method() === "POST") {
      await json(route, { ok: true });
      return;
    }
    if (path === "/api/library") {
      await json(route, {
        dueReviews: [dueCard],
        saved: [savedCard],
        youtubeSuggestions: [],
      });
      return;
    }
    if (path === "/api/videos/import") {
      if (scenario.importMode === "unavailable") {
        await json(
          route,
          {
            error: {
              code: "video_unavailable",
              message: "This video is private or unavailable.",
            },
          },
          422,
        );
        return;
      }
      const usesExtensionCaptions = scenario.extensionCaptionImport;
      await json(route, {
        ...importedVideo,
        video: {
          ...importedVideo.video,
          source: "youtube",
          sourceVideoId: usesExtensionCaptions
            ? "SVb9OV0bLzI"
            : importedVideo.video.sourceVideoId,
          durationSeconds: usesExtensionCaptions
            ? 0
            : importedVideo.video.durationSeconds,
        },
        ...(usesExtensionCaptions
          ? {
              captions: {
                available: true,
                tracks: [],
                browserSourceAvailable: false,
                browserLookupAvailable: true,
              },
              capture: {
                expectedDurationSeconds: 0,
                requiresUserGesture: false,
              },
            }
          : {}),
      });
      return;
    }
    if (
      path === "/api/quiz-imports/progressive" &&
      request.method() === "POST"
    ) {
      scenario.quizImportBodies.push(request.postDataJSON());
      scenario.quizImportKeys.push(
        request.headers()["idempotency-key"] ?? null,
      );
      const body = request.postDataJSON() as {
        chunk?: { totalQuestions?: 5 | 10 | 15 };
      };
      scenario.progressiveAvailable = 1;
      scenario.progressiveTotal = body.chunk?.totalQuestions ?? 5;
      scenario.progressiveState = "generating";
      await json(route, { quizId: QUIZ_ID, generation: generation() }, 201);
      return;
    }
    if (path === "/api/local-ai/profile" && request.method() === "GET") {
      await json(route, {
        generationProfile: "concept_first_auto_v5_8",
        minimumExtensionVersion: "0.8.8",
        requiredCapability: "question-stream-v6",
      });
      return;
    }
    if (
      path === `/api/videos/${VIDEO_ID}/source-metadata` &&
      request.method() === "PATCH"
    ) {
      await json(route, { videoId: VIDEO_ID, verified: true });
      return;
    }
    if (
      path === `/api/quiz-imports/${QUIZ_ID}/questions` &&
      request.method() === "PUT"
    ) {
      scenario.quizImportBodies.push(request.postDataJSON());
      scenario.quizImportKeys.push(
        request.headers()["idempotency-key"] ?? null,
      );
      const body = request.postDataJSON() as {
        chunk?: { startIndex?: number };
      };
      scenario.progressiveAvailable = Math.max(
        scenario.progressiveAvailable,
        (body.chunk?.startIndex ?? 0) + 1,
      );
      scenario.progressiveState =
        scenario.progressiveAvailable === scenario.progressiveTotal
          ? "ready"
          : "generating";
      await json(route, { quizId: QUIZ_ID, generation: generation() });
      return;
    }
    if (
      path === `/api/quiz-imports/${QUIZ_ID}/progress` &&
      request.method() === "PATCH"
    ) {
      const body = request.postDataJSON() as {
        state?: "retrying" | "retry_required";
      };
      scenario.progressiveState = body.state ?? "retry_required";
      await json(route, { quizId: QUIZ_ID, generation: generation() });
      return;
    }
    if (
      path.startsWith(`/api/quiz-imports/${QUIZ_ID}/calls/`) &&
      request.method() === "PUT"
    ) {
      await json(route, { quizId: QUIZ_ID, recorded: true }, 201);
      return;
    }
    if (
      path === `/api/quizzes/${QUIZ_ID}/start` &&
      request.method() === "POST"
    ) {
      scenario.quizStartBodies.push(request.postDataJSON());
      await json(
        route,
        {
          attemptId: ATTEMPT_ID,
          primer: null,
          question: {
            ...scenario.question,
            total: scenario.progressiveTotal,
          },
          generation: generation(),
        },
        201,
      );
      return;
    }
    if (
      path.endsWith("/generation/claim") &&
      path.includes("/api/attempts/") &&
      request.method() === "POST"
    ) {
      if (scenario.claimLeased) {
        await json(
          route,
          {
            error: {
              code: "generation_claim_leased",
              message: "Another tab owns the active recovery lease.",
            },
          },
          409,
        );
        return;
      }
      await json(route, {
        attemptId: path.includes(COMPLETE_ATTEMPT_ID)
          ? COMPLETE_ATTEMPT_ID
          : ATTEMPT_ID,
        quizId: QUIZ_ID,
        generation: generation(),
        claim: {
          state: "leased",
          leaseExpiresAt: "2026-08-10T08:15:00.000Z",
        },
      });
      return;
    }
    if (
      path.endsWith("/generation/heartbeat") &&
      path.includes("/api/attempts/") &&
      request.method() === "PUT"
    ) {
      await json(route, {
        attemptId: path.includes(COMPLETE_ATTEMPT_ID)
          ? COMPLETE_ATTEMPT_ID
          : ATTEMPT_ID,
        quizId: QUIZ_ID,
        generation: generation(),
        claim: {
          state: "leased",
          leaseExpiresAt: "2026-08-10T08:15:00.000Z",
        },
      });
      return;
    }
    if (
      path.endsWith("/generation") &&
      path.includes("/api/attempts/") &&
      request.method() === "GET"
    ) {
      if (path.includes(COMPLETE_ATTEMPT_ID)) {
        await json(route, {
          attemptId: COMPLETE_ATTEMPT_ID,
          quizId: QUIZ_ID,
          generation: {
            state: "ready",
            availableQuestions: scenario.progressiveTotal,
            totalQuestions: scenario.progressiveTotal,
          },
        });
        return;
      }
      await json(route, {
        attemptId: ATTEMPT_ID,
        quizId: QUIZ_ID,
        generation: generation(),
        ...(scenario.progressiveState !== "ready"
          ? {
              continuation: {
                videoId: VIDEO_ID,
                quizLanguage: "en",
                sessionLength:
                  scenario.progressiveTotal === 5
                    ? "short"
                    : scenario.progressiveTotal === 10
                      ? "medium"
                      : "long",
                questionTypes: DEFAULT_QUIZ_QUESTION_TYPES,
                watched: true,
                startIndex: scenario.progressiveAvailable,
                resultProtocolVersion: 5,
                pipelineVersion: 9,
                model: "deepseek-v4-flash",
                reasoningEffort: "high",
                promptVersion: "quiz-local-json-stream-v5.0",
                validatorVersion: "validator-local-progressive-v4.0",
                importVersion: "extension-progressive-import-v3",
                generationProfile: "legacy_reasoning_v5_1",
                generationId: GENERATION_ID,
                generationSessionId: GENERATION_SESSION_ID,
                nextCallIndex: 0,
                automaticRetryCount: 0,
                retryBudgetUsedCount: 0,
                automaticRecoveryCount: 0,
                claim: {
                  state:
                    scenario.progressiveState === "retry_required"
                      ? "available"
                      : "not_required",
                  leaseExpiresAt: null,
                },
                acceptedQuestions: Array.from(
                  { length: scenario.progressiveAvailable },
                  (_, index) => ({
                    id: `q${index + 1}`,
                    type: DEFAULT_QUIZ_QUESTION_TYPES[
                      index % DEFAULT_QUIZ_QUESTION_TYPES.length
                    ],
                    concept: `Concept ${index + 1}`,
                    question: `How does concept ${index + 1} apply?`,
                  }),
                ),
              },
            }
          : {}),
      });
      return;
    }
    if (path.endsWith("/resume") && path.includes("/api/attempts/")) {
      const completed =
        scenario.completedAttempt || path.includes(COMPLETE_ATTEMPT_ID);
      await json(route, {
        attemptId: completed ? COMPLETE_ATTEMPT_ID : ATTEMPT_ID,
        question: completed ? null : scenario.question,
        completed,
        score: completed ? 88 : null,
        mastery: completed ? "mastered" : null,
        generation: completed
          ? {
              state: "ready",
              availableQuestions: scenario.progressiveTotal,
              totalQuestions: scenario.progressiveTotal,
            }
          : generation(),
      });
      return;
    }
    if (path.endsWith("/answer") && path.includes("/api/attempts/")) {
      scenario.answerBodies.push(request.postDataJSON());
      await json(route, {
        correct: scenario.answerCorrect,
        explanation: scenario.answerCorrect
          ? "Reconstructing an idea strengthens the retrieval path and reveals what still needs practice."
          : "The key is effortful reconstruction: recalling the idea strengthens access to it later.",
        evidenceSegmentIds: ["segment-1"],
        nextQuestion: !scenario.answerCorrect
          ? {
              ...scenario.question,
              prompt: `Try again: ${scenario.question.prompt}`,
              isRetry: true,
            }
          : scenario.progressiveState !== "ready" &&
              scenario.question.position >= scenario.progressiveAvailable
            ? null
            : nextQuestion,
        completed: false,
        score: null,
        mastery: null,
        generation: generation(),
      });
      return;
    }

    await json(
      route,
      {
        error: { code: "unmocked_request", message: `No fixture for ${path}` },
      },
      404,
    );
  });

  return scenario;
}

async function seed(page: Page, key: string, value: unknown): Promise<void> {
  await page.evaluate(
    ({ storageKey, storedValue }) =>
      window.localStorage.setItem(storageKey, JSON.stringify(storedValue)),
    { storageKey: key, storedValue: value },
  );
}

async function seedGenerationRecord(
  page: Page,
  overrides: Partial<GenerationRecordV2> = {},
): Promise<string> {
  const timestamp = Date.now();
  const record: GenerationRecordV2 = {
    version: 2,
    generationId: GENERATION_ID,
    generationSessionId: GENERATION_SESSION_ID,
    idempotencyKey: GENERATION_IMPORT_KEY,
    ownerUserId: sessionFixture().user.id,
    videoId: VIDEO_ID,
    quizLanguage: "en",
    questionTypes: [...DEFAULT_QUIZ_QUESTION_TYPES],
    sessionLength: "short",
    watched: true,
    acceptedCount: 0,
    plannedCount: 5,
    state: "pending",
    nextCallIndex: 0,
    createdAt: timestamp,
    updatedAt: timestamp,
    ...overrides,
  };
  await seed(page, `clipquest:generation:v2:${record.generationId}`, record);
  if (record.attemptId) {
    await page.evaluate(
      ({ attemptId, generationId }) =>
        window.localStorage.setItem(
          `clipquest:generation-attempt:v2:${attemptId}`,
          generationId,
        ),
      { attemptId: record.attemptId, generationId: record.generationId },
    );
  }
  return record.generationId;
}

async function expectCreateRouteWithGeneration(page: Page): Promise<void> {
  await expect(page).toHaveURL((url) => {
    const generationId = url.searchParams.get("generationId") ?? "";
    return (
      url.pathname === `/create/${VIDEO_ID}` &&
      /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
        generationId,
      )
    );
  });
}

async function expectQuizRoute(
  page: Page,
  requiresGenerationId = false,
): Promise<void> {
  await expect(page).toHaveURL((url) => {
    if (url.pathname !== `/quiz/${ATTEMPT_ID}`) return false;
    if (!requiresGenerationId) return true;
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
      url.searchParams.get("generationId") ?? "",
    );
  });
}

async function seedAttempt(
  page: Page,
  attemptId: string,
  question: PublicQuestion,
): Promise<void> {
  await seed(page, `clipquest:attempt:${attemptId}`, {
    attemptId,
    primer: null,
    question,
    primerSeen: true,
  });
}

async function displayedChoiceOrder(
  page: Page,
  options: readonly string[],
): Promise<string[]> {
  const choices = await Promise.all(
    options.map(async (option) => ({
      option,
      box: await page.getByRole("button", { name: option }).boundingBox(),
    })),
  );
  return choices
    .sort(
      (left, right) =>
        (left.box?.y ?? 0) - (right.box?.y ?? 0) ||
        (left.box?.x ?? 0) - (right.box?.x ?? 0),
    )
    .map(({ option }) => option);
}

async function randomDrawCount(page: Page): Promise<number> {
  return page.evaluate(() =>
    Number(window.sessionStorage.getItem("clipquest:e2e-random-draws") ?? "0"),
  );
}

function boxesOverlap(
  left: { x: number; y: number; width: number; height: number } | null,
  right: { x: number; y: number; width: number; height: number } | null,
): boolean {
  if (!left || !right) return false;
  return !(
    left.x + left.width <= right.x ||
    right.x + right.width <= left.x ||
    left.y + left.height <= right.y ||
    right.y + right.height <= left.y
  );
}

async function capture(page: Page, name: string): Promise<void> {
  await page.screenshot({
    path: `${SCREENSHOT_DIR}/${name}.png`,
    fullPage: true,
    animations: "disabled",
  });
}

async function json(route: Route, body: unknown, status = 200): Promise<void> {
  await route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

function sessionFixture() {
  return {
    user: {
      id: "99999999-9999-4999-8999-999999999999",
      name: "Avery Learner",
      email: "avery@example.com",
      emailVerified: true,
      image: null,
      ageConfirmed: true,
      role: "user",
      banned: false,
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
    },
    session: {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      userId: "99999999-9999-4999-8999-999999999999",
      token: "playwright-session",
      expiresAt: "2026-08-31T00:00:00.000Z",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
    },
  };
}
