import { expect, test, type Page, type Route } from "@playwright/test";
import {
  DEFAULT_QUIZ_QUESTION_TYPES,
  createTranscriptCompleteness,
} from "@clipquest/contracts";

const BASE_URL = "http://localhost:8081";
const VIDEO_ID = "11111111-1111-4111-8111-111111111111";
const VIDEO_ID_TWO = "22222222-2222-4222-8222-222222222222";
const QUIZ_ID = "33333333-3333-4333-8333-333333333333";
const ATTEMPT_ID = "44444444-4444-4444-8444-444444444444";
const COMPLETE_ATTEMPT_ID = "55555555-5555-4555-8555-555555555555";
const QUESTION_ID = "66666666-6666-4666-8666-666666666666";
const NEXT_QUESTION_ID = "77777777-7777-4777-8777-777777777777";
const JOB_ID = "88888888-8888-4888-8888-888888888888";
const THUMBNAIL_URL = `${BASE_URL}/test-thumbnail.svg`;
const SCREENSHOT_DIR = "docs/screenshots/final";
const ADMIN_USER_ID = "12121212-1212-4121-8121-121212121212";

type Scenario = {
  adminMode: "allowed" | "denied";
  answerCorrect: boolean;
  completedAttempt: boolean;
  generationMode: "stable" | "failed";
  importMode: "success" | "unavailable";
  extensionCaptionImport: boolean;
  requestedPaths: string[];
  quizImportBodies: unknown[];
  quizImportKeys: (string | null)[];
};

const baseQuestion = {
  id: QUESTION_ID,
  type: "multiple_choice" as const,
  prompt: "Why does retrieval practice strengthen long-term memory?",
  options: [
    "It requires the brain to reconstruct the idea",
    "It makes every video shorter",
    "It removes the need for sleep",
    "It guarantees perfect recall",
  ],
  difficulty: 2,
  position: 1,
  total: 5,
  isRetry: false,
};

const nextQuestion = {
  id: NEXT_QUESTION_ID,
  type: "true_false" as const,
  prompt: "Spacing practice over time can improve retention.",
  difficulty: 2,
  position: 2,
  total: 5,
  isRetry: false,
};

const captionSegments = [
  {
    id: "segment-1",
    startMs: 0,
    endMs: 24_000,
    text: "Retrieval practice strengthens the paths used to reconstruct an idea.",
  },
];

const importedVideo = {
  video: {
    id: VIDEO_ID,
    source: "youtube" as const,
    sourceVideoId: "clipquest-learning-science",
    title: "How memory really works: retrieval, spacing, and sleep",
    thumbnailUrl: THUMBNAIL_URL,
    durationSeconds: 754,
    sourceLanguage: "en",
  },
  captions: {
    available: true,
    tracks: [{ language: "en", label: "English", isAutoGenerated: false }],
    preferredSegments: captionSegments,
    preferredCompleteness: createTranscriptCompleteness(captionSegments, 754),
  },
  transcriptionMode: "captions" as const,
  capture: { expectedDurationSeconds: 754, requiresUserGesture: false },
  requiresLocalTranscription: false,
};

const dueCard = {
  videoId: VIDEO_ID,
  quizId: QUIZ_ID,
  attemptId: ATTEMPT_ID,
  originalUrl: "https://www.youtube.com/watch?v=clipquest-learning-science",
  source: "youtube" as const,
  title: "How memory really works: retrieval, spacing, and sleep",
  thumbnailUrl: THUMBNAIL_URL,
  bestScore: 76,
  mastery: "learning" as const,
  action: "continue" as const,
  dueForReview: true,
};

const savedCard = {
  ...dueCard,
  videoId: VIDEO_ID_TWO,
  quizId: null,
  attemptId: null,
  originalUrl: "https://www.bilibili.com/video/BV1clipquest",
  source: "bilibili" as const,
  title: "A visual guide to the Feynman technique",
  bestScore: null,
  mastery: "not_started" as const,
  action: "start" as const,
  dueForReview: false,
};

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    window.localStorage.setItem(
      "clipquest:settings:v1",
      JSON.stringify({ locale: "en", themeMode: "light", reduceMotion: true }),
    );
    window.addEventListener("message", (event) => {
      if (
        event.source !== window ||
        event.data?.channel !== "clipquest:captions:v1" ||
        event.data?.source !== "clipquest-website" ||
        window.sessionStorage.getItem("clipquest:e2e-extension-missing") === "1"
      ) {
        return;
      }
      if (event.data.type === "ping") {
        window.postMessage(
          {
            channel: "clipquest:captions:v1",
            source: "clipquest-extension",
            type: "ready",
            version: "e2e",
            configured: true,
          },
          window.location.origin,
        );
      }
      if (event.data.type === "generate") {
        const questionCount = event.data.context?.questionCount ?? 10;
        window.postMessage(
          {
            channel: "clipquest:captions:v1",
            source: "clipquest-extension",
            type: "generation-result",
            requestId: event.data.requestId,
            response: {
              ok: true,
              result: {
                protocolVersion: 3,
                pipelineVersion: 7,
                model: "deepseek-v4-flash",
                reasoningEffort: "high",
                promptVersion: "quiz-local-tool-v2.0",
                validatorVersion: "validator-local-tool-v2.0",
                quiz: {
                  title: "Local concept quiz",
                  questions: Array.from(
                    { length: questionCount },
                    (_, index) => {
                      const common = {
                        id: `q${index + 1}`,
                        concept: `Concept ${index + 1}`,
                        question: `How does concept ${index + 1} apply?`,
                        explanation: `Concept ${index + 1} supports this answer.`,
                      };
                      if (index % 3 === 1) {
                        return {
                          ...common,
                          type: "true_false",
                          answer: index % 2 === 0,
                          correction: `Concept ${index + 1} is corrected here.`,
                        };
                      }
                      if (index % 3 === 2) {
                        return {
                          ...common,
                          type: "short_answer",
                          answer: `Reference answer ${index + 1}`,
                          rubricIdeas: [`Concept ${index + 1}`],
                          acceptableAnswers: [`Equivalent answer ${index + 1}`],
                        };
                      }
                      return {
                        ...common,
                        type: "multiple_choice",
                        choices: [
                          `Correct ${index + 1}`,
                          `Distractor A ${index + 1}`,
                          `Distractor B ${index + 1}`,
                          `Distractor C ${index + 1}`,
                        ],
                        answerIndex: 0,
                        answer: `Correct ${index + 1}`,
                      };
                    },
                  ),
                },
                metrics: {
                  aiCalls: 1,
                  retryCount: 0,
                  inputTokens: 100,
                  outputTokens: 200,
                  reasoningTokens: 50,
                  elapsedMs: 1000,
                },
              },
            },
          },
          window.location.origin,
        );
      }
      if (event.data.type === "extract") {
        window.postMessage(
          {
            channel: "clipquest:captions:v1",
            source: "clipquest-extension",
            type: "result",
            requestId: event.data.requestId,
            response: {
              ok: true,
              result: {
                videoId: event.data.videoId,
                language: "en",
                isAutoGenerated: true,
                method: "caption_track",
                sourceSegmentCount: 1,
                durationSeconds: 754,
                segments: [
                  {
                    id: "youtube-extension-e2e-0",
                    startMs: 0,
                    endMs: 5_000,
                    text: "The extension returned this complete caption segment.",
                  },
                ],
              },
            },
          },
          window.location.origin,
        );
      }
    });
  });
});

test("requires the local caption extension and reconnects automatically", async ({
  page,
}) => {
  await page.goto("/");
  await page.evaluate(() =>
    window.sessionStorage.setItem("clipquest:e2e-extension-missing", "1"),
  );
  await page.reload();

  await expect(
    page.getByRole("heading", { name: "Install ClipQuest Local AI" }),
  ).toBeVisible();
  await expect(page.getByTestId("download-caption-extension")).toBeVisible();
  await expect(
    page.getByText("chrome://extensions", { exact: false }),
  ).toBeVisible();

  await page.evaluate(() =>
    window.sessionStorage.removeItem("clipquest:e2e-extension-missing"),
  );
  await page.getByTestId("check-caption-extension").click();
  await expect(
    page.getByRole("heading", { name: "Install ClipQuest Local AI" }),
  ).toBeHidden();
  await expect(
    page.getByRole("heading", { name: "Paste a video. Build real mastery." }),
  ).toBeVisible();
});

test("imports the extension quiz, opens the learner flow, and accepts an answer", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.extensionCaptionImport = true;
  await page.goto("/");
  await page
    .getByLabel("Paste a YouTube or bilibili link")
    .fill("https://www.youtube.com/watch?v=SVb9OV0bLzI&t=44s");
  await expect(page).toHaveURL(`/create/${VIDEO_ID}`);
  await page.getByRole("radio", { name: "Short · 5" }).click();
  await page.getByRole("button", { name: "Create my quiz" }).click();

  await expect(page).toHaveURL(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  expect(scenario.requestedPaths).toContain("/api/videos/import");
  expect(scenario.requestedPaths).toContain("/api/quiz-imports");
  expect(scenario.requestedPaths).toContain(`/api/quizzes/${QUIZ_ID}/start`);
  expect(scenario.quizImportKeys).toHaveLength(1);
  expect(scenario.quizImportKeys[0]).toMatch(
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
  );
  expect(JSON.stringify(scenario.quizImportBodies)).not.toContain("segments");
  expect(JSON.stringify(scenario.quizImportBodies)).not.toContain("transcript");

  await page.getByRole("button", { name: baseQuestion.options[0] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText(
      "Reconstructing an idea strengthens the retrieval path and reveals what still needs practice.",
    ),
  ).toBeVisible();
});

test("desktop learning journey and visual states", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  const scenario = await installMocks(page);

  await page.goto("/welcome");
  await expect(
    page.getByLabel("Paste a YouTube or bilibili link"),
  ).toBeVisible();

  await page.goto("/");
  await expect(
    page.getByRole("heading", { name: "What do you want to master?" }),
  ).toBeVisible();
  await capture(page, "desktop-link-import");

  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await page.goto(`/create/${VIDEO_ID}`);
  await expect(
    page.getByRole("heading", { name: "Video ready" }),
  ).toBeVisible();
  await capture(page, "desktop-video-preview");

  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "visual-idempotency",
    jobId: JOB_ID,
    quizLanguage: "en",
    questionTypes: DEFAULT_QUIZ_QUESTION_TYPES,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expect(page).toHaveURL(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "desktop-generated-quiz");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.completedAttempt = false;
  scenario.answerCorrect = true;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "desktop-quiz-initial");

  const firstAnswer = page.getByRole("button", {
    name: baseQuestion.options[0],
  });
  await firstAnswer.focus();
  await firstAnswer.press("Space");
  await expect(
    page.getByRole("button", { name: "Check answer" }),
  ).toBeEnabled();
  await capture(page, "desktop-quiz-selected");
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(page.getByText("Nice! That’s right.")).toBeVisible();
  await capture(page, "desktop-feedback-correct");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.answerCorrect = false;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  await capture(page, "desktop-feedback-incorrect");

  scenario.completedAttempt = true;
  await page.goto(`/quiz/${COMPLETE_ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toBeVisible();
  await capture(page, "desktop-completion");

  await page.goto("/library");
  await expect(page.getByRole("heading", { name: "Library" })).toBeVisible();
  await capture(page, "desktop-library");

  await page.goto("/settings");
  await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  await capture(page, "desktop-settings");

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("mobile link, processing, lesson feedback, and completion", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const scenario = await installMocks(page);

  await page.goto("/");
  await expect(
    page.getByLabel("Paste a YouTube or bilibili link"),
  ).toBeVisible();
  await capture(page, "mobile-link-import");

  await seed(page, `clipquest:creation:${VIDEO_ID}`, importedVideo);
  await seed(page, `clipquest:generation:${VIDEO_ID}`, {
    idempotencyKey: "mobile-idempotency",
    jobId: JOB_ID,
    quizLanguage: "en",
    questionTypes: DEFAULT_QUIZ_QUESTION_TYPES,
  });
  await page.goto(
    `/generation/${VIDEO_ID}?watched=true&quizLanguage=en&sessionLength=medium`,
  );
  await expect(page).toHaveURL(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "mobile-generated-quiz");

  await seedAttempt(page, ATTEMPT_ID, baseQuestion);
  scenario.completedAttempt = false;
  scenario.answerCorrect = false;
  await page.goto(`/quiz/${ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: baseQuestion.prompt }),
  ).toBeVisible();
  await capture(page, "mobile-quiz");
  await page.getByRole("button", { name: baseQuestion.options[1] }).click();
  await page.getByRole("button", { name: "Check answer" }).click();
  await expect(
    page.getByText("Almost—try this concept another way."),
  ).toBeVisible();
  await capture(page, "mobile-feedback");

  scenario.completedAttempt = true;
  await page.goto(`/quiz/${COMPLETE_ATTEMPT_ID}`);
  await expect(
    page.getByRole("heading", { name: "Quest complete!" }),
  ).toBeVisible();
  await capture(page, "mobile-completion");
  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("tablet layout and target viewport sweep remain link-first without overflow", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  const viewports = [
    { width: 1440, height: 1000 },
    { width: 1280, height: 900 },
    { width: 1024, height: 900 },
    { width: 768, height: 1024 },
    { width: 412, height: 915 },
    { width: 393, height: 852 },
    { width: 390, height: 844 },
    { width: 375, height: 812 },
    { width: 360, height: 800 },
  ];

  for (const viewport of viewports) {
    await page.setViewportSize(viewport);
    await page.goto("/");
    await expect(
      page.getByLabel("Paste a YouTube or bilibili link"),
    ).toBeVisible();
    const dimensions = await page.evaluate(() => ({
      scrollWidth: document.documentElement.scrollWidth,
      width: window.innerWidth,
    }));
    expect(
      dimensions.scrollWidth,
      `${viewport.width}px viewport should not overflow`,
    ).toBeLessThanOrEqual(dimensions.width + 1);
    if (viewport.width === 768) await capture(page, "tablet-link-import");
  }

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("manual YouTube and bilibili imports validate and recover from unavailable video", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1024, height: 850 });
  const scenario = await installMocks(page);
  await page.goto("/");
  const input = page.getByLabel("Paste a YouTube or bilibili link");

  await input.fill("https://example.com/not-supported");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page.getByRole("alert")).toContainText(
    "valid YouTube or bilibili",
  );

  scenario.importMode = "unavailable";
  await input.fill("https://www.youtube.com/watch?v=private-video");
  await expect(page.getByRole("alert")).toContainText("unavailable");

  scenario.importMode = "success";
  await input.fill("https://www.bilibili.com/video/BV1clipquest");
  await page.getByRole("button", { name: "Make my quest" }).click();
  await expect(page).toHaveURL(new RegExp(`/create/${VIDEO_ID}$`));
  await expect(page.getByText("Bilibili", { exact: true })).toBeVisible();

  await page.goto("/");
  await expect(
    page.getByRole("heading", { name: "What do you want to master?" }),
  ).toBeVisible();
  const youtubeInput = page.getByLabel("Paste a YouTube or bilibili link");
  await youtubeInput.fill(
    "https://www.youtube.com/watch?v=clipquest-learning-science",
  );
  await expect(page).toHaveURL(new RegExp(`/create/${VIDEO_ID}$`));
  await expect(page.getByText("YouTube", { exact: true }).last()).toBeVisible();

  expect(
    scenario.requestedPaths.filter((path) => path.startsWith("/api/youtube")),
  ).toEqual([]);
});

test("admin operations console is responsive and uses real management contracts", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1024 });
  await installMocks(page);
  await page.goto("/admin");
  await expect(page.getByRole("heading", { name: "Overview" })).toBeVisible();
  await expect(page.getByText("Protected data boundary")).toBeVisible();
  await capture(page, "admin-overview-desktop-1440");

  await page.getByRole("tab", { name: "People" }).click();
  await expect(page).toHaveURL(/\/admin\/users$/);
  await expect(page.getByText("Morgan Operator")).toBeVisible();
  await expect(page.getByRole("button", { name: "Suspend" })).toBeVisible();
  await capture(page, "admin-users-desktop-1440");
  await page.getByRole("button", { name: "Suspend" }).click();
  await page
    .getByLabel("Reason")
    .fill("Confirmed policy violation after support review");
  await page.getByRole("button", { name: "Suspend" }).last().click();
  await expect(
    page.getByText("Action completed and added to the audit log."),
  ).toBeVisible();

  await page.getByRole("tab", { name: "Processing" }).click();
  await expect(
    page.getByText("How memory really works: retrieval, spacing, and sleep"),
  ).toBeVisible();
  await capture(page, "admin-processing-desktop-1440");

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/admin/users");
  await expect(page.getByRole("heading", { name: "People" })).toBeVisible();
  const overflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth -
      document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(1);
  await capture(page, "admin-users-mobile-390");
});

test("admin console rejects a signed-in learner using the server role guard", async ({
  page,
}) => {
  const scenario = await installMocks(page);
  scenario.adminMode = "denied";
  await page.goto("/admin");
  await expect(
    page.getByRole("heading", { name: "Operations access required" }),
  ).toBeVisible();
  await expect(
    page.getByRole("button", { name: "Return to ClipQuest" }),
  ).toBeVisible();
});

async function installMocks(page: Page): Promise<Scenario> {
  const scenario: Scenario = {
    adminMode: "allowed",
    answerCorrect: true,
    completedAttempt: false,
    generationMode: "stable",
    importMode: "success",
    extensionCaptionImport: false,
    requestedPaths: [],
    quizImportBodies: [],
    quizImportKeys: [],
  };

  await page.route("**/test-thumbnail.svg", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "image/svg+xml",
      body: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#4856D8"/><stop offset="1" stop-color="#43BCEB"/></linearGradient></defs><rect width="800" height="450" rx="28" fill="url(#g)"/><circle cx="630" cy="100" r="82" fill="#B8F244" opacity=".9"/><path d="M322 118v214l184-107z" fill="#fff" opacity=".94"/><text x="54" y="390" fill="#fff" font-size="36" font-family="Arial" font-weight="700">LEARNING SCIENCE</text></svg>`,
    });
  });

  await page.route("**/api/**", async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    const path = url.pathname;
    scenario.requestedPaths.push(path);

    if (path === "/api/auth/get-session") {
      await json(route, sessionFixture());
      return;
    }
    if (path === "/api/admin/me") {
      if (scenario.adminMode === "denied") {
        await json(
          route,
          {
            error: {
              code: "admin_access_required",
              message: "You do not have access to ClipQuest operations.",
            },
          },
          403,
        );
        return;
      }
      await json(route, {
        user: {
          id: "99999999-9999-4999-8999-999999999999",
          name: "Avery Learner",
          email: "avery@example.com",
          role: "owner",
        },
        permissions: [
          "overview:read",
          "users:read",
          "users:moderate",
          "users:set-role",
          "jobs:read",
          "jobs:manage",
          "lessons:read",
          "audit:read",
          "system:read",
        ],
      });
      return;
    }
    if (path === "/api/admin/overview") {
      await json(route, {
        totals: { users: 1284, lessons: 3762, activeJobs: 7, failedJobs: 3 },
        activity: { newUsers7d: 86, lessons7d: 412, completedAttempts7d: 1205 },
        recentFailures: [
          {
            id: JOB_ID,
            videoTitle: "Neural networks explained visually",
            ownerEmail: "learner@example.com",
            errorCode: "generation_failed",
            errorMessage:
              "The question provider returned an incomplete response.",
            updatedAt: "2026-07-31T09:40:00.000Z",
          },
        ],
      });
      return;
    }
    if (path === "/api/admin/users" && request.method() === "GET") {
      await json(route, {
        users: [
          {
            id: ADMIN_USER_ID,
            name: "Morgan Operator",
            email: "morgan@example.com",
            username: "morgan",
            role: "admin",
            banned: false,
            banReason: null,
            banExpiresAt: null,
            emailVerified: true,
            createdAt: "2026-07-12T08:00:00.000Z",
            lastSeenAt: "2026-07-31T09:45:00.000Z",
            lessonCount: 18,
            attemptCount: 42,
          },
          {
            id: "13131313-1313-4131-8131-131313131313",
            name: "Lin Student",
            email: "lin@example.com",
            username: "linlearns",
            role: "user",
            banned: true,
            banReason: "Repeated abuse reports",
            banExpiresAt: null,
            emailVerified: true,
            createdAt: "2026-07-20T08:00:00.000Z",
            lastSeenAt: "2026-07-29T10:00:00.000Z",
            lessonCount: 5,
            attemptCount: 9,
          },
        ],
        pagination: { page: 1, pageSize: 20, total: 2 },
      });
      return;
    }
    if (path === "/api/admin/jobs" && request.method() === "GET") {
      await json(route, {
        jobs: [
          {
            id: JOB_ID,
            state: "failed",
            stage: "creating_questions",
            progress: 0.58,
            errorCode: "generation_failed",
            errorMessage:
              "The transcript could not create trustworthy questions.",
            cancelRequested: false,
            createdAt: "2026-07-31T09:30:00.000Z",
            updatedAt: "2026-07-31T09:40:00.000Z",
            owner: {
              id: ADMIN_USER_ID,
              name: "Morgan Operator",
              email: "morgan@example.com",
            },
            video: {
              id: VIDEO_ID,
              title: importedVideo.video.title,
              source: "youtube",
            },
          },
        ],
        pagination: { page: 1, pageSize: 20, total: 1 },
      });
      return;
    }
    if (path === "/api/admin/lessons" && request.method() === "GET") {
      await json(route, {
        lessons: [
          {
            id: QUIZ_ID,
            language: "en",
            sessionLength: "medium",
            watched: true,
            createdAt: "2026-07-31T08:00:00.000Z",
            questionCount: 10,
            attemptCount: 6,
            owner: {
              id: ADMIN_USER_ID,
              name: "Morgan Operator",
              email: "morgan@example.com",
            },
            video: {
              id: VIDEO_ID,
              title: importedVideo.video.title,
              source: "youtube",
            },
          },
        ],
        pagination: { page: 1, pageSize: 20, total: 1 },
      });
      return;
    }
    if (path === "/api/admin/audit" && request.method() === "GET") {
      await json(route, {
        entries: [
          {
            id: "14141414-1414-4141-8141-141414141414",
            action: "generation.retry",
            targetType: "generation_job",
            targetId: JOB_ID,
            reason: "Provider recovered after a short outage",
            outcome: "success",
            metadata: { previousState: "failed" },
            createdAt: "2026-07-31T09:50:00.000Z",
            actor: {
              id: "99999999-9999-4999-8999-999999999999",
              name: "Avery Learner",
              email: "avery@example.com",
            },
          },
        ],
        pagination: { page: 1, pageSize: 25, total: 1 },
      });
      return;
    }
    if (path === "/api/admin/system") {
      await json(route, {
        configuration: {
          authentication: true,
          generation: true,
          email: true,
          youtubeEncryption: true,
          youtubeDemoHistory: false,
        },
        model: "deepseek-v4-flash",
        jobs: { queued: 4, running: 3, complete: 3755, failed: 3 },
        database: {
          migration: "0007_admin_audit_retention",
          auditEnabled: true,
        },
      });
      return;
    }
    if (path.startsWith("/api/admin/") && request.method() === "POST") {
      await json(route, { ok: true });
      return;
    }
    if (path === "/api/library") {
      await json(route, {
        dueReviews: [dueCard],
        saved: [savedCard],
        youtubeSuggestions: [],
      });
      return;
    }
    if (path === "/api/videos/import") {
      if (scenario.importMode === "unavailable") {
        await json(
          route,
          {
            error: {
              code: "video_unavailable",
              message: "This video is private or unavailable.",
            },
          },
          422,
        );
        return;
      }
      const body = request.postDataJSON() as { url?: string };
      const bilibili = body.url?.includes("bilibili");
      const usesExtensionCaptions =
        scenario.extensionCaptionImport && !bilibili;
      await json(route, {
        ...importedVideo,
        video: {
          ...importedVideo.video,
          source: bilibili ? "bilibili" : "youtube",
          sourceVideoId: bilibili
            ? "BV1clipquest"
            : usesExtensionCaptions
              ? "SVb9OV0bLzI"
              : importedVideo.video.sourceVideoId,
          durationSeconds: usesExtensionCaptions
            ? 0
            : importedVideo.video.durationSeconds,
        },
        ...(usesExtensionCaptions
          ? {
              captions: {
                available: true,
                tracks: [],
                browserSourceAvailable: false,
                browserLookupAvailable: true,
              },
              capture: {
                expectedDurationSeconds: 0,
                requiresUserGesture: false,
              },
            }
          : {}),
      });
      return;
    }
    if (path === "/api/quiz-imports" && request.method() === "POST") {
      scenario.quizImportBodies.push(request.postDataJSON());
      scenario.quizImportKeys.push(
        request.headers()["idempotency-key"] ?? null,
      );
      await json(route, { quizId: QUIZ_ID }, 201);
      return;
    }
    if (
      path === `/api/quizzes/${QUIZ_ID}/start` &&
      request.method() === "POST"
    ) {
      await json(
        route,
        { attemptId: ATTEMPT_ID, primer: null, question: baseQuestion },
        201,
      );
      return;
    }
    if (path.endsWith("/resume") && path.includes("/api/attempts/")) {
      const completed =
        scenario.completedAttempt || path.includes(COMPLETE_ATTEMPT_ID);
      await json(route, {
        attemptId: completed ? COMPLETE_ATTEMPT_ID : ATTEMPT_ID,
        question: completed ? null : baseQuestion,
        completed,
        score: completed ? 88 : null,
        mastery: completed ? "mastered" : null,
      });
      return;
    }
    if (path.endsWith("/answer") && path.includes("/api/attempts/")) {
      await json(route, {
        correct: scenario.answerCorrect,
        explanation: scenario.answerCorrect
          ? "Reconstructing an idea strengthens the retrieval path and reveals what still needs practice."
          : "The key is effortful reconstruction: recalling the idea strengthens access to it later.",
        evidenceSegmentIds: ["segment-1"],
        nextQuestion,
        completed: false,
        score: null,
        mastery: null,
      });
      return;
    }

    await json(
      route,
      {
        error: { code: "unmocked_request", message: `No fixture for ${path}` },
      },
      404,
    );
  });

  return scenario;
}

async function seed(page: Page, key: string, value: unknown): Promise<void> {
  await page.evaluate(
    ({ storageKey, storedValue }) =>
      window.localStorage.setItem(storageKey, JSON.stringify(storedValue)),
    { storageKey: key, storedValue: value },
  );
}

async function seedAttempt(
  page: Page,
  attemptId: string,
  question: typeof baseQuestion,
): Promise<void> {
  await seed(page, `clipquest:attempt:${attemptId}`, {
    attemptId,
    primer: null,
    question,
    primerSeen: true,
  });
}

async function capture(page: Page, name: string): Promise<void> {
  await page.screenshot({
    path: `${SCREENSHOT_DIR}/${name}.png`,
    fullPage: true,
    animations: "disabled",
  });
}

async function json(route: Route, body: unknown, status = 200): Promise<void> {
  await route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

function sessionFixture() {
  return {
    user: {
      id: "99999999-9999-4999-8999-999999999999",
      name: "Avery Learner",
      email: "avery@example.com",
      emailVerified: true,
      image: null,
      ageConfirmed: true,
      role: "user",
      banned: false,
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
    },
    session: {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      userId: "99999999-9999-4999-8999-999999999999",
      token: "playwright-session",
      expiresAt: "2026-08-31T00:00:00.000Z",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
    },
  };
}
