// Web (Chrome-extension) page-tool responder.
//
// On web the Workplace orchestrator runs inside the ClipQuest extension, which
// holds the learner's DeepSeek key. Tools that need the learner's authenticated
// ClipQuest session -- searching the owned library, reading saved notes -- are
// delegated back to this page over the extension bridge as a bounded
// "workplace-tool-request" handshake. Answering that handshake is what makes
// `search_library` work on web: without it every library search timed out.
//
// This module reuses the exact same platform-free executors the native clients
// use (`createWorkplaceToolExecutors`), wired to the shared authenticated
// `/api/library` + cheat-sheet access, so the summaries, bounded results, and
// citations are identical across platforms. Raw captions/notes never leave the
// page here -- only the bounded, sanitized envelopes the executors emit.
import { CheatSheetResponseSchema } from "@clipquest/contracts";
import type { WorkplaceChatToolName } from "@clipquest/local-quiz-engine";
import { apiRequest, ClientApiError } from "../lib/api";
import { fetchOwnedLibraryCards, searchOwnedLibrary } from "./owned-library";
import {
  createWorkplaceToolExecutors,
  type WorkplaceNotesSource,
  type WorkplaceToolServices,
} from "./tool-executors";

/** The engine-facing tool names the extension delegates to the page. */
type PageToolName = WorkplaceChatToolName;

async function loadOwnedNotes(
  videoId: string,
  signal?: AbortSignal,
): Promise<WorkplaceNotesSource | null> {
  const cards = await fetchOwnedLibraryCards(signal);
  const card = cards.find((entry) => entry.videoId === videoId);
  if (!card || card.cheatSheet.status !== "ready" || !card.cheatSheet.sheetId) {
    return null;
  }
  try {
    const sheet = await apiRequest(
      `/api/cheat-sheets/${encodeURIComponent(card.cheatSheet.sheetId)}`,
      { signal },
      CheatSheetResponseSchema,
    );
    if (!sheet.document) return null;
    return { title: card.title, document: sheet.document };
  } catch (error) {
    if (
      error instanceof ClientApiError &&
      error.code === "cheat_sheet_not_found"
    ) {
      return null;
    }
    throw error;
  }
}

/**
 * Authenticated page services for the tools the page can answer. Captions on
 * web are extracted locally by the extension, so `loadCaptions` here is only a
 * graceful "unavailable" fallback. Practice generation needs the DeepSeek key,
 * which stays in the extension, so it is not answered from the page.
 */
export function createWebWorkplacePageServices(): Pick<
  WorkplaceToolServices,
  "searchLibrary" | "loadCaptions" | "loadNotes"
> {
  return {
    searchLibrary: (query, limit, signal) =>
      searchOwnedLibrary(query, limit, signal),
    loadCaptions: async () => null,
    loadNotes: (videoId, signal) => loadOwnedNotes(videoId, signal),
  };
}

/**
 * Answer one delegated page-tool request from the extension. Returns the
 * bounded envelope the extension expects, or a bounded `{ error }` object for a
 * tool the page cannot fulfil so the turn never hangs on the extension's page
 * handshake timeout.
 */
export async function respondToWorkplacePageTool(
  name: string,
  args: unknown,
  signal?: AbortSignal,
): Promise<unknown> {
  const services = createWebWorkplacePageServices();
  const executors = createWorkplaceToolExecutors({
    ...services,
    // Practice generation is never delegated to the page on web; if the model
    // asks, surface a bounded error rather than silently hanging.
    generatePracticeSet: async () => {
      throw new Error(
        "Practice sets are generated by the ClipQuest extension, not the web page.",
      );
    },
  });
  const toolArgs =
    args && typeof args === "object" ? (args as Record<string, unknown>) : {};
  const ctx = { recentVideoIds: [] as string[], signal };
  try {
    switch (name as PageToolName) {
      case "search_library":
        return await executors.searchLibrary!(toolArgs as never, ctx);
      case "read_pdf_notes":
        return await executors.readPdfNotes!(toolArgs as never, ctx);
      case "read_video_captions":
        return await executors.readVideoCaptions!(toolArgs as never, ctx);
      default:
        return {
          error: `Unsupported page tool: ${String(name).slice(0, 64)}`,
        };
    }
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "The tool could not run.";
    return { error: message.slice(0, 300) };
  }
}
