(function installCaptionCore(globalScope) {
  "use strict";

  const MAX_CAPTION_BYTES = 8 * 1024 * 1024;
  const MAX_SEGMENTS = 60_000;

  function cleanText(value) {
    return String(value ?? "")
      .replaceAll("\n", " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function trackLabel(track) {
    if (typeof track?.name?.simpleText === "string") {
      return track.name.simpleText;
    }
    if (Array.isArray(track?.name?.runs)) {
      return cleanText(track.name.runs.map((run) => run?.text ?? "").join(""));
    }
    return typeof track?.languageCode === "string"
      ? track.languageCode
      : "Unknown";
  }

  function normalizeTrack(track) {
    if (!track || typeof track.baseUrl !== "string") return null;
    let url;
    try {
      url = new URL(track.baseUrl);
    } catch {
      return null;
    }
    if (
      url.protocol !== "https:" ||
      (url.hostname !== "youtube.com" && !url.hostname.endsWith(".youtube.com"))
    ) {
      return null;
    }
    const language =
      typeof track.languageCode === "string" && track.languageCode.length <= 35
        ? track.languageCode
        : "und";
    return {
      baseUrl: url.toString(),
      language,
      label: trackLabel(track),
      isAutoGenerated: track.kind === "asr",
      isTranslatable: track.isTranslatable === true,
    };
  }

  function selectTrack(rawTracks, preferredLanguage) {
    const tracks = (Array.isArray(rawTracks) ? rawTracks : [])
      .map(normalizeTrack)
      .filter(Boolean);
    if (!tracks.length) return null;
    const preferred = String(preferredLanguage ?? "").toLowerCase();
    const primary = preferred.split("-")[0];
    const exact = tracks.filter(
      (track) => track.language.toLowerCase() === preferred,
    );
    const related = tracks.filter(
      (track) => track.language.toLowerCase().split("-")[0] === primary,
    );
    return (
      exact.find((track) => !track.isAutoGenerated) ??
      exact[0] ??
      related.find((track) => !track.isAutoGenerated) ??
      related[0] ??
      tracks.find((track) => !track.isAutoGenerated) ??
      tracks[0]
    );
  }

  function parseJson3(payload) {
    const events = Array.isArray(payload?.events) ? payload.events : [];
    const segments = [];
    for (let index = 0; index < events.length; index += 1) {
      const event = events[index];
      if (!Array.isArray(event?.segs)) continue;
      const text = cleanText(
        event.segs.map((segment) => segment?.utf8 ?? "").join(""),
      );
      if (!text) continue;
      const startMs = Math.max(0, Math.floor(Number(event.tStartMs) || 0));
      const durationMs = Math.max(
        1,
        Math.floor(Number(event.dDurationMs) || 3_000),
      );
      segments.push({
        id: `youtube-extension-${index}-${startMs}`,
        startMs,
        endMs: startMs + durationMs,
        text,
      });
      if (segments.length > MAX_SEGMENTS) {
        throw new Error("YouTube returned too many caption segments.");
      }
    }
    return segments;
  }

  function decodeXml(value) {
    const textarea = document.createElement("textarea");
    textarea.innerHTML = value;
    return textarea.value;
  }

  function parseXml(xml) {
    const segments = [];
    const expression = /<text\b([^>]*)>([\s\S]*?)<\/text>/gi;
    let match;
    let index = 0;
    while ((match = expression.exec(xml))) {
      const attributes = match[1] ?? "";
      const start = attributes.match(/\bstart="([0-9.]+)"/i)?.[1];
      const duration = attributes.match(/\bdur="([0-9.]+)"/i)?.[1];
      const text = cleanText(decodeXml(match[2] ?? ""));
      if (!text) continue;
      const startMs = Math.max(0, Math.floor(Number(start) * 1_000 || 0));
      const durationMs = Math.max(
        1,
        Math.floor(Number(duration) * 1_000 || 3_000),
      );
      segments.push({
        id: `youtube-extension-xml-${index}-${startMs}`,
        startMs,
        endMs: startMs + durationMs,
        text,
      });
      index += 1;
      if (segments.length > MAX_SEGMENTS) {
        throw new Error("YouTube returned too many caption segments.");
      }
    }
    const paragraphExpression = /<p\b([^>]*)>([\s\S]*?)<\/p>/gi;
    while ((match = paragraphExpression.exec(xml))) {
      const attributes = match[1] ?? "";
      const start = attributes.match(/\bt="([0-9.]+)"/i)?.[1];
      const duration = attributes.match(/\bd="([0-9.]+)"/i)?.[1];
      const text = cleanText(
        decodeXml((match[2] ?? "").replace(/<[^>]+>/g, "")),
      );
      if (!text || start === undefined) continue;
      const startMs = Math.max(0, Math.floor(Number(start) || 0));
      const durationMs = Math.max(1, Math.floor(Number(duration) || 3_000));
      segments.push({
        id: `youtube-extension-xml-${index}-${startMs}`,
        startMs,
        endMs: startMs + durationMs,
        text,
      });
      index += 1;
      if (segments.length > MAX_SEGMENTS) {
        throw new Error("YouTube returned too many caption segments.");
      }
    }
    return segments;
  }

  function parseTimestamp(value) {
    const parts = String(value).trim().split(":").map(Number);
    if (parts.some((part) => !Number.isFinite(part))) return null;
    if (parts.length === 2) return (parts[0] * 60 + parts[1]) * 1_000;
    if (parts.length === 3) {
      return (parts[0] * 3_600 + parts[1] * 60 + parts[2]) * 1_000;
    }
    return null;
  }

  function finalizePanelSegments(rows) {
    const ordered = rows
      .filter(
        (row) =>
          Number.isFinite(row?.startMs) &&
          row.startMs >= 0 &&
          cleanText(row?.text),
      )
      .sort((left, right) => left.startMs - right.startMs);
    const unique = [];
    const seen = new Set();
    for (const row of ordered) {
      const text = cleanText(row.text);
      const key = `${row.startMs}:${text}`;
      if (seen.has(key)) continue;
      seen.add(key);
      unique.push({ startMs: Math.floor(row.startMs), text });
      if (unique.length > MAX_SEGMENTS) {
        throw new Error("YouTube returned too many caption segments.");
      }
    }
    return unique.map((row, index) => ({
      id: `youtube-extension-panel-${index}-${row.startMs}`,
      startMs: row.startMs,
      endMs: Math.max(
        row.startMs + 1,
        unique[index + 1]?.startMs ?? row.startMs + 30_000,
      ),
      text: row.text,
    }));
  }

  function assertPayloadSize(body) {
    if (new TextEncoder().encode(body).byteLength > MAX_CAPTION_BYTES) {
      throw new Error("YouTube captions exceeded the safe size limit.");
    }
  }

  globalScope.ClipQuestCaptionCore = Object.freeze({
    MAX_CAPTION_BYTES,
    cleanText,
    finalizePanelSegments,
    parseJson3,
    parseTimestamp,
    parseXml,
    selectTrack,
    assertPayloadSize,
  });
})(globalThis);
