(function installYouTubeExtractor() {
  "use strict";

  const core = globalThis.ClipQuestCaptionCore;
  const REQUEST_EVENT = "clipquest:youtube:tracks-request:v1";
  const RESPONSE_EVENT = "clipquest:youtube:tracks-response:v1";
  const TRANSCRIPT_WORDS =
    /transcript|show transcript|文字记录|文字記錄|轉錄|字幕|トランスクリプト|transcripci[oó]n|transcription|transkript/i;

  function delay(milliseconds) {
    return new Promise((resolve) => setTimeout(resolve, milliseconds));
  }

  function currentVideoId() {
    return new URL(location.href).searchParams.get("v");
  }

  function deepQueryAll(root, selector) {
    const matches = [];
    const visited = new Set();
    function visit(scope) {
      if (!scope || visited.has(scope)) return;
      visited.add(scope);
      if (typeof scope.querySelectorAll !== "function") return;
      matches.push(...scope.querySelectorAll(selector));
      for (const element of scope.querySelectorAll("*")) {
        if (element.shadowRoot) visit(element.shadowRoot);
      }
    }
    visit(root);
    return [...new Set(matches)];
  }

  function deepQueryOne(root, selector) {
    return deepQueryAll(root, selector)[0] ?? null;
  }

  function requestPlayerData(videoId, preferredLanguage) {
    return new Promise((resolve) => {
      const requestId = crypto.randomUUID();
      const timeout = setTimeout(() => {
        document.removeEventListener(RESPONSE_EVENT, receive);
        resolve({ tracks: [], transcriptRows: [] });
      }, 15_000);
      function receive(event) {
        if (event?.detail?.requestId !== requestId) return;
        clearTimeout(timeout);
        document.removeEventListener(RESPONSE_EVENT, receive);
        resolve({
          tracks: Array.isArray(event.detail.tracks) ? event.detail.tracks : [],
          captionBody:
            typeof event.detail.captionBody === "string"
              ? event.detail.captionBody
              : undefined,
          transcriptRows: Array.isArray(event.detail.transcriptRows)
            ? event.detail.transcriptRows
            : [],
          transcriptError: event.detail.transcriptError,
        });
      }
      document.addEventListener(RESPONSE_EVENT, receive);
      document.dispatchEvent(
        new CustomEvent(REQUEST_EVENT, {
          detail: { requestId, videoId, preferredLanguage },
        }),
      );
    });
  }

  async function downloadTrack(track) {
    const url = new URL(track.baseUrl);
    if (
      url.protocol !== "https:" ||
      url.hostname !== "www.youtube.com" ||
      url.pathname !== "/api/timedtext"
    ) {
      throw new Error("YouTube returned an unsafe caption URL.");
    }
    url.searchParams.set("fmt", "json3");
    const response = await fetch(url, {
      cache: "no-store",
      credentials: "include",
      headers: { Accept: "application/json, text/xml;q=0.8" },
    });
    if (!response.ok) {
      throw new Error(`YouTube caption download failed (${response.status}).`);
    }
    const declaredLength = Number(response.headers.get("content-length") ?? 0);
    if (declaredLength > core.MAX_CAPTION_BYTES) {
      throw new Error("YouTube captions exceeded the safe size limit.");
    }
    const body = await response.text();
    core.assertPayloadSize(body);
    let segments = [];
    try {
      segments = core.parseJson3(JSON.parse(body));
    } catch {
      segments = core.parseXml(body);
    }
    if (!segments.length) throw new Error("YouTube returned empty captions.");
    return {
      language: track.language,
      isAutoGenerated: track.isAutoGenerated,
      sourceSegmentCount: segments.length,
      segments,
      method: "caption_track",
    };
  }

  function transcriptPanel() {
    const selectors = [
      'ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"]',
      'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"]',
      "ytd-transcript-search-panel-renderer",
      "#engagement-panel-searchable-transcript",
    ];
    return selectors
      .map((selector) => deepQueryOne(document, selector))
      .find(Boolean);
  }

  function transcriptRows(panel) {
    return deepQueryAll(
      panel,
      "transcript-segment-view-model, .ytwTranscriptSegmentViewModelHost, ytd-transcript-segment-renderer",
    );
  }

  async function openTranscriptPanel() {
    const expand = deepQueryOne(
      document,
      '#expand, tp-yt-paper-button#expand, [aria-label="Show more"], [aria-label*="Show more"]',
    );
    if (expand) {
      expand.click();
      await delay(350);
    }
    const descriptionTranscript = deepQueryOne(
      document,
      "ytd-video-description-transcript-section-renderer",
    );
    if (descriptionTranscript) {
      descriptionTranscript.click();
      await delay(600);
      const openedPanel = transcriptPanel();
      if (openedPanel && transcriptRows(openedPanel).length > 0) return true;
    }
    const direct = deepQueryOne(
      document,
      'button[aria-label="Show transcript"], button[aria-label*="Show transcript"], button[aria-label*="Transcript"], ytd-video-description-transcript-section-renderer button',
    );
    if (direct) {
      direct.click();
      await delay(600);
      return true;
    }
    const buttons = deepQueryAll(
      document,
      "button, ytd-menu-service-item-renderer, tp-yt-paper-item",
    );
    const button = buttons.find((element) =>
      TRANSCRIPT_WORDS.test(
        `${element.getAttribute?.("aria-label") ?? ""} ${element.textContent ?? ""}`,
      ),
    );
    if (!button) return false;
    button.click();
    await delay(600);
    return true;
  }

  function rowValue(row) {
    const timestampElement = deepQueryOne(
      row,
      ".segment-timestamp, .ytwTranscriptSegmentViewModelTimestamp",
    );
    const textElement = deepQueryOne(
      row,
      ".segment-text, .ytwTranscriptSegmentViewModelSegment, yt-formatted-string.segment-text",
    );
    const lines = String(row.innerText ?? row.textContent ?? "")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    const timestamp =
      timestampElement?.textContent?.trim() ??
      lines.find((line) => /^\d{1,3}:\d{2}(?::\d{2})?$/.test(line));
    const startMs = core.parseTimestamp(timestamp);
    if (startMs === null) return null;
    const text = core.cleanText(
      textElement?.textContent ??
        lines.filter((line) => line !== timestamp).join(" "),
    );
    return text ? { startMs, text } : null;
  }

  function scrollContainer(panel) {
    const candidates = [
      deepQueryOne(panel, "#segments-container"),
      deepQueryOne(panel, "#content"),
      panel,
    ].filter(Boolean);
    return (
      candidates.find(
        (element) => element.scrollHeight > element.clientHeight + 10,
      ) ?? panel
    );
  }

  async function scrapeTranscriptPanel() {
    let panel = transcriptPanel();
    if (!panel || transcriptRows(panel).length === 0) {
      await openTranscriptPanel();
    }
    const deadline = Date.now() + 10_000;
    let retries = 0;
    while (
      (!panel || transcriptRows(panel).length === 0) &&
      Date.now() < deadline
    ) {
      await delay(200);
      panel = transcriptPanel();
      retries += 1;
      if (retries === 15 || retries === 30) {
        await openTranscriptPanel();
      }
    }
    if (!panel) throw new Error("YouTube did not expose a transcript panel.");

    const collected = new Map();
    const container = scrollContainer(panel);
    let stablePasses = 0;
    let lastSize = 0;
    for (let pass = 0; pass < 160 && stablePasses < 4; pass += 1) {
      for (const row of transcriptRows(panel)) {
        const value = rowValue(row);
        if (value) collected.set(`${value.startMs}:${value.text}`, value);
      }
      stablePasses = collected.size === lastSize ? stablePasses + 1 : 0;
      lastSize = collected.size;
      const previousTop = container.scrollTop;
      container.scrollTop = Math.min(
        container.scrollHeight,
        previousTop + Math.max(container.clientHeight * 0.85, 420),
      );
      container.dispatchEvent(new Event("scroll", { bubbles: true }));
      await delay(120);
      if (
        container.scrollTop === previousTop &&
        container.scrollTop + container.clientHeight >=
          container.scrollHeight - 2
      ) {
        stablePasses += 1;
      }
    }
    const segments = core.finalizePanelSegments([...collected.values()]);
    if (!segments.length) throw new Error("YouTube returned empty captions.");
    return {
      language: document.documentElement.lang || "und",
      isAutoGenerated: null,
      sourceSegmentCount: segments.length,
      segments,
      method: "transcript_panel",
    };
  }

  async function extract(request) {
    if (!/^[\w-]{11}$/.test(request.videoId)) {
      throw new Error("The YouTube video id is invalid.");
    }
    if (currentVideoId() !== request.videoId) {
      throw new Error("The opened YouTube video did not match the request.");
    }
    let directError;
    const playerData = await requestPlayerData(
      request.videoId,
      request.preferredLanguage,
    );
    const track = core.selectTrack(
      playerData.tracks,
      request.preferredLanguage,
    );
    if (playerData.captionBody) {
      core.assertPayloadSize(playerData.captionBody);
      let segments = [];
      try {
        segments = core.parseJson3(JSON.parse(playerData.captionBody));
      } catch {
        segments = core.parseXml(playerData.captionBody);
      }
      if (segments.length) {
        return {
          videoId: request.videoId,
          language: track?.language ?? document.documentElement.lang ?? "und",
          isAutoGenerated: track?.isAutoGenerated ?? null,
          sourceSegmentCount: segments.length,
          segments,
          method: "youtube_player_capture",
        };
      }
    }
    if (track) {
      try {
        return { ...(await downloadTrack(track)), videoId: request.videoId };
      } catch (error) {
        directError = error;
      }
    }
    const innerTubeSegments = core.finalizePanelSegments(
      playerData.transcriptRows,
    );
    if (innerTubeSegments.length) {
      return {
        videoId: request.videoId,
        language: track?.language ?? document.documentElement.lang ?? "und",
        isAutoGenerated: track?.isAutoGenerated ?? null,
        sourceSegmentCount: innerTubeSegments.length,
        segments: innerTubeSegments,
        method: "youtube_transcript_api",
      };
    }
    try {
      return {
        ...(await scrapeTranscriptPanel()),
        videoId: request.videoId,
      };
    } catch (panelError) {
      const panelMessage =
        panelError instanceof Error
          ? panelError.message
          : "Transcript fallback failed.";
      throw new Error(
        directError instanceof Error
          ? `${directError.message} Transcript fallback failed: ${playerData.transcriptError ?? panelMessage}`
          : panelMessage,
      );
    }
  }

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type !== "clipquest.youtube.extract.v1") return false;
    void extract(message)
      .then((result) => sendResponse({ ok: true, result }))
      .catch((error) =>
        sendResponse({
          ok: false,
          error:
            error instanceof Error
              ? error.message
              : "Caption extraction failed.",
        }),
      );
    return true;
  });
})();
