import { afterEach, describe, expect, it, vi } from "vitest";
import {
  extractYouTubePlayerResponse,
  loadCachedYouTubeSource,
  loadYouTubeCaptionSegments,
  parseYouTubePlayerResponse,
  parseYouTubeTimedText,
  selectPreferredYouTubeCaptionTrack,
} from "../src/sources/youtube";

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("YouTube timed text", () => {
  it("loads a validated first-party transcript cache for the requested video", async () => {
    const get = vi.fn().mockResolvedValue({
      size: 512,
      json: async () => ({
        sourceVideoId: "BjRvQbWsTfM",
        title: "AP Computer Science A - Unit 1: Primitive Types",
        durationSeconds: 1637,
        captionTrack: {
          language: "en",
          label: "English (auto-generated)",
          isAutoGenerated: true,
        },
        timedText: {
          events: [
            {
              tStartMs: 0,
              dDurationMs: 500,
              segs: [{ utf8: "Primitive types store simple values." }],
            },
          ],
        },
      }),
    });

    await expect(
      loadCachedYouTubeSource(
        { get } as unknown as R2Bucket,
        new URL(
          "https://www.youtube.com/watch?v=BjRvQbWsTfM&list=PLmpmyPywZ440vPqpAPeUkE-TeKifbS45W",
        ),
      ),
    ).resolves.toMatchObject({
      sourceVideoId: "BjRvQbWsTfM",
      title: "AP Computer Science A - Unit 1: Primitive Types",
      preferredCaptionSegments: [
        {
          startMs: 0,
          endMs: 500,
          text: "Primitive types store simple values.",
        },
      ],
    });
    expect(get).toHaveBeenCalledWith("source-cache/youtube/BjRvQbWsTfM.json");
  });

  it("extracts bounded player metadata without being confused by braces inside strings", () => {
    const html = `<script>var ytInitialPlayerResponse = ${JSON.stringify({
      videoDetails: {
        title: "Neural {networks}",
        lengthSeconds: "1120",
        thumbnail: {
          thumbnails: [{ url: "https://i.ytimg.com/example.jpg", width: 480 }],
        },
      },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              baseUrl: "https://www.youtube.com/api/timedtext?signed=yes",
              languageCode: "en",
              name: { runs: [{ text: "English" }] },
            },
          ],
        },
      },
    })};</script>`;

    expect(
      parseYouTubePlayerResponse(extractYouTubePlayerResponse(html)),
    ).toEqual({
      title: "Neural {networks}",
      durationSeconds: 1120,
      thumbnails: [{ url: "https://i.ytimg.com/example.jpg", width: 480 }],
      tracks: [
        {
          base_url: "https://www.youtube.com/api/timedtext?signed=yes",
          language_code: "en",
          label: "English",
        },
      ],
    });
  });

  it("turns json3 events into normalized transcript segments", () => {
    expect(
      parseYouTubeTimedText({
        events: [
          {
            tStartMs: 100,
            dDurationMs: 450,
            segs: [{ utf8: "Hello" }, { utf8: "   world" }],
          },
          { tStartMs: "700", segs: [{ utf8: "Next\nline" }] },
          { tStartMs: 900, segs: [{ acAsrConf: 0 }] },
        ],
      }),
    ).toEqual([
      { id: "yt-1", startMs: 100, endMs: 550, text: "Hello world" },
      { id: "yt-2", startMs: 700, endMs: 1_700, text: "Next line" },
    ]);
  });

  it("prefers manual English, then Chinese, before unrelated or generated tracks", () => {
    const tracks = [
      {
        base_url: "https://www.youtube.com/api/timedtext",
        language_code: "fr",
      },
      {
        base_url: "https://www.youtube.com/api/timedtext",
        language_code: "en",
        kind: "asr" as const,
      },
      {
        base_url: "https://www.youtube.com/api/timedtext",
        language_code: "zh-Hans",
      },
      {
        base_url: "https://www.youtube.com/api/timedtext",
        language_code: "en-GB",
      },
    ];
    expect(selectPreferredYouTubeCaptionTrack(tracks)).toBe(tracks[3]);
  });

  it("loads json3 only from an HTTPS YouTube host", async () => {
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(
        JSON.stringify({
          events: [
            { tStartMs: 0, dDurationMs: 500, segs: [{ utf8: "Caption" }] },
          ],
        }),
        {
          status: 200,
          headers: { "content-type": "application/json" },
        },
      ),
    );
    vi.stubGlobal("fetch", fetchMock);

    await expect(
      loadYouTubeCaptionSegments({
        base_url: "https://www.youtube.com/api/timedtext?v=video-id",
        language_code: "en",
      }),
    ).resolves.toEqual([
      { id: "yt-1", startMs: 0, endMs: 500, text: "Caption" },
    ]);
    expect(fetchMock).toHaveBeenCalledWith(
      expect.objectContaining({ hostname: "www.youtube.com" }),
      expect.objectContaining({ redirect: "error" }),
    );

    await expect(
      loadYouTubeCaptionSegments({
        base_url: "https://youtube.com.attacker.example/api/timedtext",
        language_code: "en",
      }),
    ).rejects.toThrow("YouTube captions could not be loaded");
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});
