export const voxelIconNames = [
  "appearance",
  "audit",
  "back",
  "calendar",
  "captions",
  "checkbox-checked",
  "checkbox-unchecked",
  "checklist",
  "close",
  "collapse",
  "correct",
  "database",
  "download",
  "error",
  "expand",
  "help",
  "home",
  "idea",
  "lessons",
  "library",
  "link",
  "mail",
  "model",
  "next",
  "notifications",
  "operations",
  "password",
  "people",
  "privacy",
  "processing",
  "progress",
  "refresh",
  "registration",
  "search",
  "selected",
  "settings",
  "sign-in",
  "system",
  "target",
  "time",
  "translation",
  "video",
  "warning",
] as const;

export type VoxelIconName = (typeof voxelIconNames)[number];
